### ISSUE TITLE
Add patient register questions

### ISSUE THREAD

**Issue by allan-allay** [onaio/rdt-standard#101]
Additional patient registration questions should be added to the patient registration form. 
The questions are on the [Patient Register Questions Google sheet](https://docs.google.com/spreadsheets/d/1c-QiAFmK2eoia_6Jh8xuSCrO41flgAk1EyBkLvs0tQQ/edit#gid=72287250)
- Relevance should be used to show appropriate questions as specified in the sheet
- Rules Engine calculations can be used to determine whether to proceed to conduct RDT on completion of the registration

**Comment by vincent-karuri** [comment]
Done
