### ISSUE TITLE
Confirm Expiration Date from QR Code

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#111]
When we scan the QR code, we should be able to verify that it is okay to use via the expiration date.  If it is expired, it should create a toast message that it is expired, and return the user back to the patient screen to do another RDT.  I believe this already works for the CareStart test.  This needs to be implemented for Version 1.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 ok, what is the date format on the qr?

**Comment by shivenbhatt1** [comment]
This is set up exactly how Peter's rdt-ids.csv file is.  


openrdt.ona.io/#,310619,10017,M017G71,MalariaPfPv,5060511890000

url,exp date,ID number,Lot code,Test type,GS1 manufacturing ID

**Comment by vincent-karuri** [comment]
Thanks
