### ISSUE TITLE
Save QR code information for Expired RDTs

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#114]
We will need to save QR barcode information if it is scanned, even if it is not used and returned as an expired RDT.  We would like to collect this information to see how many times the CHW scans an expired RDT.  This should be implemented for v1 release as KEMRI will be using RDTs in the first batch beginning end of August.

**Comment by vincent-karuri** [comment]
What is the exact information that needs to be collected here?

**Comment by shivenbhatt1** [comment]
We would want to see that the RDT is scanned.  Just show that it was scanned.  Need to figure out how to save it before exiting.  Submit the form, link to the patient possibly.  Would be interesting to link this to the CHW ID as well - to see whether this is a single CHW that isn't checking expiration or across 25 CHWs.  Right now we are deploying 25 expired RDTs per location.  This approach could also work for counterfeit RDTs
