### ISSUE TITLE
Add sound at the end of 20 min timer

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#138]
Add some kind of noise and/or buzz so that the CHW is aware that they can now take image if they are not looking at their phone.

**Comment by vincent-karuri** [comment]
Adding vibration for both timers.

**Comment by shivenbhatt1** [comment]
We just need to make sure they  follow protocol, I just don't want them to miss the time frame or it will mess up our study intentions (making sure they adhere to protocol).  I envisioned this would have been a ping or short tone + vibration at the end of the 20 min timer alerting them to take image, and a longer alarm warning them at the end of the second 10 min timer making sure they take the photo right away.

**Comment by vincent-karuri** [comment]
OK. @rowo from a uniformity point of view, is this ok.

I was thinking that both should have similar tones / vibrations patterns?

**Comment by vincent-karuri** [comment]
Also @shivenbhatt1 the alarm is designed to quit when one moves on to the next step.

So there may not be enough time to hear the tone as the transition from 10min to 20 min timer happens.

**Comment by vincent-karuri** [comment]
@rowo The vibration urgency tones make sense. So the same alarm tone can be used?

@shivenbhatt1 I don't think we need the complex 8 min notification logic in this version.

Why not set the timer to a time below what is too late, like 5 min?
