### ISSUE TITLE
Need to update questions according to RDT Data dictionary

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#164]
Please update questions according to RDT data dictionary found here and ensure all questions are available, one is missing regarding the bednet.

https://docs.google.com/spreadsheets/d/1K7tEA_i70Hwvc60OK_S6y4qKATvs1f1F9bGS3KEmM6A/edit#gid=0

**Comment by vincent-karuri** [comment]
Fixed
