### ISSUE TITLE
Translate app to Bahasa for Indonesia

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#172]
The links below may be useful

https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/1082654721/Transifex+Adding+GitHub+Repositories

https://smartregister.atlassian.net/wiki/spaces/Documentation/pages/1139408961/Language+Switching+Implementation+Guide

**Comment by vincent-karuri** [comment]
@shivenbhatt1 may need you to help out with this since the form translation is not really a very technical task

**Comment by shivenbhatt1** [comment]
@vincent-karuri Lets discuss this thursday then, and if possible, I'll take care of this issue

**Comment by shivenbhatt1** [comment]
I have requested SID provide this by EOW, but we are waiting on some other data for TrueCover that they are busy with at the moment
