### ISSUE TITLE
Provide a way to visualize malaria case data on a map

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#174]
Will most probably use Kujaku. This issue needs fleshing out.

@shivenbhatt1 you can also add details of any UI components here. Or create a separate issues and reference this one as related.

**Edit:** this implementation is now only going to be done on the web dashboards

**Comment by shivenbhatt1** [comment]
@vincent-karuri Lets meet the team that knows this part this week/early next week to figure this out

**Comment by vincent-karuri** [comment]
Relevant links https://docs.mapbox.com/android/maps/examples/display-a-heatmap/ https://docs.mapbox.com/android/maps/examples/add-multiple-heatmap-styles/
https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/dds/HeatmapActivity.java

**Comment by shivenbhatt1** [comment]
@rowo

**Comment by rowo** [comment]
@vincent-karuri @shivenbhatt1 Are there any notes from conversations you've had so far?

**Comment by rowo** [comment]
Recent talk notes:
- Meant for computer (non mobile), web app
- Some examples of user goals are "looking specific RDT type data on a map + GPS points to each of those results" or "Finding the positive malaria cases" or comparing "Microscropy vs. RDT results — do they conform or not?" or "Break down by strains -  which are prevalent?"
- Next steps are Shiven is to write up the primary user goals and tasks when using the dashboard

**Comment by vincent-karuri** [comment]
@shivenbhatt1 @rowo don't we also need a design for mobile? Actually, this issue was for mobile.

We also need to consider which of the goals are catered and better displayed on mobile vs web.

Mobile should essentially hold only the most pertinent subset?

**Comment by shivenbhatt1** [comment]
@pld Suggested we use a computer interface for this. I'll work on creating a list of all the filters.

**Comment by pld** [comment]
This issue was created for mobile, but we later found out that isn't a part of our deliverables.

Since we now have reveal, wouldn't using that make sense for mobile map biz if we did want to do mobile?

**Comment by vincent-karuri** [comment]
OK, so no mobile visualisation, cool.

So the plan was to use Kujaku GeoWidget, which reveal is also using. Unless we have some tasking requirements.

**Comment by rowo** [comment]
@shivenbhatt1 not sure if we are able to do the design and requirements for this by this week as planned. For now I think this issue should probably be assigned to you to document the primary user goals and tasks

**Comment by shivenbhatt1** [comment]
https://docs.google.com/document/d/17_wNwoN6uwi81GesAkEp2G4tyK59esBlZT7AipeaY0k/edit

Filter list has been started

**Comment by vincent-karuri** [comment]
@shivenbhatt1 can we close this?
