### ISSUE TITLE
New Client Record Name needs to take numbers

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#176]
Need to address ASAP: Since KEMRI is recording patient IDs as their names, we need to be able to record numbers in the name section

**Comment by vincent-karuri** [comment]
@shivenbhatt1 Why do we need numbers only?

The patient (string) id is a UUID for uniqueness and doesn't get the ids from OpenMRS

**Comment by shivenbhatt1** [comment]
@vincent-karuri My understanding from my conversation with isabella was that they have their own unique patient IDs that they would input in.  But I will double check this information.

**Comment by shivenbhatt1** [comment]
@vincent-karuri currently the name input doesn't take any numbers

**Comment by vincent-karuri** [comment]
From what I've understood, the issue is with the form name field validating that the name field does not contain numbers.

In that case, the validation can be removed

**Comment by shivenbhatt1** [comment]
@vincent-karuri Exactly, that sounds good

**Comment by vincent-karuri** [comment]
Done.
