### ISSUE TITLE
Determine timeout image capture

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#178]
In the circumstance that a certain phone can't capture an image automatically, we need to pull up the phone's camera, take an image and store that image, then return back to the app to continue on.  This may also be needed for exp date or require a manual entry for that piece.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 It's still not clear to me how we intend to determine that the rdt capture is not able to capture the image.

And discern this from the user not properly focussing on the image. We will need to discuss how to definitively determine this

**Comment by vincent-karuri** [comment]
We don't want to always capture images that cannot be correctly interpreted by the app, or that are too bad to be interpreted by a machine learning algorithm.

This might be the case if we naively execute a simple timeout

**Comment by shivenbhatt1** [comment]
@vincent-karuri @pld This came up on the monthly call with BMGF/Arunan, apparently this is a workaround for Audere as well.  The idea is any image is better than no image, and it allows the user to move onto the next step.  For example, the J5 has been giving us issues and not properly capturing the rdt image.  Here we could set a timeout of 10 seconds if the image is not captured automatically, switch over to the phone camera, capture a regular image, save that image, and switch back over to the app to continue on, even if the image is not processed by the app.

**Comment by pld** [comment]
We could, I think this would be better placed in the image capture app. If there's a metric for image goodness, it could be capturing images as it goes, and if it times out without anything above the threshold it takes of those captured images the best one.

I don't know how much capture (and running an algo to compute the metric from the image) slows the app, that'd effect how feasible the above approach is.

If none of that's feasible, having the timeout be a parameter to the app, and having it be responsible for the image upon timeout would be better than switching to the phone camera app, the way processing happens is different (at least if the app is getting RAW data) in the app vs camera app.

I agree w/@vincent-karuri that capturing an image on timeout could produce images with no-value, but also w/the assessment that something is better than nothing. The other side of this is it's not feasible to block a healthcare worker from moving onto the next step, so the other option would be continue with no image, makes sense it's worth taking an image for the small chance of getting a usable image

**Comment by vincent-karuri** [comment]
I think UW were to try setting a timeout on their side @shivenbhatt1?

**Comment by shivenbhatt1** [comment]
@pld @vincent-karuri I can discuss this issue further with UW today, however, Arunan had cautioned me that the approach stated above was how Audere is conducting it, and that UW wasn't involved with their "manual override" and could be time consuming and/or difficult to achieve on their end.  I see how this could pose an issue with RAW image capture.  In addition we had a discussion on something Keith was developing for them, which could scan an image, pull out the RDT and analyze it for exactly this data set issue.

**Comment by vincent-karuri** [comment]
As an alternative, maybe we could also explore having a button appear after a timeout.

To allow the user to at least focus and/or position the rdt within the window before manually capturing the image.

May give better quality images than leaving this to chance.

**Comment by shivenbhatt1** [comment]
@vincent-karuri I think that's an excellent idea, just didn't know how difficult it would be to implement.

**Comment by vincent-karuri** [comment]
Cool, would need to scope it.

**Comment by shivenbhatt1** [comment]
@vincent-karuri If you get some time and since we are waiting for servers and bahasa translations, could you scope this out so I can get a sense of time required?

**Comment by vincent-karuri** [comment]
Cool, will do

**Comment by shivenbhatt1** [comment]
@rowo This would be a 15 second delay until the option for manual capture shows up giving the user the option to take a manual photo of the RDT.

**Comment by rowo** [comment]
@shivenbhatt1 Did you mean to @ me here? Regardless, I will summarize to get it clearer: For the first 15 seconds the camera tries to detect the QR code (or exp date?) and automatically takes a picture if detected. If it can't after 15 seconds, a button shows up to just take a pic. There is no timeout for that manual photo step, and taking the photo is required to move on.

The flash camera option is part of both the automatic photo and the manual photo interactions.

**Comment by shivenbhatt1** [comment]
@rowo Yes, sorry I created this in a rush but @vincent-karuri wanted a design mockup to know where he should put the buttons.

**Comment by vincent-karuri** [comment]
@rowo the button is mainly for the rdt image capture screen.

But I guess can be extended to the other screens if need be

**Comment by vincent-karuri** [comment]
The button can be similar to the camera default I guees

**Comment by rowo** [comment]
@vincent-karuri Would you might putting a screengrab here of the RDT image capture screen (where it tries to do it automatically)? 

Is it like the below?
![Untitled-1](https://user-images.githubusercontent.com/1584163/66068189-25a5a080-e51b-11e9-96d4-73f1e1d79a63.png)

And, if so, is this issue about:
1) Where the "take photo" button appears on this screen after 15 seconds. 
2) You need a way to turn on the light (for the auto QR reader) and a flash (for the manual photo after timeout) for https://github.com/onaio/rdt-standard/issues/190

**Comment by vincent-karuri** [comment]
![Screenshot_20191004-103102](https://user-images.githubusercontent.com/33488286/66189591-c4084200-e692-11e9-9cec-38d7e2e4ba6f.png)

**Comment by vincent-karuri** [comment]
@rowo  we need a flash option and a manual capture option (which appears after 15s) on this screen

**Comment by vincent-karuri** [comment]
Note that we have instructions / feedback to the user above and below the capture window

**Comment by shivenbhatt1** [comment]
Right now its possible to do manual image capture, but photo capture button has not been implemented

**Comment by rowo** [comment]
So can we just replace the bottom text with a standard photo button?

**Comment by shivenbhatt1** [comment]
@rowo I don't think we can remove anything that is there currently.  The flash/light control can be functional for both the RDT capture and the expiration date capture, but not for the QR code reader.

**Comment by shivenbhatt1** [comment]
@vincent-karuri Do you want the screen to change and remove the wording, replacing it with the camera button/flash button or do you want it to just appear in the current screen?  I guess if we are changing screens, then what @rowo is asking is valid.

**Comment by vincent-karuri** [comment]
@rowo yes, we can hide the text instructions and add the manual capture after the time expires

**Comment by vincent-karuri** [comment]
Also,  I think it should be a flash light toggle instead

**Comment by rowo** [comment]
@shivenbhatt1 @vincent-karuri Here are some images for discussion

First user tries to get the app to autodetect/read the RDT:
<img src="https://user-images.githubusercontent.com/33488286/66189591-c4084200-e692-11e9-9cec-38d7e2e4ba6f.png" width="333">

Then, if that doesn't work, the instructional text at the top gets replaced to tell you to take a picture. A button appears at the bottom along with a flash toggle. In this case, I've made the camera button really prominent since the app is bringing it up automatically without a user interaction so it has to be clear that's the next step.
 
<img src="https://user-images.githubusercontent.com/1584163/66597881-d3ddc580-eb6d-11e9-8189-2ff5507a167f.png" width="333">

The flash is a toggle:
<img src="https://user-images.githubusercontent.com/1584163/66597892-d9d3a680-eb6d-11e9-95d6-626367b81264.png" width="333">

**Comment by vincent-karuri** [comment]
@rowo this looks good.

Only that the flash toggle icon should not be dependent on the capture time expiring (should always be available/visible).

**Comment by rowo** [comment]
@vincent-karuri Okay, i placed the icon in a consistent place before/after timeout. The information on passing/failing can be placed on top of that dark transparent area where the light button is.

<img src="https://user-images.githubusercontent.com/1584163/66662787-77cf7b80-ec17-11e9-8d67-e0517c153d30.png" width="333">
<img src="https://user-images.githubusercontent.com/1584163/66662788-77cf7b80-ec17-11e9-97f4-45f1e7084c7d.png" width="333">
<img src="https://user-images.githubusercontent.com/1584163/66662786-77cf7b80-ec17-11e9-9ea4-529888d23ef9.png" width="333">

**Comment by vincent-karuri** [comment]
Thanks @rowo

**Comment by vincent-karuri** [comment]
@rowo Please provide the assets for this

**Comment by vincent-karuri** [comment]
@rowo one thing is that the light option should always be present, so it may need to be in a separate view from where the manual capture button appears?

**Comment by rowo** [comment]
@vincent-karuri as discussed, Below is a view of what text on top of that grey (prior to manual capture) might look like. Basically a 1/3 + 2/3 grid. I've also included a check icon, but you can do that with regular text as well. It is #3EBB22 color.

<img src="https://user-images.githubusercontent.com/1584163/67119276-d31fe180-f1b4-11e9-8278-c2d92359baa9.png" width="333">

![check](https://user-images.githubusercontent.com/1584163/67119296-dfa43a00-f1b4-11e9-8cf4-53ae188d81b0.png)

**Comment by vincent-karuri** [comment]
Cool, thanks @rowo
