### ISSUE TITLE
Patient register questions and RDT input by CHW viewable in the UI

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#183]
SID wants to be able to view the patient register information and the RDT taken for the individual on the UI.  This study will be conducted by Ministry of health official health care workers, they may be incorporating it as part of their routine analysis of their patients or request to view the data.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 could you talk to SID and see the level of urgency for this.

And also how it compares to the other issues in the todo in terms of priority.

We may also need to get designs for this flow.

And attach particular issues to a general milestone.

**Comment by vincent-karuri** [comment]
This maybe related to #173

**Comment by vincent-karuri** [comment]
Closed in favor of #173
