### ISSUE TITLE
Flash On/Off for All camera widgets 

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#190]
@rowo @vincent-karuri  We need to add Flash on/off button option to all the image captures (RDT, Carestart expiration date and QR Code). The Clinic setting in Kilifi is relatively dark making it hard to observe barcodes and expiration dates.  This is somewhat related to #178 screen that also needs to be made.

**Comment by rowo** [comment]
@shivenbhatt1 Can this just be the stock camera option but default set to Auto?

**Comment by shivenbhatt1** [comment]
@vincent-karuri maybe you could respond to @rowo 's question

**Comment by vincent-karuri** [comment]
@rowo it can in terms of icons / positioning. But I think the UW implementation uses a different camera from the device default, so we might be forced to overlay our own icons.

**Comment by vincent-karuri** [comment]
Google does not support flash control in their public API.

The barcode widget might just have to remain without flash.

**Comment by rowo** [comment]
I added some screens to https://github.com/onaio/rdt-standard/issues/178#issuecomment-540727576 with a button. There's some explanation in that comment.

![Start-CareStartTimeout-Camera Copy](https://user-images.githubusercontent.com/1584163/66598265-ab0a0000-eb6e-11e9-938b-6a536af014ca.png)
