### ISSUE TITLE
Separate Positive Negative choices for Pf and Pv at end of test

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#191]
Currently there is no separation in the answer choices for CHWs when choosing positive, negative and invalid for the RDT.  We need to break this down into Pf, Pv (positive) and total negative, invalid.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 should this just say `pv` and `pf `as opposed to `pv positive` or `pf positive`

**Comment by shivenbhatt1** [comment]
Just an idea, @rowo let me know where you're at with this and if you agree.

Check the Appropriate Test Results:
- [Check] Pf Positive
- [Check] Pv Positive
- [Check] Negative for Both
- [Check] Invalid Test  

Negative cannot be checked if either are checked positive, Nothing else can be checked if Invalid Test is checked.

Alternatively, we can start with our current screen which has positive, negative and invalid.  If positive is chosen, then the user is allowed to check if Pf and Pv are positive below the positive choice.

**Positive**
- [Check]Pf
- [Check]Pv
**Negative**
**Invalid**

**Comment by rowo** [comment]
@shivenbhatt1 Hey sorry I haven't looked at this until now. I am not sure if I am the right person to have input on this, but the context in https://github.com/onaio/rdt-standard/issues/191#issuecomment-543886524 definitely helped and for the future a screenshot would be useful to include to help me remember what you are talking about.

So seems like the question is whether we do: (1)  a select-multiple field (checkboxes) where two questions are mutually exclusive with any other choice, or (2) a select-one (radios) where selecting positive makes you select-multiple out of two options. A (3) option would be listing out all select-one choices i.e.  Pf and Pv positive, Only Pf Positive, Only Pv Positive, Pf and Pv negative, and Invalid Test. 

To me with no context, I'd say (2) and (3) are more conventional in forms. However, if something like (1) would be understandable by most in this context, then it is the faster option and less error-prone. If we go with (2), if it's most common that both Pf and Pv are positive when positive is chosen, I would have them both auto-checked (as the common scenario) and have the user tap to uncheck one.

**Comment by shivenbhatt1** [comment]
@vincent-karuri Following up on our convo, we decided you'd just create the second version described above in my previous comment.

We can start with our current screen which has positive, negative and invalid. If positive is chosen, then the user is allowed to check if Pf and Pv are positive below the positive choice.

**Positive**
If positive is chosen, the below appear-
[Check]Pf
[Check]Pv
**Negative**
**Invalid**

**Comment by rowo** [comment]
Also it would be a required field that either or both Pf and Pv are checked.

**Comment by shivenbhatt1** [comment]
@rowo I think having a preselection in the Pf or Pv may lead to errors since they represent specific malaria strain positives.  It may be better to leave them unchecked, make sure the user is checking the appropriate response and if they do not check one or both of the items, they see an error.  "Select the positive strain type(s)."

**Comment by rowo** [comment]
@shivenbhatt1 yes that's, fine I agree. I'm just clarifying that selecting one or both boxes after positive is required. The required error message works for me.
