### ISSUE TITLE
Explore timeout CareStart Exp Date Manual Entry

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#207]
After speaking with SID, I'm wondering if we should deploy a timeout manual entry after 10 seconds where the same date bar comes up (only Month and year) so that the health worker can bypass any issues that exist barring certain phones from scanning the carestart package.

**Comment by shivenbhatt1** [comment]
@rowo need a design for this.  Some phones are having difficulty scanning the expiration date on the CareStart package. We want to be able to manually input the date as a timeout.  Ex. if after 10 seconds the date on the package isn't scanned, the next screen comes up  "Record Expiration Date" with a scroll bar (MMM/YYYY)

**Comment by rowo** [comment]
@shivenbhatt1 Is this what you are thinking? Also, I assume the same RDT expired message should appear if it's a date in the past — we would restrict entering an expired date.

<img src="https://user-images.githubusercontent.com/1584163/68576723-a3948a00-047f-11ea-87c6-835332b2996c.png" width="300"> <img src="https://user-images.githubusercontent.com/1584163/68576722-a3948a00-047f-11ea-8ec9-58f1ac3543b8.png" width="300">

**Comment by shivenbhatt1** [comment]
@vincent-karuri Is this okay?

**Comment by vincent-karuri** [comment]
@rowo works for me, thanks

**Comment by vincent-karuri** [comment]
@shivenbhatt1 for uniformity, maybe this should be 15s as well.

It will have day, month and year.

**Comment by vincent-karuri** [comment]
Done.
