### ISSUE TITLE
Monitor app through Firebase

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#218]
Deploy a crash tracking module to the RDT App

**Comment by vincent-karuri** [comment]
@shivenbhatt1 This already exists and is enabled on all production apks

**Comment by pld** [comment]
Looking through the dashboards there's not much data coming through here, so it's unclear if/how well we're tracking.

@vincent-karuri what do you think about upgrading the app analytics to use firebase? https://console.firebase.google.com/u/0/project/onaio-production/overview?pli=1

This will give us usage analytics, not just crash tracking, so we can verify some of the problems we're hearing from SID.

**Comment by vincent-karuri** [comment]
I'm ok with that. Needs to happen anyway with Crashlytics being deprecated.
