### ISSUE TITLE
Add Patient Identification Number to patient registration

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#220]
Below Patient Name add patient id number so that we can sync duplicate entries if needed in low bandwidth settings.

This could also be used for KEMRI if needed.  You would need to ensure that name is not an essential part of the patient registration though since they do not record patient name.

- Have both name and id, make id mandatory, name optional

**Comment by pld** [comment]
are we making this an optional field?

**Comment by shivenbhatt1** [comment]
Can we make both optional, but at the same time, Name OR ID is required?

**Comment by shivenbhatt1** [comment]
Patient Identification Number = Nomor Identifikasi Pasien in Bahasa

**Comment by vincent-karuri** [comment]
Who's judgement is it to use the id in low bandwidth areas?

What happens if they always begin by trying to register the patient (and to sync) on one phone while ignoring the id, and when sync doesn't work, they enter a duplicate entry on the other device, this time recording the patient id. We would essentially lose this relation. 

I think if we add it it should be mandatory. Making it optional is a bit error-prone IMO. 

We can also consider asking them to enter the id in the name field?

**Comment by shivenbhatt1** [comment]
@vincent-karuri These are all valid points.

IDs being used in low bandwidth settings would ensure that the patients stay unique and we can merge them up in the back end. There is an uncertainty to purely using names to do this because of the possibility of multiple individuals with the same name. 

So we only need IDs under this special circumstance when they are running side-by-side in the clinic. It is mandatory for areas where sync is not occurring properly. Could we have it initially deployed as mandatory (ID region) and drop it later once they have finished phase 1 of the study?

I agree they could enter ID in the name field, however, I believe they would like to collect name as well since they are using it for health purposes outside the study.

**Comment by vincent-karuri** [comment]
I'm ok with making it mandatory and keeping the name field as well.

`Who's judgement is it to use the id in low bandwidth areas?` Just to clarify, I was asking whether we should allow the CHWs to make the call on whether to enter an id or not based on the connectivity, which I thought might introduce inconsistencies.

**Comment by shivenbhatt1** [comment]
Agreed, lets make it mandatory for now

**Comment by vincent-karuri** [comment]
Have both name and id, make id mandatory, name optional
