### ISSUE TITLE
Remove questions or add a skip questions toggle

### ISSUE THREAD

**Issue by pld** [onaio/rdt-standard#221]
In the KEMRI meeting we had today they informed us that they cannot collect any of the question based data. The can use the current app and answer NA for all those questions, and that's what they're doing now, but this is slowing down the number of RDTs they can perform.

In order to speed up the rate of RDT data collection, and increase the number of total data points we have, we'd like to cut a version of the app that either
1) adds a button after patient ID is entered to skip all the questions and go straight to the read RDT screen
2) removes all the questions between enter patient ID and the read RDT screen

@shivenbhatt1 @vincent-karuri what are your thoughts on which of the 2 approaches is best and what the LOE is for each, and if there is a difference in LOE?

**Comment by vincent-karuri** [comment]
Each deployment has it's own forms so it might be easier to just remove all the questions.

Leaving the questions there and having the user click a checkbox to skip every time might be a bit bothersome.

On the other hand, the data tables will show a lot of null values for the missing questions for KEMRI. Leaving the questions can allow us to set a default `Not answered` value even when the questions are not visible (after checking a skip questions checkbox).

We also have calculation logic that depends on the fields and I'm not sure if that would break if they're taken out.

I say we can have a `skip questions` checkbox that's checked by default that hides the questions.

They both have similar LOE, not more than half a day

**Comment by shivenbhatt1** [comment]
@vincent-karuri Lets do the skip questions checkbox then
