### ISSUE TITLE
Add missing diagnostic questions when creating a client

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#240]
The following questions are missing when adding a client in the "diagnostic questions" section (V1.20)

Is there a latrine in the patient's home?
Is there running water in the patient's home?
Are the patient's immunization records up to date?
How many children under 5 years old live in the your household?

**Comment by vincent-karuri** [comment]
These questions were only relevant for the Indonesia deployment.

**Comment by vincent-karuri** [comment]
https://docs.google.com/spreadsheets/d/1K7tEA_i70Hwvc60OK_S6y4qKATvs1f1F9bGS3KEmM6A/edit#gid=0

**Comment by vincent-karuri** [comment]
@shivenbhatt1 please confirm

**Comment by shivenbhatt1** [comment]
The boolean data for rows 13-34 are all being collected by Indonesia, but not by KEMRI @vincent-karuri

**Comment by Mstjamush** [comment]
Understood @vincent-karuri
