### ISSUE TITLE
App crashing when a user clicks on some profiles

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#244]
**Crash details**
_Login using indtester1, and click on Whom, 10_

**Crash logs**

02-07 11:44:51.333  8520  8520 D AndroidRuntime: Shutting down VM
02-07 11:44:51.333  8520  8520 E AndroidRuntime: FATAL EXCEPTION: main
02-07 11:44:51.333  8520  8520 E AndroidRuntime: Process: io.ona.rdt, PID: 8520
02-07 11:44:51.333  8520  8520 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at io.ona.rdt.adapter.RDTTestListAdapter.getFormattedTestResults(RDTTestListAdapter.java:110)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at io.ona.rdt.adapter.RDTTestListAdapter.getFormattedRDTTestDetails(RDTTestListAdapter.java:82)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at io.ona.rdt.adapter.RDTTestListAdapter.onBindViewHolder(RDTTestListAdapter.java:57)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at io.ona.rdt.adapter.RDTTestListAdapter.onBindViewHolder(RDTTestListAdapter.java:33)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3336)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.View.measure(View.java:20221)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.support.constraint.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1227)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:1572)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.View.measure(View.java:20221)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.View.measure(View.java:20221)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.support.constraint.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1227)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:1572)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.View.measure(View.java:20221)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.View.measure(View.java:20221)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.View.measure(View.java:20221)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3140)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.View.measure(View.java:20221)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2687)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1640)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1932)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1528)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7530)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:622)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
02-07 11:44:51.333  8520  8520 E AndroidRuntime: 	at android.os.Handler.dispatchMessa
02-07 11:44:51.333  1711  2659 W ActivityManager:   Force finishing activity io.ona.rdt/.activity.PatientProfileActivity
02-07 11:44:51.333  1711  2659 D InputDispatcher: Focused application set to: xxxx

**Comment by vincent-karuri** [comment]
Fixed, although this (rdt test results being null) should never happen unless we have data integrity issues.

**Comment by Mstjamush** [comment]
Fixed
