### ISSUE TITLE
App crashing when a user accesses RDT details where the RDT ID is null

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#245]
**Reproduction steps**

- Login with user indtester1
- Click on Burgandy Standard profile
- Click on RDT ID null

**Crash logs**
02-07 11:51:47.373  8752  8752 D AndroidRuntime: Shutting down VM
02-07 11:51:47.373  8752  8752 E AndroidRuntime: FATAL EXCEPTION: main
02-07 11:51:47.373  8752  8752 E AndroidRuntime: Process: io.ona.rdt, PID: 8752
02-07 11:51:47.373  8752  8752 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at io.ona.rdt.fragment.TestsProfileFragment.populateRDTTestResults(TestsProfileFragment.java:89)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at io.ona.rdt.fragment.TestsProfileFragment.populateRDTTestDetails(TestsProfileFragment.java:77)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at io.ona.rdt.fragment.TestsProfileFragment.onCreateView(TestsProfileFragment.java:59)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
02-07 11:51:47.373  8752  8752 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
02-07 11:51:47.373  1711  4180 W ActivityManager:   Force finishing activity io.ona.rdt/.activity.PatientProfileActivity
02-07 11:51:47.373  1711  4180 D InputDispatcher: Focused application set to: xxxx
02-07 11:51:47.373  1711  4180 D ActivityTrigger: ActivityTrigger activityPauseTrigger

**Comment by vincent-karuri** [comment]
Fixed. Although this should never happen (the rdt id should never be null) unless we have data integrity issues.

**Comment by pld** [comment]
Weird do we know what caused this?

**Comment by vincent-karuri** [comment]
The test associated with a null rdt id is very old (from July 2019) when initial development was beginning. Don't think we had started generating rdt ids from openmrs at the time.

**Comment by pld** [comment]
Cool

**Comment by Mstjamush** [comment]
Fixed
