### ISSUE TITLE
RDT record not showing on Client's profile once created

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#247]
**Description**
When a new RDT record is created, it doesn't show on the Client's profile after saving

**Reproduction steps**
- Login successfully
- Create a RDT record successfully for any client.
- Go to the client profile to check for the RDT record

**Comment by vincent-karuri** [comment]
Fixed!

**Comment by Mstjamush** [comment]
@vincent-karuri this doesn't seem to have been fixed

**Comment by vincent-karuri** [comment]
Sorry, had read the description wrong. Should be fixed now:
https://github.com/onaio/rdt-standard/pull/243/commits/08298d9d93395698fcacac63f951b72ffd6a4436
https://github.com/onaio/rdt-standard/pull/243/commits/7beadd2a85e453f3e9d30bc3cdde5a290bf80eee
