### ISSUE TITLE
Create JSON files and Extract Images for all KE and ID data to date

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#250]
Due to the need to quickly begin assessing data for the Gates Foundation, PLD and myself would like to collate all the data collected so far and begin conducting some early data analysis on results from the study. PLD would like to apply some machine learning techniques to the images+data to extract anything interesting. Our original plan was to wait until data was in canopy discover, however, the timeline for completion prohibits this from happening.

If you could extract all JSON files (KE+ID) + images and drop them in the google file, separating them by country, it would be super helpful.

**Comment by pld** [comment]
Please put the data in Google Drive so we can access it via colab, you can put it in this folder, https://drive.google.com/drive/folders/1-KA3n3ckdjWZYNi86KicIT5eOhPAj-bf?usp=sharing

**Comment by vincent-karuri** [comment]
This is done.

**Comment by pld** [comment]
Is there a script we can re-run to fetch this data again when new data comes in?

**Comment by vincent-karuri** [comment]
There's no single script that does all the different types of extraction.

Sharing a document in the channel that explains most of what is needed.

**Comment by pld** [comment]
https://docs.google.com/document/d/1CraQ5sysXXlXhc0VnSHbeREg_bEEq0DGvAhQXa8f4Nw/edit?usp=sharing
