### ISSUE TITLE
Add Multi-Language Support (MLS)

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#256]
The covid app will need to have MLS which allows definition of form strings in separate property files.

**Comment by pld** [comment]
how is this different from the current RDT app which is in Bahasa?

**Comment by vincent-karuri** [comment]
The current flow is to create a separate form for each language, regardless of the fact that the form structure may be duplicated.

The new MLS feature allows defining a single form that can be shared across locales. Property files can then be defined for each locale containing the language-specific strings.

Also plugs in better into Transifex.
