### ISSUE TITLE
Merge UW changes that support capturing the covid RDT

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#257]
* [ ] Merge [UW's repo](https://github.com/cjpark87/rdt-scan/tree/ona-version) into [rdt capture repo](https://github.com/onaio/rdt-capture/tree/master/lib).
* [ ] Track RDT capture activity response time

**Comment by shivenbhatt1** [comment]
Only Vincent Can do this portion at the moment
