### ISSUE TITLE
Create covid test form

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#259]
* [x] Create the covid test JSON form
* [x] Ensure all test results and images are saved
* [x] Add unit tests

**Comment by vincent-karuri** [comment]
@shivenbhatt1 the format (mockups) will need to be defined for this.

**Comment by shivenbhatt1** [comment]
This is the mockups needed for test choreography. Right now we are supporting two types that we need to create job aid/user flow for

http://www.alltests.com.cn/EN/Prodetail.asp?newsid=1776&cclassid=2&classid=51

https://drive.google.com/open?id=1JRTLcnuQkEQ4m2dBd3qrFbjGKBKymB-0

**Comment by shivenbhatt1** [comment]
Make RDT and Nasal Swab collection conditional, allow end user to skip these collections ahead of the test: Ask the User "Will RDT Analysis be Conducted?", Will Respiratory Sample be Collected?"

**Comment by pld** [comment]
That sounds reasonable as a first draft. @vincent-karuri is that fine to complete as a single flow for a first draft?

---

Maybe we don't have time to do the following, but for longer, do we need to ask the user that? If we split this into 3 flow

1) registration
2) rdt
3) respiratory sample

you always complete registration, and at the end of that form there's a complete rdt and a complete resp sample button, and a complete button on the bottom

then for every registered patient there's a button to add rdt and add resp sample

@shivenbhatt1 after writing this out sounds like we need to chat w/Roger and have mockups for this

**Comment by shivenbhatt1** [comment]
Agreed, actually I told vincent this exact ideal scenario today for future release in our call @pld

**Comment by vincent-karuri** [comment]
It would be easier to have one button for now that saves the registration and immediately launches the test form for that patient.

Both swab and rdt can be collected for now so that the test is linear.

**Comment by pld** [comment]
> It would be easier to have one button for now that saves the registration and immediately launches the test form for that patient.
> 
> Both swab and rdt can be collected for now so that the test is linear.

That sounds good, I guess as long as swab and rdt collection are optional, CC @shivenbhatt1
