### ISSUE TITLE
Build patient register

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#261]
We need a register view for covid patients.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 we may need mockups for this or simply use the existing UI.

**Comment by shivenbhatt1** [comment]
@vincent-karuri For the first version, let's use the existing UI, I'll reach out to Roger to see if we can make improvements anywhere.

**Comment by vincent-karuri** [comment]
Closed by https://github.com/onaio/rdt-standard/pull/274.
