### ISSUE TITLE
Translate and incorporate Specimen Registration form into registration/test forms

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#275]
ZebraX stated that the Specimen Registration form is a requirement from MoH. This form needs to be translated and ensured that we have added missing items into the data dictionary and labeled with location (test or patient form) https://docs.google.com/spreadsheets/d/17oMlrtsRNXnIYsr0Bya3n4YsiA1xWoYsKj05p9nd05o/edit#gid=0

<img width="1190" alt="Screen Shot 2020-05-05 at 7 19 16 AM" src="https://user-images.githubusercontent.com/47836489/81060694-f8e6ac80-8ea0-11ea-8183-bfa41e21277a.png">

**Comment by vincent-karuri** [comment]
Can this be closed?

**Comment by shivenbhatt1** [comment]
keep open, we will have to modify our forms to accommodate this information

**Comment by vincent-karuri** [comment]
I think we can close this @shivenbhatt1?
