### ISSUE TITLE
Most pages in the RDT collection flow have extremely small font sizes making it invisible or hard to read

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#288]
See sample attached screenshots

![Uploading Screenshot_20200515-103352.jpg…]
![Screenshot_20200515-103420](https://user-images.githubusercontent.com/29072646/82024571-a70c0680-9698-11ea-9909-91c4174de97a.jpg)
![Screenshot_20200515-103432](https://user-images.githubusercontent.com/29072646/82024573-a7a49d00-9698-11ea-80b5-59cce0fc0240.jpg)

!
![Screenshot_20200515-103311](https://user-images.githubusercontent.com/29072646/82024561-a4a9ac80-9698-11ea-951b-5a7f9d672961.jpg)
![Screenshot_20200515-103323](https://user-images.githubusercontent.com/29072646/82024564-a5424300-9698-11ea-9d66-f8d0fa2dd9c0.jpg)
![Screenshot_20200515-103339](https://user-images.githubusercontent.com/29072646/82024568-a5dad980-9698-11ea-82eb-e66466eecfbe.jpg)

[Uploading Screenshot_20200515-103211.jpg…]()
ages
![Screenshot_20200515-103159](https://user-images.githubusercontent.com/29072646/82024554-a3787f80-9698-11ea-9fdb-2854e3b479b1.jpg)
![Screenshot_20200515-103148](https://user-images.githubusercontent.com/29072646/82024551-a2475280-9698-11ea-890e-51209df64125.jpg)

![Screenshot_20200515-103133](https://user-images.githubusercontent.com/29072646/82024549-a1162580-9698-11ea-8142-a1558007c8d0.jpg)

**Comment by vincent-karuri** [comment]
Is this a tablet or phone?

**Comment by Mstjamush** [comment]
> Is this a tablet or phone?

Tablet

**Comment by vincent-karuri** [comment]
We can increase font size, but I think this is target towards mobile phones.

**Comment by Mstjamush** [comment]
This is yet to be fixed

**Comment by vincent-karuri** [comment]
> This is yet to be fixed

Is this still on the tablet?

**Comment by Mstjamush** [comment]
Yes. Still on tablet

**Comment by vincent-karuri** [comment]
> Yes. Still on tablet

The app is not targeted for use on tablets. Please verify if this is an issue on mobile phones.

**Comment by vincent-karuri** [comment]
This is not an issue on mobile devices so closing this.
