### ISSUE TITLE
Updates to V1.1.0 requested

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#304]
- [x] The RDT card needs to be removed next to the patient name, it'll cause confusion, and since RDTs are being conducted from the patient profile.
- [x] Update "Support investigation" to "Supporting investigations"
- [x] Change Delivery details to "Sample shipment"

![image](https://user-images.githubusercontent.com/47836489/85431250-456c7100-b54f-11ea-864b-c979a695d2c1.png)

![image](https://user-images.githubusercontent.com/47836489/85431327-646b0300-b54f-11ea-890e-3aabd11c2dfe.png)

- [x] App version is incorrect, this release is not v1.15.0

![image](https://user-images.githubusercontent.com/47836489/85432087-70a39000-b550-11ea-9617-2b73512cc7cd.png)

**Comment by shivenbhatt1** [comment]
This information relates to VTM, it should be Brand of VTM as shown, then VTM expiration date and VTM lot number.

![image](https://user-images.githubusercontent.com/47836489/85459527-3fd35300-b570-11ea-8d5f-71eddaad9469.png)

**Comment by shivenbhatt1** [comment]
The header on Symptoms and history is incorrect, it currently says New client record

![image](https://user-images.githubusercontent.com/47836489/85460887-b9b80c00-b571-11ea-853b-e8aa258321b1.png)

**Comment by shivenbhatt1** [comment]
The back button at the bottom on all the screens does not seem to be working

**Comment by shivenbhatt1** [comment]
The header on the Supporting Investigations screen is incorrect, it currently says Sample collection.

![image](https://user-images.githubusercontent.com/47836489/85461204-11ef0e00-b572-11ea-8ab5-121102627afe.png)

**Comment by shivenbhatt1** [comment]
Are we not placing sample delivery details in the hamburger menu? I think it belongs in both patient profile and hamburger menu, as long as they are linked. You should at least be able to fill out the form from the hamburger menu and see the values recorded in the patient profile

**Comment by shivenbhatt1** [comment]
The sample delivery barcode scanner is not working, not picking up any of the barcodes

**Comment by shivenbhatt1** [comment]
In the RDT section, I'm noting that there are no user flows at the moment, so the barcodes do not link up to any specific user flows. Information is just captured.

**Comment by vincent-karuri** [comment]
> In the RDT section, I'm noting that there are no user flows at the moment, so the barcodes do not link up to any specific user flows. Information is just captured.

Not sure what this means, could you add more detail or screenshots?

**Comment by vincent-karuri** [comment]
> When you scan the sample barcode for delivery, it goes back to main patient profile screen, it should take you to the screen to fill out courier and sender information.

I'm not able to replicate this, are you scanning the same barcode you sent over on slack?

**Comment by vincent-karuri** [comment]
> Are we not placing sample delivery details in the hamburger menu? I think it belongs in both patient profile and hamburger menu, as long as they are linked. You should at least be able to fill out the form from the hamburger menu and see the values recorded in the patient profile
> 
> ![image](https://user-images.githubusercontent.com/47836489/85470473-166cf400-b57d-11ea-983d-ef1072431b58.png)
> ![image](https://user-images.githubusercontent.com/47836489/85470486-1bca3e80-b57d-11ea-87f9-58a56b37eda4.png)

I've added the shipment portion alone since we haven't fully figured out the sender/recipient portion.

**Comment by vincent-karuri** [comment]
> 1. This information relates to VTM, it should be Brand of VTM as shown, then VTM expiration date and VTM lot number.
> 2. The Sample ID/scan barcode box is missing here as well.
> 3. Change GSI sample number to GSI sample ID
> 
> ![image](https://user-images.githubusercontent.com/47836489/85459527-3fd35300-b570-11ea-8d5f-71eddaad9469.png)

Scanning of barcodes happens later on when choosing between manually affixing or scanning and ID.

**Comment by shivenbhatt1** [comment]
@vincent-karuri in the symptom history, "diarrhea" is spelled wrong

**Comment by shivenbhatt1** [comment]
For the contact history boxes, when entering number of patients or close contacts, you can't enter "0". This may be confusing for people to leave it blank.

**Comment by shivenbhatt1** [comment]
Change "Collect respiratory specimen using approved methods" to "Collect sample using appropriate methods". This needs to be changed now that we are offering flexibility in the type of sample collected.

**Comment by shivenbhatt1** [comment]
In the sample collection page, you can enter letters for the doctors phone number, can we restrict this to numbers only?

**Comment by shivenbhatt1** [comment]
In the patient Registration form: patient-registration-form-original.step1.patient_id.v_required.err = Please enter patient ID

This shouldn't be a requirement/error message

**Comment by shivenbhatt1** [comment]
Government ID type should be a choice between Legal ID or Passport, in Bahasa this is "NIK or Paspor"

**Comment by shivenbhatt1** [comment]
For the RDT Form, it isn't parasite type, it is supposed to be "Antibody"

**Comment by shivenbhatt1** [comment]
We need to scan or manually enter sample IDs when they are being shipped - just in case there isn't a barcode attached and they use the autogenerated one that we provided.

**Comment by vincent-karuri** [comment]
> We need to scan or manually enter sample IDs when they are being shipped - just in case there isn't a barcode attached and they use the autogenerated one that we provided.

@shivenbhatt1 this is already happening.

**Comment by vincent-karuri** [comment]
> In the patient Registration form: patient-registration-form-original.step1.patient_id.v_required.err = Please enter patient ID
> 
> This shouldn't be a requirement/error message

We need to pin down what the unique ID for the patient is as discussed before.

This will be useful when searching the patient records using the search field.

If this is not the patient ID, what will it be?

**Comment by vincent-karuri** [comment]
> diarrhea

`Diarrhoea` is an alternate spelling.

**Comment by vincent-karuri** [comment]
> > Are we not placing sample delivery details in the hamburger menu? I think it belongs in both patient profile and hamburger menu, as long as they are linked. You should at least be able to fill out the form from the hamburger menu and see the values recorded in the patient profile
> > ![image](https://user-images.githubusercontent.com/47836489/85470473-166cf400-b57d-11ea-983d-ef1072431b58.png)
> > ![image](https://user-images.githubusercontent.com/47836489/85470486-1bca3e80-b57d-11ea-87f9-58a56b37eda4.png)
> 
> > I've added the shipment portion alone since we haven't fully figured out the sender/recipient portion.
> 
> The sender and the courier should be on there, we can figure out the recipient later, but should have a place holder for the information to display to the health workers so that I can say when it is available, it'll go here in the patient profile. We discussed the recipient possibly being an API integration with the laboratory, but we are waiting until they are live to determine what that integration looks like.

I don't think adding the placeholder there is a good idea - can actually be more confusing if there's an un-clickable option in the menu.

Also, that is not necessary the final location the option will be placed since it's unclear when we will need that option to be visible i.e. it's not clear that it should always be available.

I'd rather leave it out until we can implement it and have more details.
