### ISSUE TITLE
Untranslated pages(In English instead of Bahasa)

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#306]
The following pages are in English instead of Bahasa. Error message for fields that are not provided are in English too(Not captured in the screenshots)
![Screenshot_20200630-174305](https://user-images.githubusercontent.com/29072646/86141972-5727b880-bafb-11ea-9fbb-1b32a1555ddf.jpg)

![Screenshot_20200626-163103](https://user-images.githubusercontent.com/29072646/86141956-53943180-bafb-11ea-8ffa-922d72d90150.jpg)
![Screenshot_20200630-173127](https://user-images.githubusercontent.com/29072646/86141967-55f68b80-bafb-11ea-9179-fe4e10fb2d42.jpg)

**Comment by vincent-karuri** [comment]
Cool, the first screen doesn't seem to have an issue though?

What needs translating there?

**Comment by vincent-karuri** [comment]
@shivenbhatt1 I've added the strings to the `strings.xml`, please assist with the translations.

**Comment by shivenbhatt1** [comment]
@vincent-karuri Could you provide the link? I couldn't seem to find the file that was updated. The string files have already been translated in transifex. Please let me know if this is a new file/updated file that needs translation.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 https://github.com/onaio/rdt-standard/blob/add-covid-forms/rdt-open-reader/src/covidIndonesia/res/values/strings.xml.

**Comment by shivenbhatt1** [comment]
@vincent-karuri Translation is complete and ready on Transifex

**Comment by shivenbhatt1** [comment]
> Cool, the first screen doesn't seem to have an issue though?
> 
> What needs translating there?

There is a mix of bahasa and English on the first screen. It starts with Drivers Licence and the bottom says TERUS. I'm not sure which version @Mstjamush was running, but it would either be NIK and TERUS or Drivers License and CONTINUE.

**Comment by vincent-karuri** [comment]
Driver's License is from a bug that was populating the gender label with the wrong value. Not really about translation. This should be fixed in the next release.
