### ISSUE TITLE
When a user navigates to the back from the Travel & contact exposure page to the Signs & symptoms page, they cannot "Continue" Travel & contact exposure page. The App throws a "Please correct the error(s) in the form to proceed" errors despite all the fields being filled up (Both English and Bahasa)

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#308]
Steps
	1. Login
	2. Pick a client
	3. Select Symptoms and history
	4. Fill in all Pre-existing conditions and click Continue
	5. Fill in all Signs & symptoms and click continue
	6. Click the back soft key to navigate back to the Signs & symptoms page
	7. Confirm that all fields are correct and click Continue

**Comment by vincent-karuri** [comment]
I'm unable to reproduce this.

Was able to go back and continue from the signs and symptoms page.

**Comment by Mstjamush** [comment]
This only happens on a tab
