### ISSUE TITLE
Overiding text on the "Date of onset of symptoms" ~ This happens when a user picks the date

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#309]
![Screenshot_20200630-172736_RDT Open Reader](https://user-images.githubusercontent.com/29072646/86142658-15e3d880-bafc-11ea-8222-103e71e38e47.jpg)

**Comment by vincent-karuri** [comment]
Is the issue here that the text prompts are different?

**Comment by Mstjamush** [comment]
Is the overlapping text bit on the "Date of onset of symptoms" not out of scale?

**Comment by vincent-karuri** [comment]
Yea, the prompt can be removed.
