### ISSUE TITLE
When creating a new patient, after entering general information, remain in patient profile

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#311]
When creating a new patient, after entering the general information and saving, remaining in the main patient profile page for the patient that was just created. Exiting out to the main home mage with the patient list creates confusion for the end-user.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 I'm not able to replicate this when registering a patient.

Could you please outline the steps to reproduce this and perhaps add screenshots for more clarity?

**Comment by vincent-karuri** [comment]
Reading this again, is this a bug or a feature request?

**Comment by shivenbhatt1** [comment]
@vincent-karuri new request since the app has always gone back to main screen. It's just not an ideal process flow.

**Comment by vincent-karuri** [comment]
Ok, that's debatable though. I see how this would be annoying when registering a single patient. But what if you wanted to register many patients at a go then add tests later on? It would in that case be annoying to always exit the patient profile and start a new registration.

Maybe the solution here is to allow either saving then exiting to the patient register or saving then launching the patient profile.

**Comment by shivenbhatt1** [comment]
@vincent-karuri I agree with what you're saying. I forgot to mention in our last convo with IDI, they said that the initial process would be 1 patient - 1 health worker, but there is potential later to move into higher throughput clinics.
