### ISSUE TITLE
GPS Collection update

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#314]
Record GPS collection for any "other" locations across all forms. Ex. Sample collection, if known, the person chooses the hospital that has been identified. If it is other, let them record the name and capture GPS location.

Since no locations have been identified for symptoms and history - collect GPS location with form

**Comment by vincent-karuri** [comment]
@shivenbhatt1 Requesting location information from the GPS module every time we are recording symptoms is quite a burden on the device.

Is there an alternative that we can use to mitigate this?

**Comment by vincent-karuri** [comment]
This could be something like getting the location every 30-60min and using that consistently for all forms we launch within that interval until the next location lookup.

**Comment by vincent-karuri** [comment]
The assumption being that significant movement is unlikely to happen within that time-frame.

**Comment by shivenbhatt1** [comment]
@vincent-karuri We want to ensure that the location of the form submission, for where the patient was seen is recorded. If the suggestion that you propose works, and prior location is recorded and maintained on the new form submission, that would work. As long as we can get coordinates for each patient in a map for where they were initially assessed, where their RDT was done, and where their sample was collected.

**Comment by vincent-karuri** [comment]
It's a heuristic but I think it makes sense. We just need to decide on a time interval within which we can use the same coordinates.

**Comment by vincent-karuri** [comment]
@pld any thoughts on whether this is a valid approximation?

**Comment by pld** [comment]
The approach depends on if this facility or community based, if community it must be every time symptoms are entered, if it's facility this approach will work.

Every time is the safer approach, since we don't know how it will be deployed, I think we should go with that for now.

Does the level of effort differ depending on the approach we take?

**Comment by vincent-karuri** [comment]
The LOE is comparable. This is mainly about conserving device power.
Submissions may run into the hundreds per device and that's it's a huge
drain querying location per submission.

**Comment by pld** [comment]
What do other opensrp client apps do here?

**Comment by vincent-karuri** [comment]
@pld In the case of Reveal, it does have an interval before queries though not as significant as I assumed (~5s).

Turns out battery has not been too much of an issue so we can use a similar approach.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 Other than having GPS widgets, I think we should just inject all forms with coordinates when saving them.

This is regardless of whether `other` was selected or not.

**Comment by pld** [comment]
alright, is this settled then?

**Comment by vincent-karuri** [comment]
Yep, we will request location every time a form is opened.
