### ISSUE TITLE
Remove GSI sample ID from RDT Form

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#316]
RDTs will not be sent to laboratory and no longer need GSI IDs assigned.

We can go ahead and remove it from the RDT form.

**Comment by vincent-karuri** [comment]
Was this issue about removing GSI from the patient registration form?

**Comment by shivenbhatt1** [comment]
@vincent-karuri yes, these numbers will be provided to us in batches that have to be auto-populated on the screen

**Comment by vincent-karuri** [comment]
Cool, the description and title are talking about the RDT test form.

**Comment by shivenbhatt1** [comment]
right, the GSI ID is only valid for the sample, it will not be used for RDTs

**Comment by vincent-karuri** [comment]
The RDT test form never had a GSI ID, that was the patient registration form. So the description and title are wrong I guess.

**Comment by shivenbhatt1** [comment]
@vincent-karuri This still exists in the sample collection form:
![image](https://user-images.githubusercontent.com/47836489/90674461-27f21580-e227-11ea-9d28-5be68c27030a.png)

**Comment by vincent-karuri** [comment]
From the discussion above, wasn't this issue about removing the GSI ID from the patient registration form?

Wasn't there a discussion around entering these IDs manually therefore needing them in the sample collection form?

**Comment by shivenbhatt1** [comment]
@vincent-karuri okay I must have missed that, will reclose for now
