### ISSUE TITLE
Add field validation checks/constraints to the forms to reduce input errors by end-users

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#318]
- [x] Phone numbers should only accept numerical numbers

- [x] email addresses should be in the correct formats

**Comment by shivenbhatt1** [comment]
Add postpartum question only available to female patients >12

**Comment by shivenbhatt1** [comment]
Phone numbers should have 8-13 digit constraint

**Comment by shivenbhatt1** [comment]
- [ ] NIK code is 16 digits, the second 6 digits is the date of birth, DDMMYY, 40 gets added to the DD of the birth number if it is a female to identify male from female

The NIK code is written is PPKKCC-DDMMYY-NNNN
Don't worry about PPKKCC or NNNN

A person who was born on August 17, 1945, will have NIK 317101**170845**0001 (if male) and 317101**570845**0001 (if female), where:

**Comment by vincent-karuri** [comment]
> * [ ]  NIK code is 16 digits, the second 6 digits is the date of birth, DDMMYY, 40 gets added to the DD of the birth number if it is a female to identify male from female
> 
> The NIK code is written is PPKKCC-DDMMYY-NNNN
> Don't worry about PPKKCC or NNNN
> 
> A person who was born on August 17, 1945, will have NIK 317101**170845**0001 (if male) and 317101**570845**0001 (if female), where:

@shivenbhatt1 is validation here simply verifying that the length is 16 digits?

**Comment by shivenbhatt1** [comment]
@vincent-karuri length is 16 digits, and they are numbers only
