### ISSUE TITLE
List patient visits and view the data collected in each visit

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#321]
In patient details page

- [ ] List all the encounters stored for the patient as "Visits" below the patient sorted chronologically with most recent first

When clicking on the visits
- [ ] Open the details for that visit
    - ![image](https://user-images.githubusercontent.com/47836489/89650248-240ddd00-d890-11ea-8b78-2cfa28ed8a10.png)
- [ ] Show individual visit data
    - Group data in individual visit by type OR display as single page or a page per type, whichever is less effort

**Comment by shivenbhatt1** [comment]
![image](https://user-images.githubusercontent.com/47836489/89650248-240ddd00-d890-11ea-8b78-2cfa28ed8a10.png)

**Comment by pld** [comment]
Reassigning to @shivenbhatt1 to get the screen for what shows within a visit and @allan-allay to link to provide a link to the code that already those this in the CHW app.

@shivenbhatt1 can you please review my rewrite of the description of this issue, it was not clear before, I have some questions and things to fill in there.

In that process noticed we can split this into 2 issues, one for the listing of visits one for the viewing of visits, @vincent-karuri does that make sense?

**Comment by vincent-karuri** [comment]
Yea, sounds good.

**Comment by shivenbhatt1** [comment]
![image](https://user-images.githubusercontent.com/47836489/89815230-6cd4c880-db12-11ea-987f-bef73ff47306.png)

**Comment by pld** [comment]
OK I see, I didn't realize this was a multi-level hierarchy. Is there a reason why we decided to have 2 levels vs this page being a scrollable page with headers for the different sections, or maybe accordion expansion?

Because at this level you're already in a visit so each of those final levels will only have 1 thing

**Comment by allan-allay** [comment]
#### Here are a couple of existing medical history related views from CHW 

These are the views I mentioned during the call earlier this week. The code exists in the WCARO and BA flavours. 

----
**medical history multiple visits**
<img src="https://user-images.githubusercontent.com/16164649/89929345-ccfe6400-dc11-11ea-92d3-1505f0b35158.png" width="300">

**medical history sections with details list**
<img src="https://user-images.githubusercontent.com/16164649/89929363-d2f44500-dc11-11ea-83b4-af7f08ee4a76.png" width="300">

**medical history grouped details**
<img src="https://user-images.githubusercontent.com/16164649/89929369-d5ef3580-dc11-11ea-9c7e-b4a55c1c8e0e.png" width="300">


----

**Comment by pld** [comment]
OK so I'm fine with either clicking into each category, or displaying all categories on a single page per visit, e.g. where arrows are clicks

1) clicking in
```
visit 1  -->  symptoms & history --> | symptoms & history
                                     | shortness of breath etc

         -->  RDT                --> | RDT
                                     | IgG True

         -->  ...                --> ...

visit 2  -->  symptoms & history --> | symptoms & history
                                     | fever

         -->  RDT                --> | RDT
                                     | IgM True

         -->  ...                --> ...
...
```
2) single page per visit
```
visit 1  -->  | symptoms & history
              | shortness of breath etc

              | RDT
              | IgG True

              ...

visit 2  -->  | symptoms & history
              | fever

              | RDT
              | IgM True

              ...
...
```


@vincent-karuri please go with whichever one is faster, or the latter if they're the same, if we can reuse anything from elsewhere that's fine, since this is simplified I'm changing it to a small

**Comment by shivenbhatt1** [comment]
@pld I'd say for IgG/IgM show "Positive/Negative" instead of True/False. Make sure values for both IgG and IgM show up for RDTs.

**Comment by pld** [comment]
> @pld I'd say for IgG/IgM show "Positive/Negative" instead of True/False. Make sure values for both IgG and IgM show up for RDTs.

Makes sense, but Is that how the data is stored? I was only providing an example, although to make this simple, for now let's show it as it is stored and show everything, i.e. no rewriting, no filtering

**Comment by shivenbhatt1** [comment]
I believe it is stored True/False

**Comment by pld** [comment]
K let's leave it like that for now, in future we can develop some more user friendly mappings

**Comment by vincent-karuri** [comment]
> I believe it is stored True/False

The actual parasite type selections are stored. So IgG and IgM.

**Comment by vincent-karuri** [comment]
> OK so I'm fine with either clicking into each category, or displaying all categories on a single page per visit, e.g. where arrows are clicks
> 
> 1. clicking in
> 
> ```
> visit 1  -->  symptoms & history --> | symptoms & history
>                                      | shortness of breath etc
> 
>          -->  RDT                --> | RDT
>                                      | IgG True
> 
>          -->  ...                --> ...
> 
> visit 2  -->  symptoms & history --> | symptoms & history
>                                      | fever
> 
>          -->  RDT                --> | RDT
>                                      | IgM True
> 
>          -->  ...                --> ...
> ...
> ```
> 
> 1. single page per visit
> 
> ```
> visit 1  -->  | symptoms & history
>               | shortness of breath etc
> 
>               | RDT
>               | IgG True
> 
>               ...
> 
> visit 2  -->  | symptoms & history
>               | fever
> 
>               | RDT
>               | IgM True
> 
>               ...
> ...
> ```
> 
> @vincent-karuri please go with whichever one is faster, or the latter if they're the same, if we can reuse anything from elsewhere that's fine, since this is simplified I'm changing it to a small

Option 2 is simpler, don't think the indirection in option 1 is necessary.

I also think option 2 is what was initially under consideration when adding the `L` t-shirt size. 

I'd hold off on marking this as `S` since we haven't verified if there is a simple way to reuse anything that has been implemented before. I need to see if the implementation is tightly coupled to the flavors @allan-allay shared. 

In particular, is the code factored out into a library in a configurable way and does it make sense to import an entire library to achieve this bit?

**Comment by pld** [comment]
It's not a library. If it's larger then small break it down further, eg split showing the visits as a separate issue from listing the visits.

**Comment by vincent-karuri** [comment]
I'll look to see if there's anything we can re-use, otherwise, I'll create the individual issues.

**Comment by shivenbhatt1** [comment]
@vincent-karuri to create new issues/split based on the discussion and close this issue

**Comment by pld** [comment]
replaced by other issues
