### ISSUE TITLE
Update sample collection form, sample type

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#322]
Change sample type breakdown

- [x] Swab - breakdown to Naso/oro, then further to VTM information collected as done
- [x] Sputum - Collection tube brand -open field here, add the color of sputum collected post-collection step (Choices: 1)Clear, 2) Off-white, yellow or green, 3) Red or rusty, 4) Gray or black)
- [x] Blood Serum - breakdown to type of blood (capillary or venus) - add quantity collected post-collection step
- [x] Saliva - Collection Kit Brand - open field here

**Comment by vincent-karuri** [comment]
@shivenbhatt1 not clear on what the following mean: 

- `add quantity collected post-collection step`
-  `add the color of sputum collected post-collection`

For the two above, what it the `post-collection` step?

- `then further to VTM information collected as done`

**Comment by shivenbhatt1** [comment]
It would have to come on a subsequent screen after the user is asked to collect a sample according to guidelines. In the form we assume that the end-user still hasn't collected the sample so they wouldn't know the information.

All VTM information can stay the same if Swab is chosen. VTM doesn't show up if swab is not chosen since it is swab specific.

**Comment by vincent-karuri** [comment]
Cool, do we know where the `post-collection` screen goes and what will go into it?

**Comment by shivenbhatt1** [comment]
Plan is to create an additional screen for sputum and blood collection classifications after page that says "Safely store specimen in provided transport tube"
