### ISSUE TITLE
Autofill Names on forms

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#323]
- [ ] Autofil Name of sampler from login details when filling in sample collection form
- [ ] Autofill sender name and if available, sender contact information, on sample shipment form

**Comment by vincent-karuri** [comment]
@shivenbhatt1 atm, sender contact information is not known before launching this form and so cannot be auto-populated.

Also to clarify, name of sampler and name of sender are the same value pulled from the login details, right?

CC @syedowaisali90

**Comment by shivenbhatt1** [comment]
@vincent-karuri @syedowaisali90 That is fine that the sender contact information is unknown at the moment. We should just pull what we have, I believe at this moment we are just using indtester, or beta user until we are up and running. 

Also, you are correct, the name of the sampler and name of the sender is the same value that are pulled from login details.
