### ISSUE TITLE
After sample collection information collection, add collection screen

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#328]
After sample collection information has been completed in the form, add a screen that says:

"Obtain specimen using approved methods."

**Comment by shivenbhatt1** [comment]
Add continue button at the bottom of screen

**Comment by vincent-karuri** [comment]
@shivenbhatt1 a screen already exists that contains similar information (currently step 1).

Step 2 is where we collect the sample information, which I believe you were referring to in: `After sample collection information has been completed in the form ...` in the issue description.

So is this issue about swapping the current step 2 with the current step 1 and modifying the text to read `Obtain specimen using approved methods`?

CC @syedowaisali90

**Comment by vincent-karuri** [comment]
@shivenbhatt1 please add a comment on the decision made about this?

**Comment by shivenbhatt1** [comment]
@vincent-karuri @syedowaisali90 right, lets move that screen after the form has been filled out and adjust content. 

1. Sample collection form
**2. "Obtain specimen using approved methods." <Continue>**
3.  Safely store specimen in provided transport tube. <Continue>
4. Scan specimen barcode/manually affix label
5. Please confirm the information (patient name, Dob)
6. Sample collection has completed...
