### ISSUE TITLE
Add confirmation screen to sample collection event

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#329]
After Sample barcode scan or Manually affix label Sample ID page, have a confirmation screen with checkbox:

- [x] Ensure ID:XXXXXX is recorded on the specimen tube. (Populated from specimen ID in manual process/GSI ID). This checkbox should only be visible if the barcode was scanned manually.
- [x] Record patient Name on specimen tube: Last Name, First Name (Populated from patient profile)
- [x] Record patient date of birth on specimen tube: DD/MM/YYYY (DOB populated here)

These fields are all mandatory (required).

**Comment by vincent-karuri** [comment]
Patient DoB is today's date?

**Comment by shivenbhatt1** [comment]
Edit - incorrect statement. only patients DOB recorded there.

**Comment by shivenbhatt1** [comment]
Combine with Safely store specimens in transport tube, combine with https://github.com/onaio/rdt-standard/issues/331

**Comment by shivenbhatt1** [comment]
Place checkboxes, make confirm button active only if all boxes have been checked off
