### ISSUE TITLE
Add confirmation screen before saving and exiting sample collection form

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#331]
Add a screen that says "Safely store specimens in transport tube".

The screen should come after https://github.com/onaio/rdt-standard/issues/329.

**Comment by shivenbhatt1** [comment]
Comes after the sample tube information confirmation

**Comment by vincent-karuri** [comment]
<img width="317" alt="Screen Shot 2020-08-21 at 10 09 14" src="https://user-images.githubusercontent.com/33488286/90862667-7245d480-e396-11ea-9875-100f1b413f8e.png">
@shivenbhatt1 we already have a similar screen. Should we just modify the text prompt here?

CC @syedowaisali90
