### ISSUE TITLE
Bring up image of RDT from library for user to confirm that they are choosing the correct RDT

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#333]
Place images in assets folder, can modify the location to show images, could consider laying the RDTs out horizontally.

This confirmation screen should show after the user has identified the RDT they will be using in the manual identification process.

**Comment by shivenbhatt1** [comment]
Dependent on #332

**Comment by shivenbhatt1** [comment]
@shivenbhatt1 to add images

**Comment by shivenbhatt1** [comment]
provide pld with JSON file from RDTScan

**Comment by vincent-karuri** [comment]
@shivenbhatt1 is this issue addressing the same thing as https://github.com/onaio/rdt-standard/issues/615?

**Comment by vincent-karuri** [comment]
Closing as redundant
