### ISSUE TITLE
Support batch shipment barcode scanning

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#336]
- [x] Batch sample shipment, speak to Sasa on this. Would need to generate a batch shipment ID for all the samples within the batch. OneScan may be able to operate multiple scans, list should display in app for confirmation/adding/removal. Ensure batch scan isn't enabled all the time, since RDTs don't use it. Possibly check if there is a batch scan available through google or anywhere else. https://github.com/JohnBurrin/Batch-Barcode-Scanner

**Comment by shivenbhatt1** [comment]
- [ ] Need to group the scans into a batch with a unique ID that groups the samples together. Batch ID should be linked to the individual samples

- [ ] Display batch ID at the end of sample shipment, notify the sender to place ID label onto batch shipment package

**Comment by shivenbhatt1** [comment]
Need to break this issue up into a research issue first for batch scan using https://github.com/JohnBurrin/Batch-Barcode-Scanner

**Comment by vincent-karuri** [comment]
@shivenbhatt1 also seems like there's a few things going on here:

1. Activating batch scan
2. Group scans as a single batch
3. Displaying a list where you can remove or add scans (seems a bit complex)
4. Add opt-in for the batch scanning
5. Display batch ID at the end of sample shipment, notify the sender to place ID label onto batch shipment package

with 3. being a big unknown.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 do we need to consider batch scanning for v1.6?

**Comment by vincent-karuri** [comment]
@shivenbhatt1 what is the flow for batch scanning? Do we have mockups we should be looking at?

@syedowaisali90 note that this will need the latest version of the OneScan apk installed on the phone.

**Comment by shivenbhatt1** [comment]
**Background:** The current state at which single sample laboratory shipments are sent doesn't work for the end-users. It becomes too tedious for "senders" to scan one sample and submit shipment form when they often have multiple samples they are sending at once. After discussion we came up with a batch scan mode where senders can send anywhere from 1 to XXXX samples on a single sample shipment form. These samples would then be grouped by a uniquely generated batch ID.
**What is needed:**
1. The current page allows you to enter 1 sample. We would need to be able to enter OR scan multiple samples using an add button. Once the first sample is entered/scanned using OneScan, there should be an add sample button below the previous sample to add additional sample rows. The sender should also be able to "Remove"/"Delete" samples. In the ID columns we can use a barcode Icon to launch OneScan followed by an open space for the ID to be manually entered, followed by a trashcan symbol. We can place an "Add" button before the trashcan symbol if we want users to confirm entries on the form.
2. The form should ensure that samples aren't scanned more than once. This can be done at the time of scan OR removed from the list if scanned twice. It would also be nice to cross reference the database to ensure that samples belong to patients and flag any IDs that don't exist via forms that were previously submitted for patient sample collections.
3. Once all scans are done on the sample shipment page, a secondary page displays all scanned samples. The order of the page should be header:"Batch ID:XXXX" followed by a list of scanned/entered barcode IDs. The sender should be given an option go back and "Edit batch" list at bottom of the list OR "Submit shipment"
4. The batch ID should be generated via OpenMRS or elsewhere, and be unique

**Comment by vincent-karuri** [comment]
@shivenbhatt1 as per the discussion https://github.com/onaio/rdt-standard/issues/341#issuecomment-686952763 editing and deleting are complex actions that are not straightforward to implement within native forms. I thought the decision was to skip this?

I'm not sure I understand the `add sample row` UI. I thought we would leverage what Sasa built out to simulate batch scanning and have the entire result saved to OpenSRP once the user closes out of the scan screen?

For 2, again, this would involve some state management to flag scanned barcodes or to cross-reference with existing patients. I would rather leave the duplicate handling to a backend process since this looks more like an edge case and I don't see a detrimental effect to having the duplicates atm. Thoughts?

For 3, we can display the batch ID but displaying each of the scanned entries may be less ideal.

The caveat here is that some of this functionality is more easily done within the `OneScanActivity` as opposed to native forms i.e. the edit, delete and listing of scans. I'd however prefer to have a scaled down version first and then work towards improvements later.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 

So to summarise I propose that we should initially support:

1. Scanning multiple barcodes in one submission leveraging OneScan's support for batch scan
1. Grouping and assignment of a batch ID to the scanned barcodes
1. Displaying of the batch ID

and move the more advanced features e.g. edit, delete and viewing of scans to a separate issue which we can iterate on.

**Comment by vincent-karuri** [comment]
```
package com.example.intentapitest.OnaMockApp;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.media.AudioManager;
import android.media.MediaPlayer;
import android.os.Bundle;

import com.google.android.material.floatingactionbutton.FloatingActionButton;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import android.os.Handler;
import android.text.Editable;
import android.text.method.ScrollingMovementMethod;
import android.util.Log;
import android.view.Gravity;
import android.view.SoundEffectConstants;
import android.view.View;
import android.widget.EditText;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.TextView;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {

    private static final String TAG = "MainActivity";

    private OneScanService mOneScanService;

    private EditText mResultView;

    private AudioManager mAudioManager;
    private MediaPlayer mMediaPlayer;

    private int mCounter;

    private String mReader = "camera";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        mAudioManager = (AudioManager) this.getSystemService(Context.AUDIO_SERVICE);
        mMediaPlayer = MediaPlayer.create(this, R.raw.plucky);

        mOneScanService = new OneScanService(this);

        mResultView = findViewById(R.id.textViewResult);
        mResultView.setMovementMethod(new ScrollingMovementMethod());

        mCounter = 0;

        RadioGroup radioGroup = findViewById(R.id.rg_reader);
        radioGroup.setOnCheckedChangeListener(new RadioGroup.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(RadioGroup group, int checkedId) {
                if (checkedId == R.id.rb_camera) {
                    mReader = "camera";
                } else if (checkedId == R.id.rb_scanner) {
                    mReader = "scanner";
                } else if (checkedId == R.id.rb_bluetooth) {
                    mReader = "bluetooth";
                } else {
                    mReader = "camera";
                }
            }
        });

        FloatingActionButton cameraButton = findViewById(R.id.fabCamera);
        cameraButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mCounter = 0;
                mResultView.setText("");
                doScan(mReader, false);
            }
        });

        FloatingActionButton batchButton = findViewById(R.id.fabLaser);
        batchButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mCounter = 0;
                mResultView.setText("");
                doScan(mReader, true);
            }
        });

        TextView versionView = findViewById(R.id.text_version);
        OneScanService.VersionRequest request = new OneScanService.VersionRequest();
        mOneScanService.send(request, (resultCode, bundle) -> {
            if (resultCode == Activity.RESULT_OK) {
                OneScanService.VersionResponse response = new OneScanService.VersionResponse(bundle);
                versionView.setText(String.format("OneScan Demo version: %s\nOneScan version: %s", BuildConfig.VERSION_NAME, response.version));
            } else {
                versionView.setText(String.format("OneScan Demo version: %s\nOneScan Version: (Error) OneScan not installed", BuildConfig.VERSION_NAME));
            }
        });

    }

    final Handler handler = new Handler();

    void doScan(String reader, boolean batchScan) {
        OneScanService.ScanRequest request = new OneScanService.ScanRequest();
        request.reader = reader;
        request.title = "Ona App";
        request.clientId = Security.CLIENT_ID;
        request.token = Security.TOKEN;
        request.appName = "Ona Mock";
        request.appVersion = BuildConfig.VERSION_NAME;
        request.appUserName = "sasa.mrvos@gmail.com";
        mOneScanService.send(request, (resultCode, bundle) -> {
            if (resultCode == Activity.RESULT_OK) {
                OneScanService.ScanResponse response = new OneScanService.ScanResponse(bundle);
                String text = String.format("Barcode Text:\n\"%s\"" +
                                "\nProduct ID: %s\nSerial No: %s\nAdditional ID: %s\n" +
                                "Lot: %s\nExpiration Date: %s\n",
                        response.barcodeText,
                        response.productId,
                        response.serialNumber,
                        response.additionalIdentifier,
                        response.lot,
                        response.expirationDate);

                if (response.sensorType == 1) {
                    text += String.format("Sensor triggered: %s\n\n",
                            response.sensorTriggered ? "yes" : "no");
                } else if (response.sensorType == 2) {
                    text += String.format("Sensor triggered: %s\nReflectance: %f\nRemaining Life: %f days\nRemaining Life: %f%%\n\n",
                            response.sensorTriggered ? "yes" : "no",
                            response.sensorReflectance,
                            response.remainingLife,
                            response.remainingPercentage);

                } else {

                }

                mMediaPlayer.start();

                if (batchScan) {
                    mCounter++;

                    text = String.format("Scan #%d\n", mCounter) + text;
                    Toast toast = Toast.makeText(getApplicationContext(), text, Toast.LENGTH_SHORT);
                    toast.setGravity(Gravity.BOTTOM | Gravity.CENTER_HORIZONTAL, 0, -100);
                    toast.getView().setBackgroundColor(0x50FFFFFF);
                    toast.show();

                    mResultView.append(text);

                    handler.postDelayed(new Runnable() {
                        @Override
                        public void run() {
                            doScan(reader, true);
                        }
                    }, 1);
                } else {
                    mResultView.setText(text);
                }
            }
        });
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        mOneScanService.doActivityResult(requestCode, resultCode, data);
    }

}
```

**Comment by vincent-karuri** [comment]
- [ ] Support batch scan as shown in the sample code above
- [ ] Keep track of (save) all scans in a global variable (most suitably a JSONArray) 
- [ ] OnFinish, pass saved scans as a result to the calling `OneScanCovidRDTBarcodeFactory`
- [ ] The scans should be saved as part of the `value` field of the `OneScanCovidRDTBarcodeFactory` widget
- [ ] Additionally, attach a unique batch id to the `OneScanCovidRDTBarcodeFactory` widget `value` field
- [ ] The unique batch id should be derived from the existing unique id retrieval method for RDTs and samples

e.g.

```
{
  "batch_id": "unique_batch_id",
  "scans": [
      {
          "productId": "product_id",
          "serialNumber": "serial_no",
          "additionalIdentifier": "additional_id",
          "lot": "lot_no",
          "expirationDate": "exp_date"
      },
      {...},
      {...}
  ]
}
```

@syedowaisali90

**Comment by vincent-karuri** [comment]
@shivenbhatt1 to confirm, the page displaying the batch ID will come at the very end, right? 

Also, do we need a design for a button the user can click to indicate they're done scanning?

CC @syedowaisali90

**Comment by shivenbhatt1** [comment]
@vincent-karuri That is correct, displaying the batch ID at the very end.

Can we create a preliminary button for "Scan Complete" because I sense that this will be blocked for a period of time otherwise if we require design?

**Comment by vincent-karuri** [comment]
Sounds good

**Comment by vincent-karuri** [comment]
@shivenbhatt1 fyi, this is what is going into the feature atm https://github.com/onaio/rdt-standard/issues/336#issuecomment-701416206

**Comment by shivenbhatt1** [comment]
@vincent-karuri that looks good

**Comment by vincent-karuri** [comment]
@shivenbhatt1 how do we want to handle samples whose sensor is triggered in batch scan? The flow will be more complicated if we want to flag them and still continue scanning more samples.

**Comment by shivenbhatt1** [comment]
@vincent-karuri samples do not have temperature sensors, only RDTs do. Since RDTs are not part of the sample shipment process, there is no need to worry about sensors being triggered.

**Comment by vincent-karuri** [comment]
Great. @syedowaisali90 you can remove all fields that assumed single sample barcode scanning.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 should we still keep the barcode details page for batch scan? Right now it's just suited to display details for a single sample.

**Comment by shivenbhatt1** [comment]
@vincent-karuri We can drop the details page when batch scanning.

**Comment by vincent-karuri** [comment]
cool, CC @syedowaisali90.
