### ISSUE TITLE
Enable OneScan Scan engine for non-camera based barcode scanners

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#337]
Zebra requested that we enable "scanning engine" for barcode scanners (non-camera based). They said this feature won't change existing functionality in our app for mobile phones. They are providing Anu with some TC52s (Zebra barcode scanning mobile phones) to test with various end-users, and can only work with this feature enabled.

**Comment by shivenbhatt1** [comment]
Enable "scanner" for reader ScanRequest Public fields, allows both type

**Comment by vincent-karuri** [comment]
Update https://github.com/onaio/rdt-standard/blob/c0c80733a9f7a0975ffe1270f9cb1b772c43e5c8/rdt-open-reader/src/covidIndonesia/java/io/ona/rdt/activity/OneScanActivity.java#L31 to `"scanner"`.

**Comment by vincent-karuri** [comment]
@syedowaisali90 it should probably be a constant as well.
