### ISSUE TITLE
Barcode Results screen - Need design input

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#341]
Need a design for the results screen from the OneScan barcode scanner

- [ ] The outputs for RDT barcode scan should be:
Temperature Sensor Result with graphic of Okay to Use/Not Okay to use - or some similar wording based on if the RDT has been exposed to excessive heat and possibly degraded
Unique RDT ID: XXXXXX
GTIN of manufacturer: XXXXXXXXXXX
Lot Number of manufacturing: XXXXXX
Expiration Date: DD/MM/YYYY

- [ ] Another Screen for Scanning Sample Barcodes during Sample Collection:
Unique Sample ID: XXXXX-X

- [ ] Another Screen for scanning barcodes during sample shipment (data has to be identifiable in single scans) in multiple/batch scan, for now, we can just display this all the time:
Unique Sample ID: XXXXX-X
Need buttons at bottom that allows user to scan another sample barcode/Add another barcode or Sample Scan complete.

- [ ] Screen that shows aggregate barcodes under the batch that is being shipped out and a confirmation at the bottom. We need to rework the existing sender screen to add this portion in.
*For reference the sample shipment sender will be using this form to send shipments of patient samples to the laboratory and we are working towards batch scanning wherein all samples scanned in this area will be shipped together in one box with a unique batch ID generated by OpenMRS. Each scan should have some type of acknowledgment that a barcode was scanned, then OpenSRP will have a screen which displays all the scans the barcodes that were scanned under the batch ID. Currently the sender screen has Sender name, sender phone number, sender email, courier name, courier phone number and courier ID. These scans should probably be placed below that. We should also be able to add/delete scans somehow here.

[Scanning Engine - TC52 Demo 1.MP4.zip](https://github.com/onaio/rdt-standard/files/4966440/Scanning.Engine.-.TC52.Demo.1.MP4.zip)

**Comment by shivenbhatt1** [comment]
![image](https://user-images.githubusercontent.com/47836489/90024555-fdcab180-dc82-11ea-91be-fb06dc8a9725.png)
![image](https://user-images.githubusercontent.com/47836489/90024584-04f1bf80-dc83-11ea-8095-25fa649614cc.png)

**Comment by shivenbhatt1** [comment]
Fragment_Results that Sasa shared with us

`<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.NestedScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fillViewport="true">

    <android.support.constraint.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <TextView
            android:id="@+id/product_name"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginTop="16dp"
            android:layout_marginEnd="16dp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            tools:text="product name if known" />

        <ImageView
            android:id="@+id/barcode_valid_image"
            android:layout_width="72dp"
            android:layout_height="72dp"
            android:layout_marginStart="16dp"
            android:layout_marginLeft="16dp"
            android:layout_marginTop="16dp"
            android:contentDescription="@string/barcode_valid_image"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/product_name"
            app:srcCompat="@android:drawable/btn_dialog" />

        <TextView
            android:id="@+id/result_message"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginTop="16dp"
            android:layout_marginEnd="16dp"
            android:layout_marginRight="16dp"
            android:gravity="center_vertical"
            android:minHeight="72dp"
            android:textColor="@android:color/holo_green_light"
            android:textSize="28sp"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintStart_toEndOf="@+id/barcode_valid_image"
            app:layout_constraintTop_toBottomOf="@+id/product_name"
            tools:text="scanned_status" />

        <TextView
            android:id="@+id/additional_error_message"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="8dp"
            android:layout_marginLeft="8dp"
            android:layout_marginTop="16dp"
            android:layout_marginEnd="8dp"
            android:layout_marginRight="8dp"
            android:gravity="center"
            android:minHeight="72dp"
            android:textColor="@color/red"
            android:textSize="36sp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/result_message"
            tools:text="DO NOT USE" />

        <TextView
            android:id="@+id/remaining_life"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginLeft="16dp"
            android:layout_marginTop="16dp"
            android:layout_marginBottom="16dp"
            android:text="@string/remaining_life_label"
            android:textColor="@color/result_text_color_label"
            app:layout_constraintBottom_toTopOf="@id/remaining_percentage_label"
            app:layout_constraintEnd_toStartOf="@id/remaining_life_result"
            app:layout_constraintHorizontal_chainStyle="spread_inside"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/additional_error_message" />

        <TextView
            android:id="@+id/remaining_life_result"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginEnd="16dp"
            android:layout_marginRight="16dp"
            android:gravity="start"
            app:layout_constraintBottom_toTopOf="@id/remaining_percentage_label"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toEndOf="@id/remaining_life"
            app:layout_constraintTop_toBottomOf="@id/additional_error_message"
            tools:text="7.0" />

        <TextView
            android:id="@+id/remaining_percentage_label"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginLeft="16dp"
            android:layout_marginBottom="16dp"
            android:text="@string/remaining_percentage_label"
            android:textColor="@color/result_text_color_label"
            app:layout_constraintBottom_toTopOf="@id/reflection_label"
            app:layout_constraintEnd_toStartOf="@id/remaining_percentage_result"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/remaining_life" />

        <TextView
            android:id="@+id/remaining_percentage_result"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginEnd="16dp"
            android:layout_marginRight="16dp"
            android:gravity="start"
            app:layout_constraintBottom_toTopOf="@id/reflection_label"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toEndOf="@id/remaining_percentage_label"
            app:layout_constraintTop_toBottomOf="@id/remaining_life"
            tools:text="100%" />

        <TextView
            android:id="@+id/reflection_label"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginLeft="16dp"
            android:layout_marginBottom="16dp"
            android:text="@string/reflectance_label"
            android:textColor="@color/result_text_color_label"
            app:layout_constraintBottom_toTopOf="@id/gtin_label"
            app:layout_constraintEnd_toStartOf="@id/reflection_result"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/remaining_percentage_label" />

        <TextView
            android:id="@+id/reflection_result"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginEnd="16dp"
            android:layout_marginRight="16dp"
            app:layout_constraintBottom_toTopOf="@id/gtin_label"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toEndOf="@id/reflection_label"
            app:layout_constraintTop_toBottomOf="@id/remaining_percentage_label"
            tools:text="51.25" />

        <TextView
            android:id="@+id/gtin_label"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginLeft="16dp"
            android:layout_marginBottom="16dp"
            android:text="@string/gtin_label"
            android:textColor="@color/result_text_color_label"
            app:layout_constraintBottom_toTopOf="@+id/batch_number_label"
            app:layout_constraintEnd_toStartOf="@+id/gtin_value"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/reflection_label"
            tools:textColor="@color/result_text_color_label" />

        <TextView
            android:id="@+id/gtin_value"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginEnd="16dp"
            android:layout_marginRight="16dp"
            app:layout_constraintBaseline_toBaselineOf="@+id/gtin_label"
            app:layout_constraintBottom_toTopOf="@+id/batch_number_label"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toEndOf="@+id/gtin_label"
            app:layout_constraintTop_toBottomOf="@id/reflection_label"
            tools:text="10123451234512" />

        <TextView
            android:id="@+id/batch_number_label"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginLeft="16dp"
            android:layout_marginBottom="16dp"
            android:text="@string/batch_number_label"
            android:textColor="@color/result_text_color_label"
            app:layout_constraintBottom_toTopOf="@+id/expiration_date_label"
            app:layout_constraintEnd_toStartOf="@id/batch_number_value"
            app:layout_constraintHorizontal_chainStyle="spread_inside"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/gtin_label" />

        <TextView
            android:id="@+id/batch_number_value"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginEnd="16dp"
            android:layout_marginRight="16dp"
            app:layout_constraintBottom_toTopOf="@+id/expiration_date_label"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toEndOf="@+id/batch_number_label"
            app:layout_constraintTop_toBottomOf="@id/gtin_label"
            tools:text="16R00150" />

        <TextView
            android:id="@+id/expiration_date_label"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginLeft="16dp"
            android:layout_marginBottom="16dp"
            android:text="@string/expiration_date_label"
            android:textColor="@color/result_text_color_label"
            app:layout_constraintBottom_toTopOf="@+id/serial_number_label"
            app:layout_constraintEnd_toStartOf="@id/expiration_date_value"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/batch_number_label" />

        <TextView
            android:id="@+id/expiration_date_value"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginEnd="16dp"
            app:layout_constraintBottom_toTopOf="@+id/serial_number_label"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toEndOf="@+id/expiration_date_label"
            app:layout_constraintTop_toBottomOf="@id/batch_number_label"
            tools:text="2019-12-31" />

        <TextView
            android:id="@+id/serial_number_label"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginLeft="16dp"
            android:layout_marginBottom="16dp"
            android:text="@string/serial_number_label"
            android:textColor="@color/result_text_color_label"
            app:layout_constraintBottom_toBottomOf="@+id/statistics"
            app:layout_constraintEnd_toStartOf="@id/serial_number_value"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@id/expiration_date_label" />

        <TextView
            android:id="@+id/serial_number_value"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginEnd="16dp"
            android:layout_marginRight="16dp"
            app:layout_constraintBaseline_toBaselineOf="@id/serial_number_label"
            app:layout_constraintBottom_toTopOf="@+id/statistics"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toEndOf="@+id/serial_number_label"
            app:layout_constraintTop_toBottomOf="@id/expiration_date_label"
            tools:text="4001235" />

        <TextView
            android:id="@+id/statistics"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginLeft="16dp"
            android:layout_marginEnd="16dp"
            android:layout_marginRight="16dp"
            android:minHeight="72dp"
            android:textSize="16sp"
            android:visibility="invisible"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            tools:text="statistics" />
    </android.support.constraint.ConstraintLayout>
</android.support.v4.widget.NestedScrollView>`

**Comment by shivenbhatt1** [comment]
Activity Results that Sasa shared with us:
`<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/main_content"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context=".ResultsActivity">

    <android.support.design.widget.AppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:paddingTop="@dimen/appbar_padding_top"
        android:theme="@style/AppTheme.AppBarOverlay">

        <android.support.v7.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="?attr/colorPrimary"
            app:layout_scrollFlags="snap"
            app:popupTheme="@style/AppTheme.PopupOverlay"
            app:title="@string/app_name">

        </android.support.v7.widget.Toolbar>

        <android.support.design.widget.TabLayout
            android:id="@+id/tabs"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>

    </android.support.design.widget.AppBarLayout>

    <android.support.v4.view.ViewPager
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:paddingBottom="48dp"
        app:layout_behavior="@string/appbar_scrolling_view_behavior" />

    <Button
        android:id="@+id/button_scan_again"
        android:layout_width="match_parent"
        android:layout_height="48dp"
        android:background="@drawable/button_selector"
        android:text="@string/scan_again"
        android:textColor="@android:color/white"
        android:layout_gravity="bottom"
        tools:text="Call To Action" />

</android.support.design.widget.CoordinatorLayout>`

**Comment by shivenbhatt1** [comment]
@rowo Need to create screens here

**Comment by shivenbhatt1** [comment]
Current layout: 
![image](https://user-images.githubusercontent.com/47836489/91310786-4ce30d00-e780-11ea-9c16-ce0f1d91f1da.png)

**Comment by shivenbhatt1** [comment]
This is more in line with what we want to build
![image](https://user-images.githubusercontent.com/47836489/91325257-f7632c00-e790-11ea-97a9-bd52bee923c4.png)
![image](https://user-images.githubusercontent.com/47836489/91325293-ffbb6700-e790-11ea-9596-f6a94b12b4c2.png)

**Comment by rowo** [comment]
Comes right after the image capture (not just barcode). Next step button is continue to the collecting blood.

**Comment by shivenbhatt1** [comment]
To continue blood collection for RDT/Sample we need some kind of acknowledgment button line "Continue"

**Comment by vincent-karuri** [comment]
```
Screen that shows aggregate barcodes under the batch that is being shipped out and a confirmation at the bottom. We need to rework the existing sender screen to add this portion in.
*For reference the sample shipment sender will be using this form to send shipments of patient samples to the laboratory and we are working towards batch scanning wherein all samples scanned in this area will be shipped together in one box with a unique batch ID generated by OpenMRS. Each scan should have some type of acknowledgment that a barcode was scanned, then OpenSRP will have a screen which displays all the scans the barcodes that were scanned under the batch ID. Currently the sender screen has Sender name, sender phone number, sender email, courier name, courier phone number and courier ID. These scans should probably be placed below that. We should also be able to add/delete scans somehow here.
```

State management needed in adding, deleting and displaying the list of scanned barcodes is not well-served by native forms.

If this is not absolutely necessary, I'd skip this portion. If it is, this would need scoping.

**Comment by shivenbhatt1** [comment]
The concern is mostly duplicate entries that need to be resolved for batch scanning. We will move forward without worrying about editing and deleting sample ID/barcodes from the list right now.

**Comment by rowo** [comment]
@shivenbhatt1 Added some images https://marvelapp.com/prototype/c6gb48h/screen/72606487 and https://marvelapp.com/prototype/c6gb48h/screen/72606488, but not sure if it fulfills what you're talking about. What do you think?

**Comment by shivenbhatt1** [comment]
Going to go with the first 7 items on the list @vincent-karuri

**Comment by shivenbhatt1** [comment]
Create issue for the work

**Comment by vincent-karuri** [comment]
> @shivenbhatt1 Added some images https://marvelapp.com/prototype/c6gb48h/screen/72606487 and https://marvelapp.com/prototype/c6gb48h/screen/72606488, but not sure if it fulfills what you're talking about. What do you think?

@rowo for consistency, should the continue button at the bottom of the screen be filled instead of outlined like in the other form steps?

**Comment by rowo** [comment]
@vincent-karuri yes sounds good — please stay consistent where you see fit. Sorry, jumping in and out, I forget where things are at.
