### ISSUE TITLE
Untraslated pages or text 

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#345]
a) Error message when some mandatory fields are not provided
	b) Symptoms page (last page) - the HintText is in English*
	c) When recording RDT test - the RDT page
	d) Referral
![20200803_145857](https://user-images.githubusercontent.com/29072646/89184144-034c3b80-d5a1-11ea-852d-4e440a04bafa.jpg)
![Screenshot_20200803-145325_RDT Open Reader](https://user-images.githubusercontent.com/29072646/89184161-07785900-d5a1-11ea-8ed3-9ef90619df17.jpg)
![Screenshot_20200803-145429_RDT Open Reader](https://user-images.githubusercontent.com/29072646/89184164-0810ef80-d5a1-11ea-9ffd-1877e96f27fc.jpg)
![Screenshot_20200803-145623_RDT Open Reader](https://user-images.githubusercontent.com/29072646/89184168-09421c80-d5a1-11ea-97c9-ed11ea78234c.jpg)
![Screenshot_20200803-145716_RDT Open Reader](https://user-images.githubusercontent.com/29072646/89184170-09421c80-d5a1-11ea-8c29-6fd4dc18cf9e.jpg)
![Screenshot_20200803-145845_RDT Open Reader](https://user-images.githubusercontent.com/29072646/89184172-09dab300-d5a1-11ea-8294-8fa4f2834a2d.jpg)
![Screenshot_20200803-150018_RDT Open Reader](https://user-images.githubusercontent.com/29072646/89184173-0a734980-d5a1-11ea-8c22-aff0feabc180.jpg)
![Screenshot_20200803-150058_RDT Open Reader](https://user-images.githubusercontent.com/29072646/89184176-0b0be000-d5a1-11ea-8574-1f8610e37aa9.jpg)
![Screenshot_20200803-150138_RDT Open Reader](https://user-images.githubusercontent.com/29072646/89184178-0b0be000-d5a1-11ea-9ace-8de3136ef7be.jpg)

 Healthy facility page when recording an RDT test
	e) RDT type page -  When choosing whether to Scan barcode or Enter RDT manually
	f) RDT open Reader page 
	g) One the "Enter RDT Manually" page
	h) The gender field on a Client's profile is in English (Male/Female)

**Comment by vincent-karuri** [comment]
@Mstjamush is this resolved?
