### ISSUE TITLE
Extract team location to autopopulate hospitals in surrounding area for sample collection

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#349]
- [ ] Prepopulate names based on user location if available, make it an editable field

- Pulldown menus are preferred, however, prepopulated field is suffice
- Pulldown menus are done in Reveal
- Another thing we can explore is a hierarchical view, like reveal, locations and publications. If the doctors generally move around those health facilities, we can set these in the dropdown and repopulate them dynamically.
- Easier to repopulate it with team locations though which are stored in OpenMRS and locations can be tracked down by GPS

**Comment by vincent-karuri** [comment]
@shivenbhatt1 can we add this to v1.6 milestone?

**Comment by vincent-karuri** [comment]
@shivenbhatt1 where does the dropdown or text filed go? i.e. to which screen / form

**Comment by vincent-karuri** [comment]
@syedowaisali90 we should retrieve the immediate parent location (in the location hierarchy) that the logged in user is assigned to and display all child locations under it. 

e.g. if the user is assigned to `Division 1` in the location hierarchy, they should see two options i.e. `Division 1` and `Division 2` which are both child locations of the immediate parent location i.e. `District`.

- Country (parent location)
    - District (parent location)
        - Division 1 (child location)
        - Division 2 (child location)

**Comment by shivenbhatt1** [comment]
This should exist in the following locations:
Symptom and history form -->Name of facility
RDT Form --> Name of facility
Sample collection form -->Name of health facility

**Comment by syedowaisali90** [comment]
@shivenbhatt1 In the `sample collection form` we already have `native radio` options in the `name of health facility section` so, will I need to show a dropdown menu when a user selects `other` options from the menu.

**Comment by shivenbhatt1** [comment]
@syedowaisali90 right, we are planning to move away from that since right now we are limited to the 3 locations + other manual entry. The three in place right now are the 3 main hospitals in Jakarta, however, we may be operating outside of these locations.

**Comment by vincent-karuri** [comment]
So basically replace what is there with the dropdown?

**Comment by shivenbhatt1** [comment]
yes

**Comment by vincent-karuri** [comment]
NB: looks like the default location sync only syncs a portion of the location tree and not the entire location tree associated with the logged-in user.

In this case, we'll need to enable sync of the parent location tree (in reference to https://github.com/onaio/rdt-standard/issues/349#issuecomment-700727776) to allow retrieval of its child locations.

[SyncAllLocationsServiceJob](https://github.com/OpenSRP/opensrp-client-core/blob/master/opensrp-app/src/main/java/org/smartregister/job/SyncAllLocationsServiceJob.java) is the sync process that needs to be enabled and slightly modified to allow syncing based on location id. The locations can then be retrieved from the [LocationRepository](https://github.com/OpenSRP/opensrp-client-core/blob/master/opensrp-app/src/main/java/org/smartregister/repository/LocationRepository.java).
