### ISSUE TITLE
Bug in sample barcode scanning - sample is showing as expired.

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#359]
The sample barcode scanned is coming up expired.  "Sample is expired!" "Please collect another sample."

This shouldn't be the case since there is no date assigned in the barcode. You are only collecting the assigned barcode ID

**Comment by vincent-karuri** [comment]
I was able to successfully capture the barcode.

The widget also verifies whether the sample is expired and redirects to the expiration page if so.

The barcode needs to be in a very specific format as described [here](https://github.com/onaio/rdt-standard/issues/302#issue-643201478). Maybe verify if this is the case?

**Comment by shivenbhatt1** [comment]
![image](https://user-images.githubusercontent.com/47836489/90253231-d143a080-de0e-11ea-9cc1-f9ad924df04f.png)
Barcode examples for samples posted above.

The sample barcodes are different from the RDT barcodes for barcode string link that you have posted.

Barcode string is <FNC1>21A1313-B<FNC1>240NS-1234

Which pulls out Serial number: A1313-B

What I think may be going on here is that OneScan may be the issue where it is looking for expiration date of the sample barcode, and that isn't encoded here. Is there a way to configure this so that OneScan/OpenSRP isn't looking for the expiration date?

**Comment by vincent-karuri** [comment]
These variation in barcode formats is not a good thing since we have no way of knowing how to interpret the barcode when persisting data to OpenSRP.

Are there going to be multiple formats of barcodes that need to be supported?

The expiration date check is happening on OpenSRP - the rationale was similar to the malaria case where we want to ensure expired products are restricted.

**Comment by vincent-karuri** [comment]
The only other way to do this is store the string without extracting the individual components. 

We would however need a deterministic way to tell what each of the components represent later on.

**Comment by shivenbhatt1** [comment]
@vincent-karuri Just found out that 240 is for encoding any additional information we want. Our main concern is the string post "21" and before "240" which gives us our barcode ID. We would pull that as the barcode ID. No expiration date for samples is needed since samples shouldn't have an expiration date, only RDTs do.

**Comment by pld** [comment]
Is this still an issue?

**Comment by shivenbhatt1** [comment]
@pld yes, we are unable to scan sample barcodes at the moment

**Comment by vincent-karuri** [comment]
@shivenbhatt1 I want to confirm that this is a standard schema and that we'll be using it going forward.

Is [this](https://github.com/onaio/rdt-standard/issues/302#issue-643201478) no longer valid?

Will we need to worry about different formats encoded in the barcode?

As is at the moment, we are extracting the individual  components in this [format](https://github.com/onaio/rdt-standard/issues/302#issue-643201478) and saving them individually while validating expiration date. 

If we are changing the format, the logic will be affected and we need to make a decision as to whether we should only save the entire string and not it's individual components separately. 

Additionally, the same scanner is used on the RDT and I believe expiration date applies here?

We need to worry about how to define rules for extracting information from the barcode string - if not on the app, then later on during analysis.

**Comment by shivenbhatt1** [comment]
@vincent-karuri We would need to support scanning 2 types of barcodes:
1) that is for RDTs which has temp sensor, GTIN, unique ID, expiration date and lot code - exp date is verified here
2) Sample barcodes which has a unique ID only, with some extra string "240" that can be used to capture additional metadata (not being used currently) - exp date is not verified here

Therefore, would the OneScan work for both purposes? or will we need to use the google scanner for the sample barcodes? I believe you would just extract the individual components without validating the expiration date for the sample barcodes specifically. The rules for extracting information from the barcode string would, therefore, have to be flexible wherein you extract/save the fields that are available.

There are no expected changes outside of the requirements here.
