### ISSUE TITLE
Build client registration form

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#36]
Fields:

- [ ] Unique client identifier, can be auto-generated or inputted, auto-generate for now
- [ ] Client age
- [ ] Client showing signs of fever
- [ ] Store background info in JSON since other fields may need to be added in future, during client processing, the unique client id and age can be extracted and the background info left as JSON. `personalAtrribute` field in EC model.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 

At what point and how is the test administrator informed that they need to administer an RDT test if the patient is below the age of 5 or shows signs of fever?

It can be a toast message and the CHV can perform the test right after the registration is done?

**Comment by pld** [comment]
Shiven says: in Kenya
* They need to administer an RDT test if the patient is below the age of 5 or shows signs of fever
* The test is done immediately after registration

In Indonessia, waiting to hear back

**Comment by vincent-karuri** [comment]
Closed by https://github.com/onaio/rdt-standard/pull/58
