### ISSUE TITLE
Build the patient history repository

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#381]
This repository will power the queries needed to populate the [patient history](https://github.com/onaio/rdt-standard/issues/380#issue-679194989) and [visits](https://github.com/onaio/rdt-standard/issues/379#issue-679190905) views.

The queries to be supported include:

- [x] Query number of visits matching `baseEntityId` and grouped by date  
- [x] Query events matching date, `baseEntityId` and `eventType`

NB: We should check if these queries are already directly supported by the `EventClientRepository`.

**Comment by pld** [comment]
does `baseEntityId` represent the patient?

**Comment by vincent-karuri** [comment]
> does `baseEntityId` represent the patient?

Yep, it's OpenSRP's unique patient ID.
