### ISSUE TITLE
In the Travel & Contact Exposure, Denpasar is spelled incorrectly

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#382]
Denpasar is spelled incorrectly in Travel & Contact Exposure for the Symptoms and History form.

It currently reads "Denpasa"

**Comment by vincent-karuri** [comment]
Shouldn't this be updated in the property files?

**Comment by shivenbhatt1** [comment]
@vincent-karuri SID translated it in the correct form, so Bahasa should be correct

**Comment by vincent-karuri** [comment]
Translations are not handled manually on the developer side. As long as the property file is correct, the text should render the same on the form.

Looking at [this](https://www.transifex.com/onaio-1/rdt-standard/viewstrings/#id/rdt-open-reader-src-covidindonesia-resources-patient-diagnostics-form-properties--add-covid-forms/293593438?q=text%3Adenpasa) and [this](https://www.transifex.com/onaio-1/rdt-standard/viewstrings/#id/rdt-open-reader-src-covidindonesia-resources-patient-diagnostics-form-properties--add-covid-forms/293593438?q=text%3Adenpasa) the string says `Denpasa`.

The correction needs done through the property file and committed to master.

**Comment by pld** [comment]
all these keys should say `Denpasar`, no? https://github.com/onaio/rdt-standard/search?q=denpasa&unscoped_q=denpasa
