### ISSUE TITLE
Define presenter-view register fragment contract class

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#42]
This is the MVP architecture contract class

May need:

- View: 

  1. `startForm(JSONObject formName)`
  2. `getJsonFormUtils`

- Presenter:

  1. `saveForm` which calls fragment interactor
  2. `saveImage` which calls fragment interactor
  3. `startForm` which calls fragment view

**Comment by pld** [comment]
Latest mRDT inteface we have access to, `cropRDT` seems the closest to what we'd send to `saveImage`

**Comment by vincent-karuri** [comment]
Contract class created
