### ISSUE TITLE
When temperature sensor is triggered, the user needs to be asked to take a new RDT

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#447]
I noticed that we aren't currently doing anything with temperature sensor triggered barcodes, and we are allowing users to continue through to conduct RDTs. This may not be a huge issue until these barcodes are being used in the field so we could wait for the next release.

When the temperature sensor for RDT barcode is triggered "Sensor triggered: yes" the user needs to be told that the RDT has been exposed to high heat.

Maybe something like this: "This RDT has been flagged for high heat exposure and reliability has been compromised. Please use another RDT."

They should then be taken back a screen to barcode capture/manual entry of RDT information screen.

What do you think @pld ?

**Comment by shivenbhatt1** [comment]
![image](https://user-images.githubusercontent.com/47836489/90673851-4c012700-e226-11ea-956e-7eb1db11eb87.png)

**Comment by pld** [comment]
Do we need to allow them to override this to use an RDT that's triggered the temp sensor?

**Comment by shivenbhatt1** [comment]
For Testing:

**Temp sensor untriggered:**
![image_from_ios-1](https://user-images.githubusercontent.com/47836489/91452460-99941a00-e84c-11ea-9905-4bbce3ccfb34.jpg)
**Temp sensor triggered:**
![image_from_ios](https://user-images.githubusercontent.com/47836489/91452470-9c8f0a80-e84c-11ea-9c53-d0172b6c2a3a.jpg)

**Comment by shivenbhatt1** [comment]
blocked by #341

**Comment by vincent-karuri** [comment]
@shivenbhatt1 is the interaction here finalised? @syedowaisali90 is already working on this.

**Comment by shivenbhatt1** [comment]
@vincent-karuri what do you mean by is the interaction here finalized?

**Comment by vincent-karuri** [comment]
https://github.com/onaio/rdt-standard/issues/447#issuecomment-682595845 the comment here says it's blocked.

Is this resolved?

**Comment by shivenbhatt1** [comment]
Upon looking at this further, #341 does not block this issue.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 I think it makes sense to use the same page when the sensor is triggered or the RDT is expired?

I asked @syedowaisali90 to add a more general error message `This RDT is unusable either because it's expired or has been exposed to unsafe heat levels. Please use another RDT.` Thoughts?
