### ISSUE TITLE
App unexpected closes/crashes when saving sample shipment form

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#448]
The application unexpectedly closes/crashes when saving the completed sample shipment form.

The test was run on a single phone 3 times.

**Comment by vincent-karuri** [comment]
Does this only happen for the form launched via the drawer menu?

**Comment by shivenbhatt1** [comment]
@vincent-karuri just tested it, only happens in the drawer menu, not from patient profile.
