### ISSUE TITLE
Look into creating a library from medic mobile's RDT image capture implementation

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#45]
This code base looks useful for taking RAW camera images and preprocessing them.

Can be leveraged for the camera JSON form widget.

Should benefit from [this](https://stackoverflow.com/a/23765263/9782187). At the moment, the library will not be refactored for general re-usability - it's only intended for use in this app.

- [ ] Create an interface for image capture functionality, to allow switching out different algorithms or libraries
- [ ] Look into implementing callbacks when image is taken to allow a user to perform their own saving

[This](https://github.com/medic/rdt-capture/blob/master/app/src/main/java/edu/washington/cs/ubicomplab/rdt_reader/ImageQualityActivity.java) class may be helpful

**Comment by pld** [comment]
Note that Audere is working on a refactoring of the mRDT app, this is the interface we have, we're not sure when this will be complete, but we'd like to hang-off making changes until that refactor is complete (if we can given our timeline) and and/or we'd like to make changes in their repo, https://docs.google.com/document/d/1f6diT9VOaoK-A-Ug-6pe2cY37SiH-eWcSP5WoAU0ZHQ/edit

**Comment by vincent-karuri** [comment]
Done.
