### ISSUE TITLE
Complete RDT Deployment on Google Playstore

### ISSUE THREAD

**Issue by ndegwamartin** [onaio/rdt-standard#461]
In order to complete the upload process for the new RDT OpenReader C19, we need to complete the following mandatory Playstore checklist

- [x] App access -  Provide instructions on how to access restricted parts of your app
- [x] Target audience and content - The Feature graphic upload is the only one pending here. 

The Feature Graphic is a 1024 x 500 image with the Google best practice spec defined [here](https://developer.android.com/distribute/best-practices/launch/feature-graphic) 

**As a side note:** I think Google are becoming way more stringent with their requirements this time round, we are probably facing this with this RDT upload since it is a new App on Playstore

We will probably face this for all other new OpenSRP apps that we will publish in future.

**Comment by ndegwamartin** [comment]
The following process on Google Playstore are complete

- [x] App releases
- [x] Content rating
- [x] Pricing and distribution

The items we need to complete...

![Screenshot 2020-08-28 at 21 21 41](https://user-images.githubusercontent.com/10017086/91603882-706fa880-e976-11ea-9e25-3c49a26f56a2.png)

**Comment by pld** [comment]
Added these and created release, it's pending publication, it had this warning

```

Unoptimized APK
Warning:

This APK results in unused code and resources being sent to users. Your app could be smaller if you used the Android App Bundle. By not optimizing your app for device configurations, your app is larger to download and install on users' devices than it needs to be. Larger apps see lower install success rates and take up storage on users' devices.

Resolution:

Use the Android App Bundle to automatically optimize for device configurations, or manage it yourself with multiple APKs.

```
