### ISSUE TITLE
Bugs exist on sample collection patient information confirmation screen

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#469]
3 bugs exist on patient collection confirmation screen:

- [x] 1. Patient Dob showing up as null
- [x] 2. Unable to continue forward even when both checkboxes are checked
- [ ] Sample ID field is missing

![image](https://user-images.githubusercontent.com/47836489/92481522-78b8b680-f1b4-11ea-81bd-1feae08a2fb6.png)

**Comment by syedowaisali90** [comment]
@shivenbhatt1 

- Sample id field will be shown only manual selection #329 

cc @vincent-karuri

**Comment by shivenbhatt1** [comment]
@syedowaisali90 is there no way to populate the sample ID field with the barcode that was scanned in the step before it?

**Comment by shivenbhatt1** [comment]
2. Unable to continue forward even when both checkboxes are checked is still an issue. Created a new patient, went through the sample collection workflow, scanned barcode, at the patient information screen for the end-user to confirm the information - both boxes are checked and I hit the Continue button. I am being asked to correct the error(s), where none exist.

**Comment by syedowaisali90** [comment]
> @syedowaisali90 is there no way to populate the sample ID field with the barcode that was scanned in the step before it?

@shivenbhatt1 we have relevance checked in sample id so if we come from barcode scan then we will not show the sample id but if you come from manual selection then we will show the sample id.

**Comment by vincent-karuri** [comment]
> @syedowaisali90 is there no way to populate the sample ID field with the barcode that was scanned in the step before it?

@shivenbhatt1 there probably is but what is the utility of providing the sample ID in the case that it was scanned?

i.e. how would the confirm this information?

**Comment by vincent-karuri** [comment]
> 1. Unable to continue forward even when both checkboxes are checked is still an issue. Created a new patient, went through the sample collection workflow, scanned barcode, at the patient information screen for the end-user to confirm the information - both boxes are checked and I hit the Continue button. I am being asked to correct the error(s), where none exist.

Isn't that what is being fixed as part of this issue?

**Comment by shivenbhatt1** [comment]
@syedowaisali90 @vincent-karuri The utility would be an aggregate display of the information for the user to confirm on the sample tube i.e this is the sample ID, patient name, patient DOB which is needed for processing the laboratory sample. If it provides great difficulty to add, that is fine, we can exclude it.

**Comment by vincent-karuri** [comment]
> @syedowaisali90 @vincent-karuri The utility would be an aggregate display of the information for the user to confirm on the sample tube i.e this is the sample ID, patient name, patient DOB which is needed for processing the laboratory sample. If it provides great difficulty to add, that is fine, we can exclude it.

I'm a bit confused here, is the sample ID manually affixed even when we scanned a barcode?

**Comment by shivenbhatt1** [comment]
@vincent-karuri The barcode is stuck onto the tube and the patient name and dob is written on. Just wanted to make sure there was one last confirmation that all the information is correctly attached and written on the tube before it is stored. This could be an issue if the health worker is working with multiple patients at once. If it is an easy lift, better to have the sample ID on there.

**Comment by vincent-karuri** [comment]
<img width="218" alt="Screen Shot 2020-09-10 at 12 48 00" src="https://user-images.githubusercontent.com/33488286/92713638-e6571500-f363-11ea-9888-4bdb82495e11.png">
Is this about confirming the ID at the bottom of the barcode?

**Comment by shivenbhatt1** [comment]
@vincent-karuri That is correct, making sure the barcode has been placed on the appropriate tube, and matching the sample ID at the bottom of the barcode with the patient name and DOB.

**Comment by vincent-karuri** [comment]
Ok, @syedowaisali90 are you able to work on this? 

After scanning, we'll need to pull the sample ID and write it to the field on the confirmation page.

**Comment by syedowaisali90** [comment]
> Ok, @syedowaisali90 are you able to work on this?
> 

yes
