### ISSUE TITLE
Implement timer button 

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#47]
Extend `ButtonFactory` in native forms and start timer on button click that has alarm once time (15 min) expires.

- [ ] Make time configurable
- [ ] `value` field should be the time on timer, should perhaps make sure this value is written before image is saved
- [ ] `isActive` field should be set to true when button is clicked
- [ ] `isActive` field should be set to false when time expires
- [ ] show toast message showing time is expired
- [ ] should record system time when it was clicked

**Comment by vincent-karuri** [comment]
@shivenbhatt1 

- What kind of alarm do we want here?
- How do we prompt the user to enter the RDT result, a toast message?
- The approach here uses a manual button that the user presses when ready, not sure what the system time approach means?

**Comment by shivenbhatt1** [comment]
1. I'm not sure what type of alarm we should add - TBD will ask PLD
2. Toast message should be fine
3. System timer runs in the background to observe any abnormality in the time between adding the reagents to the wells and the start of the manual timer button.
4. Time on timer should be recorded at the time the image is captured.  There are set guidelines from when the reagents enter the wells of the RDT and our specific one states that it must be read at 15 minutes, but is invalid after 30 minutes.  This is something we should consider, a message should possibly show if the CHV has not captured the image of the test within 30 minutes of starting the manual timer.
5. System timer should begin at the place buffer step, or if image of buffer vial is taken.

**Comment by vincent-karuri** [comment]
Ok, what is the event that marks that the reagents have been added? Is checking a box good enough?

**Comment by shivenbhatt1** [comment]
Some kind of confirmation box would be good for now, we are looking at confirmation by image capture, but this hasn't been determined yet.  I have sent an email request to the developers of the prototype to see if they will be adding a color change feature to the RDT to confirm addition of buffer and blood.

**Comment by vincent-karuri** [comment]
Using checkboxes for each sequential test step.

**Comment by vincent-karuri** [comment]
Closed in favour for #78
