### ISSUE TITLE
Cannot scroll from the profile's page to access the sample shipment details option

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#475]
The options do no fit in the screens of some devices and the page is not scrollable

![Screenshot_20200910-170947_RDT Open Reader](https://user-images.githubusercontent.com/29072646/93051184-c29a1480-f66c-11ea-852e-754deffff969.jpg)

**Comment by vincent-karuri** [comment]
This can change to a scroll view.
