### ISSUE TITLE
Malformed fields on RDT visits for "# of covid patients in compound", "# of covid patients who are close contacts" and "# of covid contacts outside household"

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#523]
Malformed fields on RDT visits for "# of covid patients in compound", "# of covid patients who are close contacts" and "# of covid contacts outside household"
![Screenshot_20200921-161758_RDT Open Reader](https://user-images.githubusercontent.com/29072646/93783830-db8a6300-fc34-11ea-8174-a53fb0b48932.jpg)
![Screenshot_20200921-161805_RDT Open Reader](https://user-images.githubusercontent.com/29072646/93783840-e04f1700-fc34-11ea-9964-44a7e7141089.jpg)vin
![Screenshot_20200921-161811_RDT Open Reader](https://user-images.githubusercontent.com/29072646/93783846-e1804400-fc34-11ea-9fd6-7834897b0f4b.jpg)

**Comment by vincent-karuri** [comment]
@shivenbhatt1 do you see this on the app for new visits?

**Comment by vincent-karuri** [comment]
I'm unable to replicate this - shows up as number values for me on recent visits.

This only occurs on older visits hence the need to test on a newly created visit i.e. a new submission.

**Comment by shivenbhatt1** [comment]
@vincent-karuri @Mstjamush Same, I only see it on older visits, before the update

**Comment by vincent-karuri** [comment]
**NB**: A fix for this should be made against https://github.com/onaio/rdt-standard/tree/v1.5 since it's a bug from QA of `v1.5.0 RC`.

**Comment by Mstjamush** [comment]
Closed
