### ISSUE TITLE
When validating email address (Sample Shipments), if an email has a space before or after...it's flagged as invalid

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#525]
When validating email address (Sample Shipments), if an email has a space before or after...it's flagged as invalid

**Comment by vincent-karuri** [comment]
@syedowaisali90 could you confirm if this is still an issue by testing on a device?

**Comment by syedowaisali90** [comment]
@vincent-karuri No, i had fixed that.

**Comment by vincent-karuri** [comment]
I don't think this was done for sample shipments, could you confirm that?

**Comment by syedowaisali90** [comment]
> I don't think this was done for sample shipments, could you confirm that?

yes, you are right it was not fixed in sample shipments. Now i have fixed that.

**Comment by vincent-karuri** [comment]
Fixed
