### ISSUE TITLE
Regresssion - Sample collection page - one cannot proceed when they choose Swab as a option - Date validator is invalidation all dates for VTM expiration date

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#526]
Sample collection page - one cannot proceed when they choose Swab as a option - Date validator is invalidation all dates for VTM expiration date

**Comment by vincent-karuri** [comment]
I'm unable to reproduce this. Is the date at least a day before today?

**Comment by vincent-karuri** [comment]
The bug was that it was expecting dates before and not after today. Fixed!
