### ISSUE TITLE
Translations Issues

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#527]
Translations on
	a) Login Page
	b) Home page - gender is in English
	c) Profile Page - Gender, Patient forms and Patient history are in English
	c) Patient History - Visit is in English
	d) Visits - In scenarios where "No data available" is in English
	e) Symptoms and History forms - "# of covid patients..." hint is in English
	f) Sample collection page is in English
	g) Other Clinical data is in English

![Screenshot_20200921-173826_RDT Open Reader](https://user-images.githubusercontent.com/29072646/93784399-a7637200-fc35-11ea-8a65-5805f16d3916.jpg)
![Screenshot_20200921-173912_RDT Open Reader](https://user-images.githubusercontent.com/29072646/93784410-ab8f8f80-fc35-11ea-9268-2debff03b83a.jpg)
![Screenshot_20200921-174142_RDT Open Reader](https://user-images.githubusercontent.com/29072646/93784419-ac282600-fc35-11ea-8bd9-b5bb8b605bb1.jpg)
![Screenshot_20200921-174257_RDT Open Reader](https://user-images.githubusercontent.com/29072646/93784422-acc0bc80-fc35-11ea-8cd1-d5781d18c970.jpg)
![Screenshot_20200921-174625_RDT Open Reader](https://user-images.githubusercontent.com/29072646/93784426-ad595300-fc35-11ea-85e2-493248e37ead.jpg)
![Screenshot_20200921-175044_RDT Open Reader](https://user-images.githubusercontent.com/29072646/93784429-adf1e980-fc35-11ea-94e1-380a2238682a.jpg)
![Screenshot_20200922-122907_RDT Open Reader](https://user-images.githubusercontent.com/29072646/93784432-af231680-fc35-11ea-93ea-0f1a5e960ba4.jpg)

**Comment by vincent-karuri** [comment]
**NB**: A fix for this should be made against https://github.com/onaio/rdt-standard/tree/v1.5 since it's a bug from QA of `v1.5.0 RC`.

**Comment by shivenbhatt1** [comment]
@vincent-karuri @syedowaisali90 do you know which resource the gender from the first screen shot that josphat highlighted is coming from?

**Comment by vincent-karuri** [comment]
Those strings are not part of any resource - they're a result of how OpenSRP saves values from radio buttons. We could possibly find a way to translate them on RDT but it would feel a bit hacky.

**Comment by vincent-karuri** [comment]
Fixed.
