### ISSUE TITLE
Bug in form translations

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#578]
Forms are not translated for Bahasa i.e. the forms are launching in English instead of Bahasa. Could this be related to how the language switcher works?

Also, the patient history questions are not showing in Bahasa as they should.

**Comment by syedowaisali90** [comment]
> Also, the patient history questions are not showing in Bahasa as they should.

Strings were missing for Bahasa I have added them.

**Comment by syedowaisali90** [comment]
>Forms are not translated for Bahasa i.e. the forms are launching in English instead of Bahasa. Could this be related to how the language switcher works?

Probably could be,

**Comment by syedowaisali90** [comment]
Yes, it was a language switcher problem not it's fixed.
