### ISSUE TITLE
Expired RDT bug in V1.7

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#580]
If conducting a manual RDT, you can enter a date in the past for the expiration date and the user can still continue to do the test. We want to make sure that all expired dates (past dates) are flagged and the user is requested to take another RDT, returning them back to the screen where they are asked to choose manual or barcoded RDT.

**Comment by vincent-karuri** [comment]
This flow is a bit different from what is happening with the sample collection form. I think it's better if we stay consistent. The sample collection form shows an error on the same page if the expiration date is invalid which prevents navigation to the next page.

**Comment by shivenbhatt1** [comment]
@vincent-karuri just wanted to make sure we are on the same page, the sample collection form doesn't have an expiration for the sample itself, but it is the VTM that has the expiration date, right? #359 

I agree with keeping consistent. Let's show the error on the same page.

**Comment by vincent-karuri** [comment]
Yea, the VTM.
