### ISSUE TITLE
Bug in V1.7 - Unable to manually select Wondfo SARS-CoV-2 Antibody test

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#581]
If you try to select the first RDT type (Wondfo) an error displays stating that this field is required. I tried changing the rdt to a different type and back to Wondfo, and this error still displays.

I'm wondering if the first scroll bar field should state "Select RDT Type", the user selects the dropdown menu and selects the RDT from there. This may solve the issue we are experiencing here.

**Comment by vincent-karuri** [comment]
Yea, I was able to reproduce this. As per your suggestion, perhaps there should not be a pre-selected value. Or it could be a bug that needs fixing in Native Forms. Either way, worth investigating.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 is this fixed?

**Comment by shivenbhatt1** [comment]
This is fixed.
