### ISSUE TITLE
Bug in V1.7 - If barcode is scanned of RDT, Cannot launch RDT Capture Widget

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#582]
If you decide to scan the barcode of RDT, the app attempts to open the RDT Capture Widget, however, the screen just shows please wait with a spinning wheel.

**Comment by vincent-karuri** [comment]
Capture will not work for the `scan barcode` workflow at the moment since there's no way to fetch the configuration from the FHIR resource. This is related to the conversation we're having on how to  identify the FHIR resource for barcoded RDTs. We need to discuss this further.

**Comment by shivenbhatt1** [comment]
@vincent-karuri Final decision on this was to generate a 13 digit GTIN string with the last digit being the check digit.
I spoke with Anu on this and he suggested we start with a distinctive set of digits denoting that it is a unique scheme and not actually a GTIN like "999"

**I followed the following process:**
Use a numerical scheme starting with 999+6 digits taken from CareStart IDs+000+Check digit generated from [GS1 Check Digit Calculator](https://www.gs1.org/services/check-digit-calculator)

**I retrieved the following IDs:**
Wondfo SARS-CoV-2 Antibody Test | 9991976400004
Alltest 2019-nCoV IgG/IgM | 6970277514699 - **note that this is a real GTIN**
Alltest 2019-nCoV IgG/IgM | 6970277514699 - **note that this is a real GTIN**
Realy Tech 2019-nCOV IgG/IgM | 9992128110000
Realy Tech 2019-nCOV IgG/IgM | 9992128110000
Green Spring COVID-19 IgG / IgM Rapid Test Kit | 9992030340007
Green Spring COVID-19 IgG / IgM Rapid Test Kit | 9992030340007
SD Biosensor STANDARD Q Covid | 9992128780005
SD Biosensor STANDARD Q Covid | 9992128780005
SD Biosensor STANDARD Q Syphilis Ab | 9992031090000
SD Biosensor STANDARD Q Syphilis Ab | 9992031090000
SD Biosensor STANDARD Q COVID-19 Ag | 9991976080008
Realy Tech Novel Coronavirus Antigen Rapid Test Cassette (Swab) | 9992030590006
Lituo COVID-19 Antigen Detection Kit | 9991976320005
JOYSBIO SARS-CoV-2 Antigen Rapid Test Kit | 9992030910002

These numbers have been recorded in the fhir device definitions list: https://docs.google.com/spreadsheets/d/1P9yCzXHoy9Dz0_hp43GX_qpOc6Ayvz_D2TCReNVN_n4/edit#gid=0

**Comment by shivenbhatt1** [comment]
@vincent-karuri I have added the device definitions for SD Biosensor StandardQ Syphilis and Redpharm to the FHIR definitions document.

**Comment by vincent-karuri** [comment]
Thanks @shivenbhatt1

**Comment by vincent-karuri** [comment]
@pld @shivenbhatt1 is there a requirement to have the [identifier](https://github.com/onaio/Covid19/blob/87cec883409c16b5ce3ac7b1ab9c0df4cb2a06e6/scripts/device-definition/device_definitions-rdt-og-2020-10-07.json#L72) as a uuid? Is it possible to use the product code as the resource identifier? This would simplify FHIR Path queries.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 do we go ahead and remove the duplicate resources (blood/plasma) based on our conversation about combining them?

**Comment by shivenbhatt1** [comment]
@vincent-karuri Yes, let's go ahead and combine them

**Comment by vincent-karuri** [comment]
@shivenbhatt1 the gtins need to be 14 and not 13 digits https://github.com/onaio/rdt-standard/issues/302#issue-643201478. OneScan is extracting the wrong gtin with the 13 digits.

**Comment by shivenbhatt1** [comment]
@vincent-karuri okay, lets add a 0 in front, seems like that is what is being done in the other barcodes

**Comment by vincent-karuri** [comment]
Already added a zero to the end and generated check digits. Aren't we supposed to maintain 999 at the beginning?

**Comment by shivenbhatt1** [comment]
@vincent-karuri That works too, we just need to confirm if the check digit is still valid and OneScan is actually reading that. We will be able to generate some test barcodes next week in Indonesia to try it out.

**Comment by vincent-karuri** [comment]
I already verified it's working and generated the check digit based on the now 13-digit unique id (i.e. minus the check digit).

**Comment by vincent-karuri** [comment]
After adding the check digit, we get the 14-digit product id which can then be encoded into the barcode https://github.com/onaio/rdt-standard/blob/4f66bcbdde458f0dd3aed007628f739a16381f12/rdt-open-reader/src/covidIndonesia/assets/fhir.resource/DeviceDefinition.json.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 is this fixed?

**Comment by shivenbhatt1** [comment]
@vincent-karuri this is working now
