### ISSUE TITLE
OneScan is crashing due to FHIR RDT Definitions being absent

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#585]
This crash occurs during RDT capture. I think I managed to find out the reason, the device definitions aren't recorded in the FHIR list. I completed the following assessments after updating the software of my phone and the assessment came out fine.

1.All test (1) - OK
2.All test (2) - OK
3. Realy tech (1) - OK
4.Realy tech (2) - OK
5. Green Spring (1) - OK
6. Green Spring (2) - OK
7. STANDARD Q (1) - OK
8. Standard Q (2) - OK
9. standard Q syphilis Ab (1) - Crash
10. standard Q syphilis Ab (2) - Crash
11. Standard Q Covid Ab - Crash

Solution: Update the device definitions in the resources. This assessment is being run on a google pixel 3, will try again on other devices that haven't been updated since I believe the error did occur elsewhere on another my previous QA round.

@vincent-karuri Can you point me to where the image is being pulled from?

**Comment by shivenbhatt1** [comment]
@vincent-karuri We should discuss a solution for devices that don't have definitions tomorrow.  We might be able to launch manual capture instead of having OneScan crash?

**Comment by vincent-karuri** [comment]
Thanks for the thorough review @shivenbhatt1. Yes, that version of the app is expected to crash for RDT's without a valid configuration. A more recent version of the app does not allow the capture to launch and instead shows the user a toaster message explaining the configuration is missing.

We can definitely make this transition directly to manual capture, as it the case with the `other` selection on the most recent version of the app.

**Comment by vincent-karuri** [comment]
Images are hosted in [rdt scan repository](https://github.com/onaio/rdt-capture/tree/8ea2381a3c6973377e5a6326a57a07acff9c1154/lib/src/main/res/drawable-nodpi) atm.

**Comment by shivenbhatt1** [comment]
@vincent-karuri I think the approach we have taken in the most recent version is better than the decision we made today to remove the RDTs without device definitions from the list. For one, there are user workflows that have been recorded in the list that can still be used, and two, I believe these will be integrated at some point anyway.

We can continue to use the toaster message explaining that the configuration is missing and open the manual capture.

Does that work?

**Comment by shivenbhatt1** [comment]
> Images are hosted in [rdt scan repository](https://github.com/onaio/rdt-capture/tree/8ea2381a3c6973377e5a6326a57a07acff9c1154/lib/src/main/res/drawable-nodpi) atm.

@vincent-karuri This repository is not updated with the most recent RDTs, are we actually pulling from CJ's main branch that I updated?

FYI, I've been working in my own branch for most recent updates that eventually get merged into CJ's. I added 2 more images today for Redpharm and SDbiosensor syphilis https://github.com/shivenbhatt1/rdt-scan/tree/master/app/src/main/res/drawable-nodpi

**Comment by vincent-karuri** [comment]
@shivenbhatt1 https://github.com/cjpark87/rdt-scan/tree/master/app/src/main/res/drawable-nodpi  is the correct url.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 [your fork](https://github.com/shivenbhatt1/rdt-scan/tree/master/app/src/main/res/drawable-nodpi) has quite a few conflicts with the [ona version](https://github.com/onaio/rdt-capture/tree/master/lib/src/main/res/drawable-nodpi). Is it possible to upload the images directly to the ona version?

**Comment by shivenbhatt1** [comment]
@vincent-karuri Is it possible because I changed the name of some of the images? I wanted to maintain consistency and the images in that folder were incorrectly labeled. CJ merged my updates. The last 2 should be merged today sometime.

**Comment by shivenbhatt1** [comment]
@vincent-karuri Uploads are unavailable.

![covid19_alltest_ref_v0](https://user-images.githubusercontent.com/47836489/98049694-38fdfc00-1dfe-11eb-99b7-5fc2d4472f3b.jpg)
![covid19_greenspring_ref_v0](https://user-images.githubusercontent.com/47836489/98049697-39969280-1dfe-11eb-9ef5-dfb806c7502d.jpg)
![covid19_realytech_ref_v0](https://user-images.githubusercontent.com/47836489/98049698-39969280-1dfe-11eb-8723-31074311094e.jpg)
![covid19_sdbiosensorIgG_ref_v0](https://user-images.githubusercontent.com/47836489/98049700-39969280-1dfe-11eb-923a-d90179764bd8.jpg)
![covid19_sdbiosensorIgM_ref_v0](https://user-images.githubusercontent.com/47836489/98049701-39969280-1dfe-11eb-99f9-0d409f167c62.jpg)
![covid19_wondfo_ref_v0](https://user-images.githubusercontent.com/47836489/98049702-39969280-1dfe-11eb-8b21-be84b6a63e06.jpg)
![covid19ag_joysbio_ref_v0](https://user-images.githubusercontent.com/47836489/98049703-39969280-1dfe-11eb-8c64-dda560cd8eb3.JPG)

**Comment by vincent-karuri** [comment]
@shivenbhatt1 is this about our repo? Wasn't the suggestion to upload directly to it https://github.com/onaio/rdt-standard/issues/585#issuecomment-719361531.

Also, do all these RDTs have corresponding FHIR configs?

**Comment by shivenbhatt1** [comment]
@vincent-karuri I'm unable to directly add to our repo since it is protected. I will send you a slack message with the images and correct names I posted above. I used the Alltest cassette as an example, which is labeled as jal medical in our repo. This may be causing the crash since the code was updated to link the image I send you.

**Comment by vincent-karuri** [comment]
I don't think that's the problem. There's no relationship between updating
the images and the app crashing. We are pulling images from the fhir
resource.

**Comment by shivenbhatt1** [comment]
@vincent-karuri The issue is, the FHIR resource doesn't point to the image that is in [https://github.com/onaio/rdt-capture/tree/master/lib/src/main/res/drawable-nodpi](https://github.com/onaio/rdt-capture/tree/master/lib/src/main/res/drawable-nodpi). These need to be updated with the new images that match CJ's master repo

**Comment by vincent-karuri** [comment]
I don't follow. Is the app still crashing on capture? I've tested capture on an image of Alltest multiple times and it works just fine.

**Comment by shivenbhatt1** [comment]
Not if you use barcode scan pathway. It is working if you use manual capture.

Just for reference, I am scanning this barcode and returning this result.
![image](https://user-images.githubusercontent.com/47836489/98173821-c0f90a00-1ec1-11eb-88c4-2dd0d43ad508.png)
![image](https://user-images.githubusercontent.com/47836489/98173842-c6565480-1ec1-11eb-8a42-7e3eb0255f84.png)

**Comment by vincent-karuri** [comment]
https://github.com/onaio/rdt-standard/issues/606#issuecomment-721647979 should fix this (I was able to scan the barcode and proceed to capture). We should merge these two issues (close one) - they seem to be addressing the same thing.

**Comment by vincent-karuri** [comment]
This is fixed.
