### ISSUE TITLE
RDT Form error

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#597]
RDT Form  - referral health facility section.

**Ellya QA**- In the RDT section, there is this section asking about which referral health facility the patient went to. The third option doesn't match with the question. It says, where is the assessment conducted. The first option says hospital, second says clinic, and the forth says Other. Probably it is misplaced

**Shiven Recommendation**- This section has two questions that seemed to have been merged. Name of the facility should go with 3rd option.

![image](https://user-images.githubusercontent.com/47836489/98006573-6b890400-1dc0-11eb-98d8-8bd3a95e4a56.png)

**Comment by vincent-karuri** [comment]
@shivenbhatt1 should we just remove the radio button group and simply have the dropdown?

**Comment by shivenbhatt1** [comment]
@vincent-karuri the question will be if other is needed here. It would be better to have the dropdown above 'other' though and not make the drop essential. If they select 'other' an open field displays for them to enter a location manually.

**Comment by vincent-karuri** [comment]
By essential do you mean mandatory/required? If I get you correctly you're saying we should have an `other` field below the drop-down?

In that case, couldn't we simply have `other` as part of the drop-down and the manual entry field visible when other is selected for the drop-down?

**Comment by vincent-karuri** [comment]
And is the decision yes to replacing the radio group with the drop-down list?

**Comment by shivenbhatt1** [comment]
I agree to 

> By essential do you mean mandatory/required? If I get you correctly you're saying we should have an `other` field below the drop-down?
> 
> In that case, couldn't we simply have `other` as part of the drop-down and the manual entry field visible when other is selected for the drop-down?

I agree to having other as part of the drop-down, and the decision is yes to replacing the radio group with a drop-down.
