### ISSUE TITLE
Translation Issues

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#604]
**I had Ellya from SID translate the properties files into Bahasa as txt format. For some reason, some of the asset translations weren't properly working.**

We need to replace the Bahasa properties files that we have with these.

[patient-diagnostics-form.properties_in_v2.txt](https://github.com/onaio/rdt-standard/files/5484370/patient-diagnostics-form.properties_in_v2.txt)
[rdt-capture-form.properties_in_v2.txt](https://github.com/onaio/rdt-standard/files/5484371/rdt-capture-form.properties_in_v2.txt)
[sample-collection-form.properties_in_v2.txt](https://github.com/onaio/rdt-standard/files/5484372/sample-collection-form.properties_in_v2.txt)
[wbc-form.properties_in.txt](https://github.com/onaio/rdt-standard/files/5484373/wbc-form.properties_in.txt)
[xray-form.properties_in.txt](https://github.com/onaio/rdt-standard/files/5484375/xray-form.properties_in.txt)

**Comment by vincent-karuri** [comment]
@syedowaisali90 please look into this.
