### ISSUE TITLE
Bug in contact exposure in patient diagnostics form

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#605]
In the Travel and contact exposure portion of the patient diagnostics form, when entering # of covid patients in compound, # of covid-19 patients who are close contacts, and # of close contacts outside:

If you enter the number 1: 2 patient contact requested
If you enter the number 2: 4 patient contacts are requested
If you enter the number 3: 5 patient contacts are requested
If you enter the number 4: 6 patient contacts are requested
If you enter the number 5, 10 patient contacts are requested

Not sure what is going on here and why these numbers are so far off.

**Comment by shivenbhatt1** [comment]
An additional note, if you change the number of contacts in the box and update, you can not proceed. A message telling you that "error(s)" exist shows up at the bottom and the user needs to exit out of the form and refill everything out.

**Comment by vincent-karuri** [comment]
> An additional note, if you change the number of contacts in the box and update, you can not proceed. A message telling you that "error(s)" exist shows up at the bottom and the user needs to exit out of the form and refill everything out.

Moving this to a separate issue https://github.com/onaio/rdt-standard/issues/610
