### ISSUE TITLE
Crash - After OneScan barcode scan

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#606]
My app crashed twice after reading the temperature sensor on the RDT (both triggered and not triggered) on the test model Samsung J7 using the most up to date OneScan and Covid App freshly installed.

This was replicated twice.

Covid patient 2 -> RDT -> Scan Barcode -> Scanned Alltest barcode, Status showed okay (Continue) -> Displayed message says "RDT Open Reader has stopped."

**Comment by vincent-karuri** [comment]
Does the barcode have a valid gtin assigned? The gtin must be part of the `udiDeviceIdentifier` in one of the devices here https://github.com/onaio/rdt-standard/blob/283-update-rdt-templates-dynamically/rdt-open-reader/src/covidIndonesia/assets/fhir.resource/DeviceDefinition.json.

**Comment by vincent-karuri** [comment]
I also notice that AllTest has a 13 digit gtin the fhir device definition spreadsheet document. Shouldn't it be 14?

**Comment by vincent-karuri** [comment]
I've used `06970277514699` instead of `6970277514699` for Alltest and removed the gtin block (keeping the manufacturer block) in the fhir resource. Fixes the crash for alltest. Couldn't replicate the issue for other RDTs.
