### ISSUE TITLE
Additional Identity Type in Bahasa version (Government ID Section)

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#608]
Hi, Ellya from SID here, helping the QA in the Bahasa version.
I have an issue with the identity type. In Indonesia, we have 3 types of Identity: National Identity Card (KTP), Passport (Paspor), and Driving's license (SIM). Could we add one more identity type on the government ID section?

![ID Issue](https://user-images.githubusercontent.com/73918009/98057481-faefef00-1e74-11eb-9980-8fe8f8773fc1.png)

**Comment by shivenbhatt1** [comment]
@vincent-karuri @syedowaisali90 in English we need to add "National Identity Card" because I think we already have drivers license then @ellyasafaa we can fix the translations accordingly.

Right now Drivers license is translating to KTP.
