### ISSUE TITLE
Bug on edit of repeating group edit text

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#610]
An additional note, if you change the number of contacts in the box and update, you can not proceed. A message telling you that "error(s)" exist shows up at the bottom and the user needs to exit out of the form and refill everything out.

**Comment by vincent-karuri** [comment]
This seems to be related to validation not being cleared for deleted repeating group views.

**Comment by zeeshan-vd** [comment]
@vincent-karuri this issue needs to be fixed in https://github.com/OpenSRP/opensrp-client-native-form. I'll create the PR there.
