### ISSUE TITLE
Joysbio missing from the rdt device list

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#611]
After reviewing the list of RDTs available and the device definitions in the FHIR device list, I noticed that device Joysbio in row 16 is missing.  Could you update and add this in?

**Comment by vincent-karuri** [comment]
I've added this but the configs don't seem to work. I can't auto-capture the device image.

**Comment by shivenbhatt1** [comment]
Concluded that we will need a physical device to take measurements. The image that SID provided may not be adequate.
