### ISSUE TITLE
Translation Issue on Bahasa Apps V1.7 (Built on Nov 7) - Resources Urgently Needed

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#612]
I have changed the translation manually for the last update about the government ID type. Also, I made some changes based on Tami's suggestion. Please find the resource below for your reference.

[patient-registration-form.properties_in_v3.txt](https://github.com/onaio/rdt-standard/files/5504335/patient-registration-form.properties_in_v3.txt)
[sample-collection-form.properties_in_v3.txt](https://github.com/onaio/rdt-standard/files/5504369/sample-collection-form.properties_in_v3.txt)

Just wanna make sure,
patient-registration-form-original.step1.patient_dob.duration.label = DoB (This one will show the age, right?)
patient-registration-form-original.step1.patient_dob.hint = Date of birth (This one will ask for the date, right?)
Both of them in Bahasa will be translated as "Tanggal Lahir", but when I check on the apps, the other one will show the age. In case I translated in on the other ways, you can change it as it should be. Please see the pictures.
![Translation issue 0](https://user-images.githubusercontent.com/73918009/98432703-72cb4d00-20f3-11eb-9230-e44265f86bd5.png)

However, there are some pages and sections that are still in English on the latest apps (V1.7.0 built on Nov 7) and I can't find which resource to get it translated. Attached the pics for some pages that I need to translate and I need to change the translations. Could you please tell me which resources they are or what should I do to do the translations?

![Translation issue 2](https://user-images.githubusercontent.com/73918009/98432429-b96b7800-20f0-11eb-829f-1d667fea6d61.png)
![Translation issue 3](https://user-images.githubusercontent.com/73918009/98432432-bbcdd200-20f0-11eb-8083-bcbd94a427da.png)
![Translation issue 4](https://user-images.githubusercontent.com/73918009/98432434-bd979580-20f0-11eb-940c-e80fbd55eb10.png)
![Translation issue 1](https://user-images.githubusercontent.com/73918009/98432435-bec8c280-20f0-11eb-8ec7-4460dfa3aaaf.png)
![Translation issue 5](https://user-images.githubusercontent.com/73918009/98432989-ef5f2b00-20f5-11eb-8d3c-9e54188cd9c2.png)

**Comment by shivenbhatt1** [comment]
@ellyasafaa Can you finish the translations on transifex too, we have some pending translations there.

**Comment by zeeshan-vd** [comment]
@shivenbhatt1 @vincent-karuri @ellyasafaa Is there some manual tool to translate the string resources besides JMAG? I need to put translations of "Login" and "Show Password" etc into in/strings.xml.

**Comment by shivenbhatt1** [comment]
@zeeshan-vd 

Login: Gabung
Show Password: Tampilkan Kata Sandi

**Comment by ellyasafaa** [comment]
I need to correct the login part
Login: Masuk

**Comment by zeeshan-vd** [comment]
@ellyasafaa can you please provide translations of the following text?
 
1. Patient
2.  Contact's name
3.  Contact's phone number
4.  Value must be numeric
5.  Phone number cannot be more than 13 digits
6.  Phone number cannot be less than 8 digits
7.  Relationship with contact
8.  Date of first contact
9.  Date of last contact
10.  Location of contact
12.  Expired VTM! Please use another

**Comment by ellyasafaa** [comment]
@zeeshan-vd sure, here they are:
1. Patient: Pasien
2. Contact's name: Nama Kontak
3. Contact's phone number: Nomor Telepon Kontak
4. Value must be numeric: Nilai harus berupa angka
5. Phone number cannot be more than 13 digits: Nomor telepon tidak dapat lebih dari 13 digit
6. Phone number cannot be less than 8 digits: Nomor telepon tidak dapat kurang dari 8 digit
7. Relationship with contact: Hubungan dengan kontak
8. Date of first contact: Tanggal kontak pertama kali
9. Date of last contact: Tanggal kontak terakhir
10. Location of contact: Lokasi kontak
11. Expired VTM! Please use another: VTM telah kedaluwarsa! Tolong gunakan yang lain
