### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#623]
Translation issues
	a) The gender is captured in English on the Clients register page(Home page)
	b) error message when submiting forms and some fields are not filled in is in English (e.g Please correct the error(s) in the form to proceed)
	c) The form that extends for Contact details is in English

**Comment by shivenbhatt1** [comment]
@zeeshan-vd These are all taken care of now, right?

**Comment by zeeshan-vd** [comment]
@shivenbhatt1 (a) and (c) are fixed as part of Issue # 612. Translation of "Please correct the error(s) in the form to proceed" needs to be fixed.

@Mstjamush please provide the translation of this text.

**Comment by shivenbhatt1** [comment]
@zeeshan-vd any translations for bahasa can be directed to @ellyasafaa

**Comment by zeeshan-vd** [comment]
@ellyasafaa Please share the translations of following:

1. Found %d error(s) in the form. Please correct them to submit
2. Please correct the error(s) in the form to proceed

**Comment by ellyasafaa** [comment]
@zeeshan-vd sorry for the late response.
1. Found %d error(s) in the form. Please correct them to submit : Menemukan kesalahan %d dalam form. Mohon perbaiki sebelum dikirim
2. Please correct the error(s) in the form to proceed: Mohon perbaiki kesalahan dalam form untuk melanjutkan
