### ISSUE TITLE
Translation Issues on Bahasa App 

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#642]
The translation has been inputted well. However, I still find some details in English. Also, there was a change that I made in the last txt files that I sent on Github (sample-collection-form.properties_in_v3, attached), but it does not seem to change in the Apk. I also have addressed these same issues on Github, but they have not changed. Please see the details in PDF files below.

[Translation issues_SID.pdf](https://github.com/onaio/rdt-standard/files/5626784/Translation.issues_SID.pdf)
[sample-collection-form.properties_in_v3.txt](https://github.com/onaio/rdt-standard/files/5626786/sample-collection-form.properties_in_v3.txt)

**Comment by vincent-karuri** [comment]
@ellyasafaa Any new strings that need translations should appear on Transifex now. Please provide the translations when you get a chance.

**Comment by ellyasafaa** [comment]
Hi Vincent and team @vincent-karuri

I'd like to confirm whether the translation source is using the transifex or not. I still have 2 issues that don't match with the thing I have translated there.

![Translate](https://user-images.githubusercontent.com/73918009/103751214-85ea9280-503a-11eb-8314-f934a1797e49.jpeg)
It translated Saved! = Diselamatkan. However, it was translated by Shiven a long time ago, and I have fixed it about 5 months ago both on the transifex and on the txt files I sent you. It is supposed to be Saved! = Disimpan!
![Transifex 2](https://user-images.githubusercontent.com/73918009/103758671-15953e80-5045-11eb-9a72-d947582583d2.png)

For this, as requested by Ms. Tami, the head of SID, to not shorten the name of the organization, and this translation has met the expectation, but it has not inputted well in the apps.
![Transifex 1](https://user-images.githubusercontent.com/73918009/103748139-3c984400-5036-11eb-8f21-c0429087360c.png)

**Comment by vincent-karuri** [comment]
@ellyasafaa text should match transifex translations after they are merged. Please confirm whether this is still an issue on the latest version of the app.

**Comment by ellyasafaa** [comment]
@vincent-karuri I found out that there are some translations that are different from what I translated before and that was Shiven's translation. I heard that the Transifex was acting up, so I think it changed. I have reviewed it all again, could you re-merge the translation again? Also, in the new version, the 'Saved!' part that previously translated incorrectly is in English, and the Visit part (as in the image below) has not translated yet

![Translation issu 07012021](https://user-images.githubusercontent.com/73918009/103992637-00481d80-51c7-11eb-8980-5a2f4d6df60a.png)

**Comment by vincent-karuri** [comment]
@syedowaisali90 please verify if the translations are ok.
