### ISSUE TITLE
Issue with questions diplayed for Number of COVID-19 Patients 

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#645]
`The details of the patients in the Travel and contact exposure are displayed here, under the question about contact history with animal, but it is supposed to be under the Number of COVID-19 Patients section if we fill the number. I once tried to fill the information and deleted it, but the information was suddenly displayed as in the picture here.`

@ellyasafaa https://github.com/onaio/rdt-standard/issues/643#issue-754907962 please rephrase what this means in the context of the English form (images will be helpful)?

**Comment by ellyasafaa** [comment]
@vincent-karuri I explain in the picture below. Should you have any questions or need further explanation, please let me know.

![Display of Info Issue_SID](https://user-images.githubusercontent.com/73918009/100871546-0b76a200-34d3-11eb-8c97-f2fb92017ed7.png)

**Comment by vincent-karuri** [comment]
@ellyasafaa I'm not able to reproduce this. It doesn't look like any repeating groups were generated - the grey check mark would turn green if this was the case. 

Any reason for deleting the number after entering contact details? It doesn't seem like a natural end-user flow. 

Either way, you could share a video so I can understand the interaction here if this is still an issue.

**Comment by vincent-karuri** [comment]
Closing as outdated and not reproducible.
