### ISSUE TITLE
Get upright RDT images for display on the form

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#650]
@shivenbhatt1 as a note, the images are horizontally placed so they look a bit weird on the confirmation page.

_Originally posted by @vincent-karuri in https://github.com/onaio/rdt-standard/issues/615#issuecomment-734857926_

In reference to above, we'll need the RDT images in an upright position for easier display on the forms.

**Comment by vincent-karuri** [comment]
@mwkhan1983 this is the list of current images https://github.com/cjpark87/rdt-scan/tree/master/app/src/main/res/drawable-nodpi.

**Comment by mwkhan1983** [comment]
RDT images are now in upright position
