### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#655]
Translation issues
	a) Error message on Phone field when creating a Client is in English (Phone number cannot be less 0 /8-13 than 8 digits
	b) Gender on Client profile is in English 
	c) RDT Status status after scanning a RDT status successfully (Status: OK) and the Continue button

![Screenshot_20201208-161645_RDT Open Reader](https://user-images.githubusercontent.com/29072646/101618817-871ca580-3a23-11eb-87b2-687506596cb0.jpg)
![Screenshot_20201208-161921_RDT Open Reader](https://user-images.githubusercontent.com/29072646/101618823-897eff80-3a23-11eb-9178-9047efaa0c06.jpg)vin
![Screenshot_20201208-162254_RDT Open Reader](https://user-images.githubusercontent.com/29072646/101618828-8a179600-3a23-11eb-9263-9383496a5060.jpg)

**Comment by syedowaisali90** [comment]
@vincent-karuri I think the first and second point in this issue is already catered in #642

**Comment by vincent-karuri** [comment]
ok, please add what's missing.
