### ISSUE TITLE
Sync issues: Sync process took longer time and crashed

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#671]
When the first time we installed the APK, it will sync and take a longer time, about 1 - 2 mins. Usually more than 1 mins. While this process happened, users will get confused and start clicking anything, trying to find out what's going on. And during the process (if the sync process has not been finished), if we clicked another button, it will crash. Have sent videos to Wasim.

1st-time install > log in > syncing > taking longer time, clicking shipping preparation or plus button > crashed

Replicated on Samsung A50s Android 10, Redmi plus Android 8.1.0, and other phones. Will tell you other versions of the APK on the comments asap.

**Comment by ellyasafaa** [comment]
@vincent-karuri

**Comment by vincent-karuri** [comment]
@ellyasafaa does this crash happen on phones lower than Android 10?

**Comment by ellyasafaa** [comment]
@vincent-karuri I have tried it again with the latest version that Wasim sent (rdt-open-reader-covidIndonesia-v1.8.1-RC2-debug.apk) on Redmi plus Android 8 and Redmi Note 8 Android 9 and the crash did not happen. However, the sync process still took more than 1 min. Could we resolve that issue?

**Comment by vincent-karuri** [comment]
@ellyasafaa there are thousands of records being synced during fresh install so this is to be expected. As  @mwkhan1983 explained, this > 1 min sync time is only expected once during initial login and shouldn't be much of a problem subsequently.

**Comment by ellyasafaa** [comment]
@vincent-karuri okay noted. Will put the waiting time estimation in the user guideline.

**Comment by vincent-karuri** [comment]
@ellyasafaa is there a reason you need to wait until the entire sync process is complete?

**Comment by ellyasafaa** [comment]
@vincent-karuri The entire sync process should be complete to make sure all the data entried are existed in the apps, right? Like, to make sure all patients have been there, in the apps. I experienced a few times on the other apps, the data seems like losing because after we input those, the data was not there. Hopefully, it's not happened on this apps. On Android 8 and 9, while waiting for the sync, we are still able to entry the data without any crash happened, but for Android 10, if we click other part of the apk, it will crash. So, I think it is necessary just put some caution in the guideline regarding this matter if this can't be resolved. Also, most of the time, when the first time people opened the app and there was no data exist (there was nothing on the apps), they will think that the apps doesn't function well.

**Comment by vincent-karuri** [comment]
Ok, can we close this issue as being Android 10 specific?

**Comment by ellyasafaa** [comment]
@vincent-karuri Ok, sure
