### ISSUE TITLE
Add conditional save or save and conduct rdt logic

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#69]
The [save button](https://marvelapp.com/4b1bje0/screen/58413512) on the register patient form should save and exit to the register page if the patient does not qualify for an rdt test. Or save and launch the rdt test form if the patient qualifies.

Who qualifies for rdt testing is defined [here](https://docs.google.com/document/d/1rPK5U_NaEM7EMgfme_k-0V3j9qrRYT79b1SRjDS749M/)

Closes #36 

Partially fulfills #68

**Comment by allan-allay** [comment]
- [ ] Also adding additional patient registration form questions 

> Occupation
Gender
Was anyone else in the house diagnosed by RDT or slide with malaria in the last 3 months
Did you sleep under a treated mosquito net for the last week.
Was your house/compound sprayed in the last 3 months
That type of house do you live in (graded from 1-3 for local conditions)
Are you currently febrile [axillary temperature≥37.5°C]
Have you experience fever in the last 48 hours
Have you had chills in the last 48 hours  
Have you experienced severe malaise in the last 48 hours
Have you experienced headache in the last 48 hours
Have you vomited in the last 48 hours

**Comment by allan-allay** [comment]
> * [ ]  Also adding additional patient registration form questions
> 
> > Occupation
> > Gender
> > Was anyone else in the house diagnosed by RDT or slide with malaria in the last 3 months
> > Did you sleep under a treated mosquito net for the last week.
> > Was your house/compound sprayed in the last 3 months
> > That type of house do you live in (graded from 1-3 for local conditions)
> > Are you currently febrile [axillary temperature≥37.5°C]
> > Have you experience fever in the last 48 hours
> > Have you had chills in the last 48 hours
> > Have you experienced severe malaise in the last 48 hours
> > Have you experienced headache in the last 48 hours
> > Have you vomited in the last 48 hours
> 
> * [ ]  Have one Save button on the form

The above will be done in a separate issue
