### ISSUE TITLE
New Client Record: Change and additional information needed

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#703]
Hi Vincent,
We have adjusted the information needed with the Indonesian government record for several forms. I separated the issues based on the form. Please find the images below for your reference
![New Client Record](https://user-images.githubusercontent.com/73918009/103991391-28368180-51c5-11eb-8a8f-e3bf95127235.png)

In the new client record, we also need additional fields related to the information below:
![New Client Record 2](https://user-images.githubusercontent.com/73918009/103991482-4ef4b800-51c5-11eb-98cb-079a7d3abd97.png)

**Comment by ellyasafaa** [comment]
@vincent-karuri

**Comment by vincent-karuri** [comment]
@ellyasafaa what exactly goes into the address? Is the suggestion here to have an address field and still have a separate city and province field?

**Comment by vincent-karuri** [comment]
@ellyasafaa it's not clear what the follow-up question is asking. Could you add some more information and possibly rephrase it?

**Comment by vincent-karuri** [comment]
@ellyasafaa just wondering, are the questions about previous tests best asked during registration or when conducting a test?

**Comment by ellyasafaa** [comment]
> what exactly goes into the address? Is the suggestion here to have an address field and still have a separate city and province field?

@vincent-karuri Yes, to make us easier to categorize the address based on the city and province later on when we fetch the data. I think we need to make it a drop-down list for the city and the province in Indonesia for that.

>  it's not clear what the follow-up question is asking. Could you add some more information and possibly rephrase it? 

@vincent-karuri do you mean the last question? The follow-up to the latest COVID-19 test result?
So, if the result of the COVID-19 test was reactive or positive (depending on the test that s/he took), we would like to know what action was taken for that. So, the question would be: What is the follow-up action to the latest COVID-19 test result?

>  just wondering, are the questions about previous tests best asked during registration or when conducting a test?

@vincent-karuri well, this will refer to the patient who took the test before the patient registered in the Open Reader, so that's why we put that information there when the first time s/he registered. Our dilemma is if we put it when conducting a test and there is the case when the patient registered in the Open Reader has taken the 2nd test, the health worker needed to reinput all the information that actually has been recorded in the Open Reader. However, your point is correct. Could you put the questions in the symptom and history form by making a different page, but with an additional feature to autofill the information if the previous test conducted in the previous visit? Like, matching it with the date and the location perhaps? If the location (name of facility) is the same and the date chosen has the data about the test, then it will autofill the info.

**Comment by vincent-karuri** [comment]
@ellyasafaa please provide a list of provinces/cities.

**Comment by vincent-karuri** [comment]
@ellyasafaa I think auto-filling that data in the manner suggested is a more involved and complicated feature and would require a bit more time.

It's still not clear to me what is meant by:

```
Our dilemma is if we put it when conducting a test and there is the case when the patient registered in the Open Reader has taken the 2nd test, the health worker needed to reinput all the information that actually has been recorded in the Open Reader.
```

If the patient has taken a test before, it would show in the patient history section. We can also add an option to skip these set of questions as well if the CHW already knows that a previous test has been collected via the app.

**Comment by ellyasafaa** [comment]
> @ellyasafaa please provide a list of provinces/cities.

Please find the file for your reference @vincent-karuri 
I also requested in the travel and contact exposure (domestic travel) to be included the name of the province and cities. Please note that you should not make it the same as in this list, because the list of areas in that section is only for the area where local transmission happened.
[Uploading Download Daftar Seluruh Kelurahan, Kecamatan, Kabupaten, Province, Kode Pos, di Indonesia-excel.xlsx…]()


> @ellyasafaa I think auto-filling that data in the manner suggested is a more involved and complicated feature and would require a bit more time.
> 
> It's still not clear to me what is meant by:
> 
> ```
> Our dilemma is if we put it when conducting a test and there is the case when the patient registered in the Open Reader has taken the 2nd test, the health worker needed to reinput all the information that actually has been recorded in the Open Reader.
> ```
> 
> If the patient has taken a test before, it would show in the patient history section. We can also add an option to skip this set of questions as well if the CHW already knows that a previous test has been collected via the app.

@vincent-karuri The auto-filling part can be useful since it will help the health worker to determine the patient case category based on the test result and will be more convenient for the user because s/he only needs to open the symptom and history form once and get all information needed without any need to open other parts of the apk. And also, to be aware of the questions (previous test results questions), the user will have to experience these steps:

open the symptom and history > see the questions > ask the patient and realizing, for example, that she has taken the test before in the same health facility > back press > click patient history > searching for the previous test result > clicking the patient history form > seeing the result > back press > open the symptom and history form > skipping the question

My concerns are actually is related to that experience.

And actually, I do have concerns related to the patient history section. In each visit, it is possible here for someone to only get the screening question (what included in the symptom and history question) and will take the test on another day (for example the day after the screening process). If we fill only the symptom and history questions and take the test on another day, there will be 2 visits recorded on the app, right? If the visits recorded are still 2 visits, we can still remember it and check it without any problem. But, if there are a lot of visits recorded on the apk, it will be hard to see which visit gives us information on the test result, which visit gives us the information only on the screening process, or which visit gives us both information without clicking the visit there. Do you have any suggestions for this matter? Like giving any sign perhaps that tells us, Visit 1 only has the symptom and history information, Visit 2 only has the sample collection information,......... Visit 10 has complete information of both?

**Comment by ellyasafaa** [comment]
@vincent-karuri please note on the Excel sheets shared, there are city column and city name column. You should include both as one. The city column indicates the type of the city (In Indonesia, we have 2 types of it: City (Kota) and Regency (Kabupaten)) and the city name indicates the name. So, it is possible to have the same city name, but different city type, e.g. (Kabupaten) Bandung and (Kota) Bandung.

**Comment by vincent-karuri** [comment]
@ellyasafaa the suggestions are all valid but increase the scope quite a bit for this issue. I'd prefer we concentrate on the initial request about having the additional questions added.


We'd want to break out any other requests into different issues for further consideration / scoping if they become priorities.

**Comment by vincent-karuri** [comment]
@ellyasafaa the provinces link does not point to a document

**Comment by ellyasafaa** [comment]
> @ellyasafaa the suggestions are all valid but increase the scope quite a bit for this issue. I'd prefer we concentrate on the initial request about having the additional questions added.
> 
> We'd want to break out any other requests into different issues for further consideration / scoping if they become priorities.
I see. It will also take more time to do that. Let's have the questions added first

> @ellyasafaa the provinces link does not point to a document
@vincent-karuri 
Sorry about that. This is the document
[Download Daftar Seluruh Kelurahan, Kecamatan, Kabupaten, Province, Kode Pos, di Indonesia-excel.xlsx](https://github.com/onaio/rdt-standard/files/5802308/Download.Daftar.Seluruh.Kelurahan.Kecamatan.Kabupaten.Province.Kode.Pos.di.Indonesia-excel.xlsx)

**Comment by vincent-karuri** [comment]
@ellyasafaa there are over 8000 entries in the document. I don't think we can display all of these. Is there a way to summarise this information?

**Comment by ellyasafaa** [comment]
@vincent-karuri 
I think you will need the complete list and will make it like this
https://user-images.githubusercontent.com/73918009/104539491-3fa3bd80-5650-11eb-8d74-46d0f8cae022.mp4

or like this
https://user-images.githubusercontent.com/73918009/104540361-e2a90700-5651-11eb-8996-8be4a32f4f74.mp4

**Comment by vincent-karuri** [comment]
There are significantly fewer entries in the demo videos than the sheet that's attached. That's the summary I was requesting.

Otherwise, it's not possible to load 80,000 entries onto the form. If there's duplicated information, could that be removed and shared as an updated document?

**Comment by ellyasafaa** [comment]
@vincent-karuri In the document I sent you, there is sheet 5 that lists all city and regency that we need. I think you can use that as the reference. For Indonesia All sheet, I put all with the zip code and until village level (Desa), so it will be a lot.

So, the choice of city/regency will depend on the province we chose, right? All cities/regencies won't be appearing if we don't choose specifically for the province. That's how it works, correct?

**Comment by vincent-karuri** [comment]
@ellyasafaa we don't currently support dynamic loading of entries based on previous selections. This would mean loading all cities beforehand which would make for a terrible user experience. Can these fields be made manual for now?

**Comment by ellyasafaa** [comment]
@vincent-karuri Oh, I see. So, the manual field is the best option for now, isn't it?

**Comment by vincent-karuri** [comment]
@ellyasafaa yes it is

**Comment by ellyasafaa** [comment]
@ellyasafaa Ok, let's do that then
