### ISSUE TITLE
Pre-existing condition Form: Change and additional information needed

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#704]
![Pre-existing condition form](https://user-images.githubusercontent.com/73918009/103991622-85cace00-51c5-11eb-9663-76ee010c8426.png)

**Comment by ellyasafaa** [comment]
@vincent-karuri

**Comment by vincent-karuri** [comment]
@ellyasafaa does changing the step order so that the patient case category comes at the end of the form achieve the same thing as having a separate `Patient Case Category` form? i.e. do we really need a separate form for that?

**Comment by ellyasafaa** [comment]
> does changing the step order so that the patient case category comes at the end of the form achieve the same thing as having a separate `Patient Case Category` form? i.e. do we really need a separate form for that?

Well, actually they are the same. However, the last form would be about travel and contact exposure, and there will be a lot of information required to fill in the form, so this question will add the form to be longer. But, we can just rearrange the order of the form and put the question at the end of the form. So, the first could be the sign and symptom form > travel and contact exposure form > pre-existing condition form (the question about patient case category put at the end of the form). However, please note that the question of "Where is the assessment taking place?" and the name of the facility should always be in the first form.

**Comment by mwkhan1983** [comment]
@ellyasafaa @vincent-karuri In my opinion, patient case category question could be put at the end of 'travel and contact exposure' form.. Adding one question should not make the form longer unless there are several sub questions based on selection of category. New form for just one question does not make sense. Also pre-existing condition should be the first form to be filled as that is only logical

**Comment by vincent-karuri** [comment]
Ok, I think we can move the question to it's own step.

**Comment by ellyasafaa** [comment]
@syedowaisali90 the pregnant question is not back yet in the last APK that I got.

**Comment by ellyasafaa** [comment]
> @syedowaisali90 the pregnant question is not back yet in the last APK that I got.

@vincent-karuri @syedowaisali90 @mwkhan1983 Hi, is there any update on the question I asked?

**Comment by syedowaisali90** [comment]
@ellyasafaa this question is available in v1.9.0-RC6-CONFIGURABLE-RDT-SID-DEBUG.apk and in addition, it will be shown depending on condition like Patient age must be greater than 12 and gender must be female

**Comment by ellyasafaa** [comment]
@syedowaisali90 Thanks for the explanation. I tried to check i, but the question does not appear in the pre-existing form if I used Bahasa. Have checked it in English, it appeared.

**Comment by syedowaisali90** [comment]
@ellyasafaa let me check that

**Comment by syedowaisali90** [comment]
@ellyasafaa bug fixed in https://github.com/onaio/rdt-standard/pull/791
