### ISSUE TITLE
Sign and Symptom Form: Change and Additional Information Needed

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#705]
![sign and symptom field](https://user-images.githubusercontent.com/73918009/103991801-c4f91f00-51c5-11eb-8ad6-b96a16c7e768.png)

**Comment by ellyasafaa** [comment]
@vincent-karuri

**Comment by vincent-karuri** [comment]
@ellyasafaa are all the new questions dependent on the answer being `yes` for the preceding question i.e. should they only appear if the answer is `yes`?

**Comment by ellyasafaa** [comment]
@vincent-karuri No, Vincent. It doesn't depend on the preceding question answer. So, that was just about the order pf the questions.
