### ISSUE TITLE
Travel and Contact Exposure: Change and Additional Information Needed

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#706]
![Travel and contact exposure](https://user-images.githubusercontent.com/73918009/103991933-fbcf3500-51c5-11eb-99b3-4ca7b25f0c27.png)
![Travel and contact exposure 2](https://user-images.githubusercontent.com/73918009/103991947-02f64300-51c6-11eb-8252-060dfc1a72f7.png)
![Travel and contact exposure 3](https://user-images.githubusercontent.com/73918009/103991965-08538d80-51c6-11eb-9a6f-a3ba22df702c.png)
![Travel and contact exposure 4](https://user-images.githubusercontent.com/73918009/103991979-0c7fab00-51c6-11eb-94cf-6fa3e74ea61e.png)

**Comment by ellyasafaa** [comment]
@vincent-karuri

**Comment by ellyasafaa** [comment]
In case you need the list of transmission local area in Indonesia
[Transmission Local Area.xlsx](https://github.com/onaio/rdt-standard/files/5799123/Transmission.Local.Area.xlsx)

**Comment by vincent-karuri** [comment]
> In case you need the list of transmission local area in Indonesia
> [Transmission Local Area.xlsx](https://github.com/onaio/rdt-standard/files/5799123/Transmission.Local.Area.xlsx)

@ellyasafaa how is this supposed to be used?

**Comment by ellyasafaa** [comment]
@vincent-karuri 
I think you will need it for this question requested? So, make it like a dropdown list for the province and the city? This list is different from the one in the new client record
![Travel and contact exposure 2](https://user-images.githubusercontent.com/73918009/104321333-0f580400-5516-11eb-8031-ac11aef6ff89.png)

**Comment by vincent-karuri** [comment]
@ellyasafaa it's a very long list and I don't think it would be user-friendly as a dropdown. Is there a way to summarise the information there?

**Comment by ellyasafaa** [comment]
@vincent-karuri same as my answer in the new client record issue. Could you make it like that?

**Comment by vincent-karuri** [comment]
https://github.com/onaio/rdt-standard/issues/703#issuecomment-760768080
