### ISSUE TITLE
RDT Form: Change needed

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#707]
![RDT Form](https://user-images.githubusercontent.com/73918009/103992141-42249400-51c6-11eb-912a-465c52766300.png)

**Comment by ellyasafaa** [comment]
@vincent-karuri

**Comment by vincent-karuri** [comment]
We should add an extra field that asks for the type of test in that case and add the extra choices for antibody tests.

**Comment by ellyasafaa** [comment]
> We should add an extra field that asks for the type of test in that case and add the extra choices for antibody tests.

@vincent-karuri So, on the result page, you will add one more field that will ask about the type of the test, correct? We already have the question about the type of RDT if we enter RDT manually, and the type will also be detected after scanning, could we make it automatically? So, if the type chosen when they enter RDT manually or the type detected after scanning is A type, then the result adjusts to that type?

**Comment by vincent-karuri** [comment]
@ellyasafaa that information is not currently encoded in the RDT metadata. We can do this in future but for now it will have to be a manual selection.

**Comment by vincent-karuri** [comment]
@mwkhan1983 @ellyasafaa  could we get a list of RDT type (antigen/antibody)? 

We should populate this information [here](https://docs.google.com/spreadsheets/d/1P9yCzXHoy9Dz0_hp43GX_qpOc6Ayvz_D2TCReNVN_n4/edit#gid=0) to possibly have it automatically added as part of the metadata in future.

**Comment by ellyasafaa** [comment]
@vincent-karuri Okay noted. Have requested access to the sheet you sent

**Comment by vincent-karuri** [comment]
@ellyasafaa please work with @mwkhan1983 on this. I think all we'll need from your side is a list of the RDTs with their type, @mwkhan1983 will help with populating the sheet.

**Comment by mwkhan1983** [comment]
@vincent-karuri Please provide sheet access to @ellyasafaa and me. Thanks.
