### ISSUE TITLE
Unable to click RDT page

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#708]
There is the same problem as previously happened a long time ago that I am unable to click the RDT page before scanning (Which RDT? Scan barcode or Enter RDT Manually page) except the cross button on the upper left. I have tried to close the form and retried the same step to scan the RDT three times, but it still couldn't be clicked. I tried to click both the arrow and the text, but there is nothing happened. Have sent video to Wasim. This happened on Samsung A50s Android 10.

**Comment by ellyasafaa** [comment]
@vincent-karuri

**Comment by mwkhan1983** [comment]
https://user-images.githubusercontent.com/69383347/104132582-24ab2200-53a0-11eb-9839-3ae3360ee7cc.mp4

**Comment by vincent-karuri** [comment]
@ellyasafaa if this happened after a crash, please force close the app and try again.

**Comment by ellyasafaa** [comment]
But it happened without any crash happened before. So, if this happened again, the step should close the app and retry again. When will this case happen and why is that happening?

**Comment by vincent-karuri** [comment]
This happens when the app crashes an seemingly "re-launches" itself.

**Comment by vincent-karuri** [comment]
As noted before, the app does not currently have full support for Android 10 and I would recommend testing on phones with a lower version.

**Comment by ellyasafaa** [comment]
@vincent-karuri noted. I thought the Android 10 issue had been resolved

**Comment by vincent-karuri** [comment]
Someone on the team is working on this but it's not yet resolved.

**Comment by vincent-karuri** [comment]
@ellyasafaa could we close this as an intermittent issue that occurs after the app crashes and "relaunches" onto the profile page?

I've added a [fix](https://github.com/onaio/rdt-standard/pull/710) to ensure that when a crash happens, it closes out the app completely so we shouldn't see this behaviour in future.
