### ISSUE TITLE
Taking a longer time after scanning RDT and the screen is black

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#709]
When we are scanning the RDT and it succeeded, there would be a "Status: OK" page. And when I clicked continue, before the RDT type detected, it will take about 15 to 20 seconds to load it and during the process, the screen will be black. It happened on Samsung A50s Android 10 and Redmi plus Android 8.1.0. Could you make the process longer or do something with the black screen? Because if the screen is black, people will think that there is something wrong with the apk during the process.

Scan barcode RDT > Status: OK > continue > the screen black, waiting for about 15 - 20 secs > Confirmation page of RDT name and manufacturer

Have sent video to Wasim

**Comment by ellyasafaa** [comment]
@vincent-karuri

**Comment by mwkhan1983** [comment]
https://user-images.githubusercontent.com/69383347/104132650-908d8a80-53a0-11eb-8126-c90daa68316d.mp4

@vincent-karuri @ellyasafaa

**Comment by vincent-karuri** [comment]
@mwkhan1983 this lag is likely to a result of https://github.com/onaio/rdt-standard/issues/650.

Could you help with this?

**Comment by ellyasafaa** [comment]
@vincent-karuri @mwkhan1983 Hi, Thanks for getting the RDT Scan function back. Is there any update about this?

**Comment by mwkhan1983** [comment]
@ellyasafaa for now, we will have to live with this. We can train user accordingly.

**Comment by ellyasafaa** [comment]
@mwkhan1983 What causes that make this issue happened? How long will it take to solve this?

**Comment by mwkhan1983** [comment]
@vincent-karuri I have modified all images and they are now upright.

**Comment by vincent-karuri** [comment]
@mwkhan1983 thanks!

**Comment by mwkhan1983** [comment]
@ellyasafaa please confirm if this issue is resolved now or is it still happening?

**Comment by vincent-karuri** [comment]
@mwkhan1983 it requires more optimizations that will be part of the pr above.
