### ISSUE TITLE
App crashing when opening new registration form right after sync completed

### ISSUE THREAD

**Issue by mwkhan1983** [onaio/rdt-standard#732]
Please see the attached video for the crash.

https://user-images.githubusercontent.com/69383347/105810981-b71d0980-5fcd-11eb-8c7b-cce9082cf3fa.mp4

**Comment by mwkhan1983** [comment]
@ellyasafaa

**Comment by vincent-karuri** [comment]
@ellyasafaa Please provide the phone specs here?

**Comment by ellyasafaa** [comment]
@vincent-karuri Samsung A50s Android 10, LG v30 android 9

**Comment by vincent-karuri** [comment]
Is this video from the `LG v30 android 9`?

**Comment by ellyasafaa** [comment]
@vincent-karuri No, this one is from Android 10 Samsung A50s. The LG does not have any recording

**Comment by vincent-karuri** [comment]
A crash is expected from the samsung since it's Android 10 as discussed before. Are you able to get a recording for the LG?

**Comment by ellyasafaa** [comment]
@vincent-karuri Will do double-check with the LG user since I'm not holding the phone. Could we solve the Android-10-specific issues?

**Comment by vincent-karuri** [comment]
@ellyasafaa I think we can close this as related to Android 10?

**Comment by ellyasafaa** [comment]
@vincent-karuri Yes, Sure

**Comment by mwkhan1983** [comment]
closing this issue
