### ISSUE TITLE
App crashing when clicking RDT

### ISSUE THREAD

**Issue by mwkhan1983** [onaio/rdt-standard#733]
Please see the attached video. Replicated on Android 5 & 6

https://user-images.githubusercontent.com/69383347/105811241-24309f00-5fce-11eb-8d56-cd6b63acad23.mp4

**Comment by mwkhan1983** [comment]
@ellyasafaa

**Comment by vincent-karuri** [comment]
Note: related to API < 24.

**Comment by ellyasafaa** [comment]
@vincent-karuri What does that mean?

**Comment by vincent-karuri** [comment]
@ellyasafaa this is just a note for me, the issue is related to older devices.

**Comment by ellyasafaa** [comment]
@vincent-karuri Oh, I see

**Comment by ellyasafaa** [comment]
Is there any update on this?

**Comment by mwkhan1983** [comment]
Also closing this issue since we are not supporting Android versions 6 and below
