### ISSUE TITLE
App crashing - Sample collection form

### ISSUE THREAD

**Issue by mwkhan1983** [onaio/rdt-standard#734]
Please see attached Video. Replicated on Android 9. 

https://user-images.githubusercontent.com/69383347/105811923-234c3d00-5fcf-11eb-85e1-507f147b2409.mp4

**Comment by vincent-karuri** [comment]
Is OneScan installed on the device?

**Comment by vincent-karuri** [comment]
@ellyasafaa Is OneScan installed on the device?

**Comment by ellyasafaa** [comment]
@vincent-karuri Oh, sorry, the tester apparently forgot to install it. After installing it, it works fine. You can close the issue.

**Comment by mwkhan1983** [comment]
closing issue
