### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#736]
![Translation new issue](https://user-images.githubusercontent.com/73918009/105820683-754f8b80-5fec-11eb-8a16-55fd045541ff.png)

**Comment by ellyasafaa** [comment]
@vincent-karuri

**Comment by vincent-karuri** [comment]
Translation for this section is not currently supported due to it's dynamic nature.

We'd have to hard-code the values.

**Comment by ellyasafaa** [comment]
@vincent-karuri Previously this section can be translated as far as I can remember. So, how long will it take to hard-code the values?
