### ISSUE TITLE
Missing Information on New Client Record

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#737]
![New client record new issue](https://user-images.githubusercontent.com/73918009/105820820-a29c3980-5fec-11eb-8b98-e4f0d841d1f7.png)
![New Client record new issue 2](https://user-images.githubusercontent.com/73918009/105820825-a465fd00-5fec-11eb-86b1-ba8b48166fe8.png)

**Comment by ellyasafaa** [comment]
@vincent-karuri

**Comment by ellyasafaa** [comment]
@vincent-karuri  Sorry, the 2nd picture should be: It will need one additional field: Government ID address question, before the Government ID province and after the email address.

**Comment by vincent-karuri** [comment]
@ellyasafaa sorry this is not clear, what should the question be?

**Comment by ellyasafaa** [comment]
@vincent-karuri my apologies, it should be: 
Government ID address (located before the Gov ID province question)

**Comment by vincent-karuri** [comment]
How is government ID address different from the province and city questions? Don't those form the address?

**Comment by vincent-karuri** [comment]
And if we're making that change will it also be necessary to make a similar change to domicile address?

**Comment by ellyasafaa** [comment]
@vincent-karuri Usually, Indonesian will fill the address with only the street name, not specifically with the city and province. So the province and city fields will validate the address that has been inputted. And yes, it will apply to the domicile address as well.

**Comment by vincent-karuri** [comment]
Ok, can we name that `Government ID street address` then for clarity?

**Comment by ellyasafaa** [comment]
@vincent-karuri Sure, I'll translate it in a different way though.
