### ISSUE TITLE
RDT Menu Misinformation

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#738]
![RDT menu](https://user-images.githubusercontent.com/73918009/105820941-ce1f2400-5fec-11eb-9552-408935ab7403.png)

**Comment by ellyasafaa** [comment]
@vincent-karuri

**Comment by ellyasafaa** [comment]
@vincent-karuri @syedowaisali90 Hi, just checking this on the latest apk Wasim sent me. Thank you for moving the antibody part as requested, but can we make it not required? If the result is nonreactive, it is not necessary for them to fill in the antibody question. However, it will be required if the result is reactive

![WhatsApp Image 2021-02-02 at 7 24 24 PM](https://user-images.githubusercontent.com/73918009/106600283-c4696380-658c-11eb-97a1-711bb97bc531.jpeg)

**Comment by syedowaisali90** [comment]
@ellyasafaa could you create a separate issue for this.
cc @vincent-karuri

**Comment by ellyasafaa** [comment]
@syedowaisali90 will do
