### ISSUE TITLE
Unable to Click Sample Barcode Scan Issue

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#743]
Hi, I found the same issue as we had before: unable to click page issue on Redmi 5 Plus, Android 7.1.2. Attached the video. Have clicked both arrows and the text.

https://user-images.githubusercontent.com/73918009/105944181-61139900-6095-11eb-869a-27aa7ad11779.mp4

**Comment by ellyasafaa** [comment]
@vincent-karuri @mwkhan1983

**Comment by vincent-karuri** [comment]
What happens when you close out the app?

**Comment by vincent-karuri** [comment]
@ellyasafaa could you confirm if closing out the app fixes this? Also, is this the latest update? This issue should've been resolved in the latest version.

**Comment by ellyasafaa** [comment]
@vincent-karuri Yes, this is the latest apps that has been installed. Will contact the tester and get back to you soon to clarify, but I guess yesterday he said on the call that after closing, it works fine.

**Comment by ellyasafaa** [comment]
What can cause that to happen again in the latest version of the apps?

**Comment by vincent-karuri** [comment]
@ellyasafaa I have not been able to reproduce this on the latest version yet.

**Comment by ellyasafaa** [comment]
@vincent-karuri It is also not replicated on the device using Android 8 and 9 that I currently have, but the tester using Android 7 said it replicated again on his phone. Another device using Android 7 will arrive in the office on Wed at the earliest. Will do a recheck again after I have the device.

**Comment by mwkhan1983** [comment]
@ellyasafaa is there an update on this?

**Comment by mwkhan1983** [comment]
@ellyasafaa is this still an issue or can we close this?

**Comment by ellyasafaa** [comment]
@mwkhan1983 Apologies for missing this. All GitHub messages go to the trash folder in my email, so I don't get them on time. I couldn't replicate this again, so we can close this for now.

**Comment by mwkhan1983** [comment]
closing
