### ISSUE TITLE
Issues on Sample Collection Form

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#746]
Please kindly find the image below for your reference. If you need to break down the issue and create new issues for these, please tag me on the issue.

![EoA_Sample Collection Form_1](https://user-images.githubusercontent.com/73918009/106087641-03e01c00-6157-11eb-8fef-2fb5a95317f6.png)
![EoA_Sample Collection Form_2](https://user-images.githubusercontent.com/73918009/106087647-05114900-6157-11eb-99d1-a51857439ce9.png)
![EoA_Sample Collection Form_3](https://user-images.githubusercontent.com/73918009/106087648-05a9df80-6157-11eb-8936-4b6f207d6324.png)
![EoA_Sample Collection Form_4](https://user-images.githubusercontent.com/73918009/106087651-06db0c80-6157-11eb-9cc7-6cb6a061b1a8.png)
![EoA_Sample Collection Form_5](https://user-images.githubusercontent.com/73918009/106087640-02165880-6157-11eb-9342-b4c91c119fb6.png)

**Comment by ellyasafaa** [comment]
@vincent-karuri @mwkhan1983

**Comment by ellyasafaa** [comment]
There is an issue related to location hierarchy here. Will put on separate issue.

**Comment by vincent-karuri** [comment]
@ellyasafaa I don't know what `Testing booking slot` is. Shiven said is was requested.

Could we refine the message on the last page? It seems repetitive to say `Safely store under safe and secure conditions`.

**Comment by ellyasafaa** [comment]
@vincent-karuri Oh okay. I think the Testing Book slot and the GSI Sample ID should be erased at this point.

The last page of information is to remind the health worker for storing the specimen safely in the storage. So the flow would be:
Open sample collection form > Follow the instruction, start from obtaining specimen using approved methods > after taking the specimen they should safely store it in the transport tube > scan the sample barcode > confirm the patient information > lastly they will store it in a bigger storage

So, the information on the last page will instruct them to safely store in a bigger storage, and we choose the sentence like that

**Comment by vincent-karuri** [comment]
@ellyasafaa modifying the UI around the `Name of sampler` text can move to a separate issue.
