### ISSUE TITLE
Issues on Other Clinical Data Form

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#748]
Please kindly find the image below for your reference. If you need to break down the issue and create new issues for these, please tag me on the issue.

![EoA_Other Clinical Data Form](https://user-images.githubusercontent.com/73918009/106087847-6cc79400-6157-11eb-8889-c623e4deaf6a.png)
![EoA_Other Clinical Data Form_2](https://user-images.githubusercontent.com/73918009/106087840-6afdd080-6157-11eb-93f9-33f611adf517.png)

**Comment by ellyasafaa** [comment]
@vincent-karuri @mwkhan1983

**Comment by vincent-karuri** [comment]
@ellyasafaa what is the expected format?

**Comment by ellyasafaa** [comment]
@vincent-karuri 
Leukocyte: 400 to 108,000  per microliter
lymphocyte 90 to 52,000  per microliter
platelet: 13,000 to 4,000,000  per microliter
