### ISSUE TITLE
Issues on Symptom and History Form

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#749]
Please kindly find the image below for your reference. If you need to break down the issue and create new issues for these, please tag me on the issue.

![EoA_Symptom and History Form_1](https://user-images.githubusercontent.com/73918009/106087949-97195180-6157-11eb-92c9-8173c6508ac3.png)
![EoA_Symptom and History Form_2](https://user-images.githubusercontent.com/73918009/106087950-97b1e800-6157-11eb-946d-a0a8c31182d4.png)
![EoA_Symptom and History Form_3](https://user-images.githubusercontent.com/73918009/106087941-954f8e00-6157-11eb-82d8-134f67a333c9.png)

**Comment by ellyasafaa** [comment]
@vincent-karuri @mwkhan1983

**Comment by vincent-karuri** [comment]
@ellyasafaa please specify the exact format expected e.g. this should only allow text characters or this should only allow digits where the digits are > x and < y.

If there are other issues in other forms, please create them as separate issues and point out the same to avoid ambiguity.

**Comment by ellyasafaa** [comment]
@vincent-karuri 
Body temperature should only allow digits: 35 - 45
Apart from the body temperature and contact's phone number, all short answer field should only allow for the text in the Symptom and History section:
- Enter additional health issues
- International country of travel
- International city of travel
- Local area province
- Local area city of travel
- Detail of each patient in the travel and contact exposure form

**Comment by syedowaisali90** [comment]
@ellyasafaa I'm a bit confused in the first image so do I need to show this question (Does the patient have a history with urinary or kidney disease?) only when select no on this question (Does the patient have chronic kidney disease?). could you eleborate more

**Comment by ellyasafaa** [comment]
@syedowaisali90 Thanks for asking. I think we can just erase one question because the answer will be connected. _Does the patient have a history with urinary or kidney disease?_ can be deleted. My apologies for the unclear description.

**Comment by ellyasafaa** [comment]
@syedowaisali90 Hi just checked about the body temperature field, it seems the validation number hasn't been set in the latest APK that I got.

**Comment by syedowaisali90** [comment]
@ellyasafaa I think if you asking about this then it's already merged in master https://github.com/onaio/rdt-standard/blob/261b080846e845c196a8d542201077454d8fd22c/rdt-open-reader/src/covidIndonesia/assets/json.form/patient-diagnostics-form.json#L541-L566
and if it's not about this then could you share that you have

**Comment by ellyasafaa** [comment]
@syedowaisali90 in this version v1.9.0-rc6-configurable-rdt-sid-debug, is it already merged in that APK?

**Comment by syedowaisali90** [comment]
@ellyasafaa not sure @vincent-karuri can help on this.

**Comment by vincent-karuri** [comment]
@syedowaisali90 please confirm in master.

**Comment by syedowaisali90** [comment]
@vincent-karuri I have checked. It's available in master but not this APK v1.9.0-rc6-configurable-rdt-sid-debug

**Comment by ellyasafaa** [comment]
@syedowaisali90 does the range allow decimal as well?

**Comment by syedowaisali90** [comment]
> @syedowaisali90 does the range allow decimal as well?

@ellyasafaa yes

**Comment by syedowaisali90** [comment]
@ellyasafaa I haved fixed the fever validation bug in https://github.com/onaio/rdt-standard/pull/789

**Comment by ellyasafaa** [comment]
@syedowaisali90 great! what is the decimal separator for that? comma or point? Just wanna make sure in the manual that we have it is correctly written

**Comment by syedowaisali90** [comment]
@ellyasafaa point. like **33.5**

**Comment by ellyasafaa** [comment]
@syedowaisali90 Well noted, thanks!
