### ISSUE TITLE
Auto-detect RDT Type from DeviceDefinition

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#760]
To detect whether an RDT is antigen/antibody based, we need to encode this information in the FHIR resource and extract it into the form.

**Comment by vincent-karuri** [comment]
@ellyasafaa @mwkhan1983 we'll need an extra column that records the RDT type in this [doc](https://docs.google.com/spreadsheets/d/1P9yCzXHoy9Dz0_hp43GX_qpOc6Ayvz_D2TCReNVN_n4/edit#gid=0).

**Comment by mwkhan1983** [comment]
@yussin-hidayat when RDT type is antibody, RDT result options are `Reactive` and `Non-Reactive`.  When "Reactive" is selected, it should show IgG and IgM but NOT when "Non-Reactive" is selected. Currently, it shows the follow-up question in any case, that is, whether `Reactive` is selected or `Non-Reactive` is selected.
