### ISSUE TITLE
Change for the SID Official Trademark on Home screen page

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#772]
![Homescreen issue](https://user-images.githubusercontent.com/73918009/106615660-3f3b7a00-659f-11eb-8479-507bd601ad3f.png)

**Comment by ellyasafaa** [comment]
@vincent-karuri @mwkhan1983 the logo will be necessary as our identity because we will use it in a broader scope

**Comment by mwkhan1983** [comment]
@ellyasafaa please provide SID logo

**Comment by ellyasafaa** [comment]
@mwkhan1983 please find the file for your reference
![Logo SID](https://user-images.githubusercontent.com/73918009/106898171-6ec8be80-6726-11eb-9580-9c8aa972240c.jpg)

**Comment by vincent-karuri** [comment]
We can change the text. I think I'd want to  discuss with management before adding the logo.

**Comment by ellyasafaa** [comment]
For reference:
![developed by](https://user-images.githubusercontent.com/73918009/110578158-bb287380-8196-11eb-838c-d8413c758a81.png)
