### ISSUE TITLE
Change for antibody question on RDT menu

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#773]
Hi, just checking this on the latest apk Wasim sent me. Thank you for moving the antibody part as requested, but can we make it not required? If the result is nonreactive, it is not necessary for them to fill in the antibody question. However, it will be required if the result is reactive

![WhatsApp Image 2021-02-02 at 7 24 24 PM](https://user-images.githubusercontent.com/73918009/106616144-c983de00-659f-11eb-997d-866620fdd6f3.jpeg)

**Comment by ellyasafaa** [comment]
@vincent-karuri @syedowaisali90

**Comment by mwkhan1983** [comment]
@ellyasafaa antibody question will either be required or non-required. It cannot be both

**Comment by syedowaisali90** [comment]
@ellyasafaa need your input https://github.com/onaio/rdt-standard/issues/773#issuecomment-772339904

**Comment by ellyasafaa** [comment]
@syedowaisali90 @mwkhan1983 I think just keep it required then since it can be skipped if it is not required. You can close this issue.

**Comment by ellyasafaa** [comment]
@mwkhan1983 @syedowaisali90 Sorry, before deciding with that my previous comment. Just wanna confirm, can we make the question appear only if the result is reactive?

**Comment by syedowaisali90** [comment]
@ellyasafaa yes, we can show the Antibody question only if the result is Reactive and hide on NonReactive.

cc: @mwkhan1983

**Comment by ellyasafaa** [comment]
@syedowaisali90 And the Antibody question can be required, right? Let's do that.
