### ISSUE TITLE
Next Page UX Issue

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#774]
![Page information issue](https://user-images.githubusercontent.com/73918009/106616673-62b2f480-65a0-11eb-9ebd-3bd225529c14.png)

**Comment by ellyasafaa** [comment]
@vincent-karuri @mwkhan1983

**Comment by mwkhan1983** [comment]
@ellyasafaa there is a search function for that. You need to refine results using search.

**Comment by ellyasafaa** [comment]
@mwkhan1983 yes, I am aware of the function. However, since this app has no sorting feature that allowing users to sort the patient based on the result or based on the time we inputted or based on the alphabet, the current patient will be put in the last page. It will be really difficult if we want to track the patient based only on the date or else. So, it will be really helpful I think if we can at least add the sorting page and create the next page manually. I believe this kind of practice will absolutely happen in the field.

**Comment by mwkhan1983** [comment]
@ellyasafaa I think I understood the problem. New patients added ends up at the end of the list. 
@vincent-karuri I believe it is possible to sort the list so that new patients added gets displayed on first page. Right?

**Comment by vincent-karuri** [comment]
@ellyasafaa you can search for the patient you registered by name if that's the use case here.

**Comment by ellyasafaa** [comment]
@vincent-karuri So, the practice would be:
You will test many patients, more than 50 a day, and you will absolutely put all of them in the apk. The health worker will do screening task, asking those questions on the symptom and history form and do the testing separately, for sure. Absolutely, we want to use the apk to make our task is more convenient, right? But only the search feature won't help because it will only filter to the specific name, in individual case, and that's not the case that will happen. It will be really difficult for someone to memorize more than 50 names in a day and it will be more convenient if the patient can be sorted based on the date and to set manually for the page that we wanna go into would be really helpful. Not only based on the date, if we could get the sorting feature based on the result it would be very helpful. These features are important.

**Comment by vincent-karuri** [comment]
@ellyasafaa I'm not sure I understand the flow here. Isn't the patient available when taking a test? Is it not possible to ask them for their name at that point to retrieve their record?

**Comment by ellyasafaa** [comment]
@vincent-karuri they will not line up, the health worker who will call their name and then the patient will come to the area where the test conducted or the screening conducted.

**Comment by ellyasafaa** [comment]
@vincent-karuri Hi, is there any update on this?

**Comment by mwkhan1983** [comment]
@ellyasafaa Anu mentioned to sort the list based on the visit date. But this list is of registered patients and NOT linked to visits. I asked earlier that can we sort the list based on time the client is registered? So any new client registered will show up at the top. Please confirm.

**Comment by ellyasafaa** [comment]
@mwkhan1983 Can we do both options?

**Comment by mwkhan1983** [comment]
@ellyasafaa sorting by visit date is not possible. As I mentioned list of registered patients and NOT linked to visits. When it is not linked to visits, it cannot be sorted based on visit date. 
Please confirm if we want to sort based on date when patient is registered in descending order (latest registered on top).

**Comment by ellyasafaa** [comment]
@mwkhan1983 Yes, please kindly proceed with that.
