### ISSUE TITLE
Changes in New Client Record

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#778]
![new client record issue](https://user-images.githubusercontent.com/73918009/106833624-6e004000-66c6-11eb-8443-b590706d00c3.png)

@vincent-karuri @syedowaisali90

**Comment by syedowaisali90** [comment]
@ellyasafaa about your line spacing concern, we can add a spacer between questions but on a client-side, we don't have an option to remove the padding from a text field.

cc: @vincent-karuri

**Comment by ellyasafaa** [comment]
@syedowaisali90 Just wanna clarify, the padding is the space between the answer line and the answer text, right? So, you can remove the space that was too far between the question and answer related to that question, and add a spacer between the answer from the previous question to the next question, right?

**Comment by syedowaisali90** [comment]
@ellyasafaa sorry for the delay, 5th feb was a holiday in Pakistan. Actually, we don't have any provided option on the client-side to adjust the margin/padding from the EditText. Even there is no margin or padding has been set from native-form so the spacing you have seen it's Android default EditText background.

We have three options.

- We need to create PR in native-form to add a property for margin/padding.
- We need to create an EditTextFactory extension on the client-side.
- We can remove the labels and use EditText placeholder as a label.

cc: @vincent-karuri

**Comment by ellyasafaa** [comment]
@syedowaisali90 what is the best option for doing this? I see that option number 3 wouldn't be the recommended one, because we have already that type of question, right? Like for the Date question, but the users end up being confused whether they have to fill it or not.

**Comment by syedowaisali90** [comment]
@ellyasafaa you right option 3 wouldn't be the best option so I'm going to work on option 1 which is best for now and more extensible in the future.

P.S Thanks @vincent-karuri for the suggestion.

**Comment by ellyasafaa** [comment]
@syedowaisali90 Thank you, let's do that.

**Comment by ellyasafaa** [comment]
@syedowaisali90 Hi, is there any update on this?

**Comment by syedowaisali90** [comment]
@ellyasafaa it's almost done just waiting that some other flavor test cases are failing I'm trying to figure that issue.
