### ISSUE TITLE
Travel and Contact Exposure Form Change Needed

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#782]
Could we allow space for that 'only alphabetic characters are allowed' field? Because there are several provinces and cities that have two words.

![Screenshot_20210210-120830_RDT Open Reader](https://user-images.githubusercontent.com/73918009/107468160-16684580-6b9a-11eb-920e-4e31024637ac.jpg)

@mwkhan1983 @vincent-karuri

**Comment by ellyasafaa** [comment]
Hi, the same case also in this field that needs to be corrected. Here is the pre-existing condition form.
![Screenshot_2021-02-15-14-49-04-981_io ona diagnostics rdt configurable id](https://user-images.githubusercontent.com/73918009/108007127-c53fd200-702f-11eb-875d-411466a56b3e.png)

**Comment by ellyasafaa** [comment]
@mwkhan1983 @syedowaisali90 Hi, is there any update on this?

**Comment by syedowaisali90** [comment]
@ellyasafaa it's not started yet actually I'm trying to close pending issues that need to close on priority
