### ISSUE TITLE
Crash when clicking Sample Collection menu

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#784]
Oppo A5s Android 8.1.0

https://user-images.githubusercontent.com/73918009/107493098-d61bbe00-6bbf-11eb-8237-11e90803aee5.mp4

@vincent-karuri @mwkhan1983

**Comment by mwkhan1983** [comment]
@syedowaisali90 can you please try and replicate this issue? You may use emulator to configure same OS version

**Comment by syedowaisali90** [comment]
@ellyasafaa could you share crash logs.

**Comment by syedowaisali90** [comment]
@ellyasafaa is the application got crashed on the first time installed or every time.

**Comment by ellyasafaa** [comment]
@syedowaisali90 my apologies for the late reply. It is not happening every time but often happened. Not in the first time installed.

**Comment by ellyasafaa** [comment]
@syedowaisali90 Hi, is there any update on this?

**Comment by syedowaisali90** [comment]
@ellyasafaa I have fixed the crash in the above PR but I tried too many times to reproduce it but it's not happened.
