### ISSUE TITLE
Adding One New Test in New Client Record Form

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#787]
Currently in Indonesia, we have another test called GeNose C19, the result will be positive or negative. Could we add that to the type of test question below?

![Screenshot_2021-02-16-08-32-49-359_io ona diagnostics rdt configurable id](https://user-images.githubusercontent.com/73918009/108008233-7f383d80-7032-11eb-8f05-a2b436e46de7.png)

@mwkhan1983 @vincent-karuri @syedowaisali90

**Comment by ellyasafaa** [comment]
@syedowaisali90 @mwkhan1983 @vincent-karuri Hi, is there any update on this?

**Comment by syedowaisali90** [comment]
@ellyasafaa new test question added https://github.com/onaio/rdt-standard/pull/792
