### ISSUE TITLE
Critical issue on the release version

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#799]
Hi, I've performed the UAT and there are some critical points that need to be fixed before it released because will end up disturbing the field data collection process:
- Please kindly remove the Medical record ID as required. I think I have addressed this several times, it has been fixed, right?
- All text-related answer fields in symptom and history should allow spaces. Please kindly fix that.
- Please remove the onset date on the Sign and Symptom form as required. Later we will enhance the question, but for now, just don't make it required.
- Please show the post-partum and pregnant question in the release version
- The test taker/name of sampler (Nama Pengambil Sampel) in sample collection form should not be automatically entered (The issue has been solved, right?), and there is one additional column for test taker ID below that question (ID Pengambil Sampel)
- Please kindly move the doctor's name and doctor's phone number to symptom and history form, with additional Doctor's ID/ID Petugas Pemeriksa and Phone Number question.

There are also some enhancement features that need to be solved, which will be opened in separate issues, but the critical points above should be addressed in this release. The documentation of the UAT will be sent by email.

@mwkhan1983 @syedowaisali90 @vincent-karuri

**Comment by ellyasafaa** [comment]
Also, please kindly put all fixed issues that have been created by all of you in this release. Seems like the beta apps is not integrated with the current fixed issues?

**Comment by ellyasafaa** [comment]
One more thing left, in Media type, please add one more answer option: No media (Dry swab) option. My apologies for this, the option is really important. Our additional requests are related to moving questions, adding questions, and removing required questions because the rest of the issues have been pointed out before and should have been fixed. I believe it can happen faster, right?

**Comment by vincent-karuri** [comment]
@ellyasafaa could you specify from which form we are moving `the doctor's name and doctor's phone number` and where within the `symptom and history form` is should be moved to?

**Comment by vincent-karuri** [comment]
```
The test taker/name of sampler (Nama Pengambil Sampel) in sample collection form should not be automatically entered (The issue has been solved, right?), and there is one additional column for test taker ID below that question (ID Pengambil Sampel)
```

does this mean that this should be converted into a free-text field that is not pre-filled?

**Comment by ellyasafaa** [comment]
> ```
> The test taker/name of sampler (Nama Pengambil Sampel) in sample collection form should not be automatically entered (The issue has been solved, right?), and there is one additional column for test taker ID below that question (ID Pengambil Sampel)
> ```
> 
> does this mean that this should be converted into a free-text field that is not pre-filled?

Yes, as we discussed before

**Comment by vincent-karuri** [comment]
@ellyasafaa please also address this https://github.com/onaio/rdt-standard/issues/799#issuecomment-784205321

**Comment by ellyasafaa** [comment]
> @ellyasafaa could you specify from which form we are moving `the doctor's name and doctor's phone number` and where within the `symptom and history form` is should be moved to?

![klik tombol ini hingga berwarna hijau untuk memunculkan detail pertanyaan kontak (tracing kontak) (16)](https://user-images.githubusercontent.com/73918009/108873059-67ae1580-762d-11eb-9756-3b02e7923bd5.png)

**Comment by ellyasafaa** [comment]
@vincent-karuri apologies for taking a long time, editing the image first. Please let me know if it is still not clear.

**Comment by mwkhan1983** [comment]
@ellyasafaa I think when we add No media option then Media expiration date and Media lot number shouldn't be there. Please confirm

**Comment by ellyasafaa** [comment]
@mwkhan1983 The expiration date will be automatically 3 days after the test day

**Comment by mwkhan1983** [comment]
`@mwkhan1983 The expiration date will be automatically 3 days after the test day`

@ellyasafaa  This is a totally different requirement.

I am not sure if my question in comment https://github.com/onaio/rdt-standard/issues/799#issuecomment-784994464 is understood correctly.

**Comment by ellyasafaa** [comment]
@mwkhan1983 Apologies for the unclear explanation. Yes, there will be no media, but Dr. Anu suggested that the part of the media expiration date would be set automatically in 3 days.

**Comment by vincent-karuri** [comment]
> > @ellyasafaa could you specify from which form we are moving `the doctor's name and doctor's phone number` and where within the `symptom and history form` is should be moved to?
> 
> ![klik tombol ini hingga berwarna hijau untuk memunculkan detail pertanyaan kontak (tracing kontak) (16)](https://user-images.githubusercontent.com/73918009/108873059-67ae1580-762d-11eb-9756-3b02e7923bd5.png)

@ellyasafaa is the health worker ID/phone number replacing the doctor's ID/phone number.

CC @syedowaisali90

**Comment by ellyasafaa** [comment]
@vincent-karuri Yes, because the health worker can cover more general scope of health worker. So, if the test is taken by a doctor or vaccinator, or even a trained midwife, it's still relevant.

**Comment by mwkhan1983** [comment]
@ellyasafaa Please provide translations in transifex for

Sampler ID
Sampler's phone number
Name of health worker
Health worker ID
Health worker phone number

**Comment by syedowaisali90** [comment]
@ellyasafaa should i mark the `sampler phone number` field and `health worker phone number` field mandatory.

**Comment by ellyasafaa** [comment]
> @ellyasafaa should I mark the `sampler phone number` field and `health worker phone number` field mandatory.

Yes, please.

> @ellyasafaa Please provide translations in transifex for
> 
> Sampler ID
> Sampler's phone number
> Name of health worker
> Health worker ID
> Health worker phone number

@mwkhan1983 apologies for the late reply. In the last 3 days, I conducted training here in Indonesia, so I didn't catch up with this matter in a timely manner. Will check on transifex. Thank you

**Comment by ellyasafaa** [comment]
@mwkhan1983 @syedowaisali90 Hi, the onset date on the Sign & Symptom Form still required.

**Comment by vincent-karuri** [comment]
@ellyasafaa is the date supposed to be mandatory or should it be optional. It was made optional as was asked in the issue description https://github.com/onaio/rdt-standard/issues/799#issue-813950999.

**Comment by ellyasafaa** [comment]
should be optional. I checked with the last apps that I have, it was still mandatory

**Comment by ellyasafaa** [comment]
> @mwkhan1983 @syedowaisali90 Hi, the onset date on the Sign & Symptom Form still required.

if you get confused, this comment is FYI comment.
