### ISSUE TITLE
Language consistency

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#802]
Bahasa and English are not consistent when we switch/change the language. When changed to English, there are still some pages in Bahasa and vice versa. This includes the validation error message that mostly still in English.

**Comment by vincent-karuri** [comment]
Please note down all the sections individually. These can be fixed in a subsequent release.

**Comment by mwkhan1983** [comment]
[images.zip](https://github.com/onaio/rdt-standard/files/6042407/images.zip)
Attached instances where validation messages are in English but should have been in Bhasa.
I didn't find instances where language is english but text appearing in Bhasa. 

@ellyasafaa 
Please share all language inconsistencies besides what I have attached here by Monday, 1st March

**Comment by ellyasafaa** [comment]
In addition to your attachment above. Thank you

![klik tombol ini hingga berwarna hijau untuk memunculkan detail pertanyaan kontak (tracing kontak) (17)](https://user-images.githubusercontent.com/73918009/109463160-238c9c00-7a97-11eb-8faf-c381358f5956.png)

**Comment by syedowaisali90** [comment]
@ellyasafaa could you double on Transifex translation because some of the keys that need to be checked are properly translating or not like there is no translation found of `Other Clinical Data` form.

**Comment by ellyasafaa** [comment]
Apologies, one more thing left. The Yes and No option should be in Bahasa. I think I have translated the Yes/No strings several times. Is it not included here?

![Screenshot_20210303-174916_RDT Open Reader](https://user-images.githubusercontent.com/73918009/109795613-b705ce80-7c49-11eb-8547-1b9af8e079a7.jpg)

**Comment by ellyasafaa** [comment]
> @ellyasafaa could you double on Transifex translation because some of the keys that need to be checked are properly translating or not like there is no translation found of `Other Clinical Data` form.

What do you mean by double? double checked?

**Comment by syedowaisali90** [comment]
@ellyasafaa sorry, yes i mean double check

**Comment by ellyasafaa** [comment]
I have double-checked the translation there, apart from the resource: rdt-open-reader..json.form/patient-diagnostics-form.json (master), everything has been translated, but I don't find any string of: value cannot be this low.

**Comment by ellyasafaa** [comment]
I couldn't find also the email validation error message string on the patient registration form resource.

**Comment by ellyasafaa** [comment]
Also, the phone number validation error message on new client record is still in English

**Comment by syedowaisali90** [comment]
@ellyasafaa did you check the latest build?

**Comment by ellyasafaa** [comment]
@syedowaisali90 Yes, I have checked it. I have sent the translation info for the other clinical data form to Wasim via email. The phone number validation error message have been corrected. Thanks! However, I need a translation for the account disabled message after the session expired. Could you give me the string for that to be translated? And also the yes or no in below message:

> Apologies, one more thing left. The Yes and No option should be in Bahasa. I think I have translated the Yes/No strings several times. Is it not included here?
> 
> ![Screenshot_20210303-174916_RDT Open Reader](https://user-images.githubusercontent.com/73918009/109795613-b705ce80-7c49-11eb-8547-1b9af8e079a7.jpg)

**Comment by syedowaisali90** [comment]
@ellyasafaa Hey these are the strings of the account disabled popup.

https://github.com/OpenSRP/opensrp-client-core/blob/fec5e95c5c12a0f0688f53555f51b0eab18eb8c1/opensrp-app/res/values/strings.xml#L388-L389

and these are for yes and no

https://github.com/onaio/rdt-standard/blob/b3b30209c127fe584a22b1e0c0d49d9e717c28a8/rdt-open-reader/src/main/res/values/strings.xml#L64-L65

**Comment by ellyasafaa** [comment]
@syedowaisali90 I think I have translated the yes and no on Transifex this morning. There are some other strings that I translated too, but will do translate strings that you sent above. Have you gotten the value validation error message translation yet from Wasim? I have translated it manually too.

**Comment by ellyasafaa** [comment]
For account disabled popup
```
    <string name="account_disabled">Akun Dinonaktifkan</string>
    <string name="account_disabled_logged_off">Anda telah keluar karena akun Anda telah dinonaktifkan. Silakan hubungi administrator Anda.</string>
```

For Yes/No
```
 <string name="yes">Ya</string> 
 <string name="no">Tidak</string> 
```
