### ISSUE TITLE
Patient History Enhancement

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#803]
5 enhancement points in patient history page:

![klik tombol ini hingga berwarna hijau untuk memunculkan detail pertanyaan kontak (tracing kontak) (7)](https://user-images.githubusercontent.com/73918009/108787358-2889b100-75a8-11eb-9a59-5121bcb49935.png)

**Comment by vincent-karuri** [comment]
These are new requests and can be explore in a future release.

**Comment by ellyasafaa** [comment]
@vincent-karuri Yes, please proceed. Will follow up on a regular basis.
