### ISSUE TITLE
Punctuation Consistency

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#809]
Please kindly check all punctuation on all pages, including space, colon, question mark, and etc.
Found inconsistency in the space of IgG/IgM below

![Screenshot_20210218-174124_RDT Open Reader](https://user-images.githubusercontent.com/73918009/108790723-fd0ac480-75af-11eb-8d82-650da3e6ceef.jpg)

**Comment by vincent-karuri** [comment]
Could you provide all instances with this problem? These can be addressed in a later release.

**Comment by mwkhan1983** [comment]
@ellyasafaa Please provide all instances with punctuation inconsistency by Monday, 1st March

**Comment by ellyasafaa** [comment]
Apart from the RDT type on the manually record the RDT info above, please find all inconsistencies. Apologies, I put also in the same image for the inconsistent capitalization. Thank you
![klik tombol ini hingga berwarna hijau untuk memunculkan detail pertanyaan kontak (tracing kontak) (18)](https://user-images.githubusercontent.com/73918009/109463099-0f489f00-7a97-11eb-986a-29230339c237.png)
