### ISSUE TITLE
Adding Antigen RDT Configuration

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#812]
So CJ sent us the way to have the configuration result, I can do the 1st step to have the image, but is not able to do the other steps. This is really important to be added to the apps asap, because there will be 2 main RDTs that will be deployed: Alltest Antibody and Alltest Antigen RDT. Do you have any suggestions for this?

@mwkhan1983 @vincent-karuri @syedowaisali90

**Comment by vincent-karuri** [comment]
@mwkhan1983 do you know which RDTs these are? I think we already have one Alltest version.

**Comment by ellyasafaa** [comment]
@vincent-karuri The current that has been on the apps is Alltest Antibody Test, the antigen one, you have the info on the sheet, but there is no configuration yet.

**Comment by mwkhan1983** [comment]
@ellyasafaa this the RDT "Alltest 2019-nCoV IgG/IgM" we have in [FHIR Device definition sheet](https://docs.google.com/spreadsheets/d/1P9yCzXHoy9Dz0_hp43GX_qpOc6Ayvz_D2TCReNVN_n4/edit#gid=0) and this is also part of the app. There is no other Alltest RDT which is part of the list currently.

**Comment by ellyasafaa** [comment]
@mwkhan1983 Oh, just rechecked and there is no row for that yet. 

I think we can provide the information below, do you have the definition for each? I am aware that we can define it by ourselves from the title of the column, but just to make sure that the information given is correct.
RDT_type | GTIN | Product Code | Lines | Sampletypes | Steps | Sampleqty drops | Sampleqty uL | Bufferqty drops | Bufferqty drops max | Bufferqty uL | minimumtimeforresult | maximumtimeforresult | low_temp | high_temp

But for the RDTScan configuration, I think I am just able to give you the image. How does that sound?

**Comment by ellyasafaa** [comment]
If the configuration existed, how long will it take to merge it in the apps?

**Comment by mwkhan1983** [comment]
@ellyasafaa please provide the configuration in [FHIR device definition list](https://docs.google.com/spreadsheets/d/1P9yCzXHoy9Dz0_hp43GX_qpOc6Ayvz_D2TCReNVN_n4/edit#gid=0) and reference image

**Comment by ellyasafaa** [comment]
Please kindly find the configuration and the reference image:

"covid19_prevent_tb": {
"REF_IMG": "covid19_prevent_tb_ref_v0",
"VIEW_FINDER_SCALE": 0.6,
"RESULT_WINDOW_TOP_LEFT": [111, 246],
"RESULT_WINDOW_BOTTOM_RIGHT": [144, 399],
"TOP_LINE_POSITION": [128, 295],
"MIDDLE_LINE_POSITION": [128, 362],
"TOP_LINE_NAME": "Control",
"MIDDLE_LINE_NAME": "Test",
"LINE_INTENSITY": 85
},
"covid19_preventplus_ag": {
"REF_IMG": "covid19_preventplus_ag_ref_v0",
"VIEW_FINDER_SCALE": 0.6,
"RESULT_WINDOW_TOP_LEFT": [106, 246],
"RESULT_WINDOW_BOTTOM_RIGHT": [138, 390],
"TOP_LINE_POSITION": [122, 278],
"MIDDLE_LINE_POSITION": [122, 331],
"TOP_LINE_NAME": "Control",
"MIDDLE_LINE_NAME": "Test",
"LINE_INTENSITY": 85
}

![covid19_prevent_tb_ref_v0](https://user-images.githubusercontent.com/73918009/109914530-c8e78000-7ce2-11eb-85c0-5e261def7218.jpg)
![covid19_preventplus_ag_ref_v0](https://user-images.githubusercontent.com/73918009/109914533-cab14380-7ce2-11eb-9cf9-2e4ff6accd59.jpg)

**Comment by mwkhan1983** [comment]
@ellyasafaa Please also provide **GTIN** for these RDTs

**Comment by ellyasafaa** [comment]
@mwkhan1983 

Antigen 6970277515719
Tb 6970277514095
Malaria 6970277514217

**Comment by ellyasafaa** [comment]
Since the configuration has not been tried yet, we don't know whether it will be successful or not.

**Comment by ellyasafaa** [comment]
> Please kindly find the configuration and the reference image:
> 
> "covid19_prevent_tb": {
> "REF_IMG": "covid19_prevent_tb_ref_v0",
> "VIEW_FINDER_SCALE": 0.6,
> "RESULT_WINDOW_TOP_LEFT": [111, 246],
> "RESULT_WINDOW_BOTTOM_RIGHT": [144, 399],
> "TOP_LINE_POSITION": [128, 295],
> "MIDDLE_LINE_POSITION": [128, 362],
> "TOP_LINE_NAME": "Control",
> "MIDDLE_LINE_NAME": "Test",
> "LINE_INTENSITY": 85
> },
> "covid19_preventplus_ag": {
> "REF_IMG": "covid19_preventplus_ag_ref_v0",
> "VIEW_FINDER_SCALE": 0.6,
> "RESULT_WINDOW_TOP_LEFT": [106, 246],
> "RESULT_WINDOW_BOTTOM_RIGHT": [138, 390],
> "TOP_LINE_POSITION": [122, 278],
> "MIDDLE_LINE_POSITION": [122, 331],
> "TOP_LINE_NAME": "Control",
> "MIDDLE_LINE_NAME": "Test",
> "LINE_INTENSITY": 85
> }
> 
> ![covid19_prevent_tb_ref_v0](https://user-images.githubusercontent.com/73918009/109914530-c8e78000-7ce2-11eb-85c0-5e261def7218.jpg)
> ![covid19_preventplus_ag_ref_v0](https://user-images.githubusercontent.com/73918009/109914533-cab14380-7ce2-11eb-9cf9-2e4ff6accd59.jpg)

I think for TB the name of the config should be different. Please kindly erase the covid19 on the Prevent TB including in the REF_IMG

**Comment by mwkhan1983** [comment]
@ellyasafaa please make the necessary changes and resend

**Comment by ellyasafaa** [comment]
You can simply change the name.

"Prevent_tb": {
"REF_IMG": "Prevent_tb_ref_v0",
"VIEW_FINDER_SCALE": 0.6,
"RESULT_WINDOW_TOP_LEFT": [111, 246],
"RESULT_WINDOW_BOTTOM_RIGHT": [144, 399],
"TOP_LINE_POSITION": [128, 295],
"MIDDLE_LINE_POSITION": [128, 362],
"TOP_LINE_NAME": "Control",
"MIDDLE_LINE_NAME": "Test",
"LINE_INTENSITY": 85
},
"covid19_preventplus_ag": {
"REF_IMG": "covid19_preventplus_ag_ref_v0",
"VIEW_FINDER_SCALE": 0.6,
"RESULT_WINDOW_TOP_LEFT": [106, 246],
"RESULT_WINDOW_BOTTOM_RIGHT": [138, 390],
"TOP_LINE_POSITION": [122, 278],
"MIDDLE_LINE_POSITION": [122, 331],
"TOP_LINE_NAME": "Control",
"MIDDLE_LINE_NAME": "Test",
"LINE_INTENSITY": 85
}

![covid19_preventplus_ag_ref_v0](https://user-images.githubusercontent.com/73918009/109922282-aad44c80-7cef-11eb-9570-884602eee51a.jpg)
![Prevent_tb_ref_v0](https://user-images.githubusercontent.com/73918009/109922285-ac057980-7cef-11eb-8c62-fa341b8532c8.jpg)

**Comment by mwkhan1983** [comment]
@ellyasafaa I have added config and ref image in required places. Please provide information in these columns in FHR device def sheet where missing for 2 RDTs provided (last 2 rows):
RDT_type | GTIN | Product Code | Lines | Sampletypes | Steps | Sampleqty drops | Sampleqty uL | Bufferqty drops | Bufferqty drops max | Bufferqty uL | minimumtimeforresult | maximumtimeforresult | low_temp | high_temp

I have given you temporary edit rights.

**Comment by ellyasafaa** [comment]
> @mwkhan1983
> 
> Antigen 6970277515719
> Tb 6970277514095
> Malaria 6970277514217

@mwkhan1983 I have added all information needed and just saw the comment about the GTIN that should be 14 digits. Sorry, when I double-checked it, I changed the GTIN and made it suitable with the information I shared with you here, so now it becomes 13 digits. Why should we have it 14 digits? Could you recheck and change what needed there?

**Comment by ellyasafaa** [comment]
For the antigen RDT, the one that we have tried to create the barcode is the 13 digits GTIN, should we change that to the 14 digits number? How will the GTIN information on the sheet be used on the apps? Which function of the apps will be affected?

**Comment by vincent-karuri** [comment]
The GTINs must be 14 digits, you can have a look at this issue https://github.com/onaio/rdt-standard/issues/302.

**Comment by vincent-karuri** [comment]
Official GTINs from manufacturers are 14 digits. If you create an artificial one, you should generate 13 unique digits + 1 check digit generated from the Luhn algoritm (used in validating the GTIN value).

**Comment by mwkhan1983** [comment]
@ellyasafaa for Malaria Prevent RDT, what each of these means in terms of capture and interpretation `C/Pan/P.v./P.f.`
since this application is for Covid, only following list of codes are supported:
```
   "C": "Control",
    "T": "Test",
    "G": "IgG",
    "M": "IgM",
    "G+M": "IgG / IgM"
```
We will be excluding Malaria Prevent RDT

**Comment by ellyasafaa** [comment]
> Official GTINs from manufacturers are 14 digits. If you create an artificial one, you should generate 13 unique digits + 1 check digit generated from the Luhn algoritm (used in validating the GTIN value).

@vincent-karuri 
From the issue there that you showed me, in the comment section, there is this info:

Packaging level 1 digit from 0 smallest unit to 8 being a pallet. In this example, it is “0”
Company unique identification and product code. In this example, it is the number from ALL TEST and it is “697027751469”
Check Digit and in this case the value is “9”

Dr. Anu told me that there is no check digit for the GTIN, the GTIN typically has a leading 0. The number read from the barcode has a leading 0. That makes 14 digits in the GTIN standard. It is not the check digit that does that. So, to make it 14 digits, it is the packaging level 1 digit.

**Comment by ellyasafaa** [comment]
Don't forget to change the GTIN

Malaria: 06970277514217
Antigen: 06970277515719
TB: 06970277514095
