### ISSUE TITLE
Token is expiring but user is not logged out

### ISSUE THREAD

**Issue by mwkhan1983** [onaio/rdt-standard#814]
While syncing I am getting the error. See snapshot attached. I have logged out and then logged in, still the same issue, unable to sync due to authentication error. Then cleared data, logged in and finally able to sync.

![Screenshot_20210223-132132](https://user-images.githubusercontent.com/69383347/108820850-994bc000-75de-11eb-9c1a-04047329c77f.png)

**Comment by ellyasafaa** [comment]
@mwkhan1983 finding the same issue in the production version

**Comment by ellyasafaa** [comment]
not only during the sync process, sometimes it appeared after logging in
