### ISSUE TITLE
Track device acceleration (motion) and rdt capture activity response time

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#83]
We need to detect if the device is in motion while it's being used.

We also need to gauge how long ti takes for the rdt capture activity to capture an image.

**Comment by shivenbhatt1** [comment]
@vincent-karuri The second part is built into the UW reader code is it not?

**Comment by vincent-karuri** [comment]
yes it is

**Comment by vincent-karuri** [comment]
And I think you mentioned not implementing the first?

**Comment by shivenbhatt1** [comment]
If we do it, not a priority

**Comment by vincent-karuri** [comment]
Closing, not implementing this
