### ISSUE TITLE
Sign in token expires and App shows  "Sign-in error for indtester1" even when successfully logged in on the device notification bar

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#834]
Sign in token expires and App shows  "Sign-in error for indtester1" even when successfully logged in on the device notification bar

![Screenshot_20210302-165750_RDT Open Reader](https://user-images.githubusercontent.com/29072646/109659210-80ac4e80-7b78-11eb-848a-65a4f93d7d91.jpg)

**Comment by vincent-karuri** [comment]
closing as duplicate of https://github.com/onaio/rdt-standard/issues/814
