### ISSUE TITLE
Design issue. The back arrow after one selects "Scan barcode" looks floating

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#836]
Design issue. The back arrow after one selects "Scan barcode" looks floating

--See Screenshot

![Screenshot_20210302-163915_RDT Open Reader](https://user-images.githubusercontent.com/29072646/109659715-07612b80-7b79-11eb-9a12-7d9c749218d8.jpg)

**Comment by vincent-karuri** [comment]
is onescan installed on the device?

**Comment by Mstjamush** [comment]
@vincent-karuri let me test with oneScan and revert

**Comment by Mstjamush** [comment]
@vincent-karuri Tested. Issue was OneScan but we will need to inform the user to install OneScan. This was in one of the previous versions.

**Comment by vincent-karuri** [comment]
@Mstjamush I agree with showing a message to the user

**Comment by vincent-karuri** [comment]
ok, closing as resolved
