### ISSUE TITLE
Add sync button and toggle button to hamburger menu 

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#88]
Add a sync button and a separate button that toggles image sync on/off.

This should ideally be accessed from a drawer menu that is accessed from the hamburger menu on the [register page](https://marvelapp.com/4b1bje0/screen/58413507).

**Comment by rowo** [comment]
@vincent-karuri 

What would the content be for the sync buttons (label and any other information)? Is the image sync toggle a sub-option of Sync?

**Comment by vincent-karuri** [comment]
Sync button that just says `Sync`, a logout button `Logout`,  and the image sync toggle that is a stand-alone option by itself.

**Comment by rowo** [comment]
@vincent-karuri this what you meant?

![Menu-toggleoff](https://user-images.githubusercontent.com/1584163/61151588-4e863e80-a4b4-11e9-8a99-0a147e89c54a.png)
![Menu-toggleon](https://user-images.githubusercontent.com/1584163/61151589-4e863e80-a4b4-11e9-86ef-266744b838f0.png)

**Comment by vincent-karuri** [comment]
@rowo this is good, thanks
