### ISSUE TITLE
Last sync time not refreshing when you stay on home screen 

### ISSUE THREAD

**Issue by mwkhan1983** [onaio/rdt-standard#897]
Press Sync. When sync is completed, see that the last sync time does not refresh in drawer menu. Now navigate away from home screen and then come back to the home screen. Open drawer menu, it shows updated last sync time.

**Comment by mwkhan1983** [comment]
@syedowaisali90 its good that sync time is refreshing now when stay on home screen. However, if you navigate to some other screen and come back to home screen, sync date/time is not shown.

**Comment by syedowaisali90** [comment]
@mwkhan1983 https://github.com/onaio/rdt-standard/pull/899#discussion_r590264562

**Comment by mwkhan1983** [comment]
@syedowaisali90 problem in this case is we have to sync every time to see the last sync time.  Without it, it never shows you time except you stay on home screen :)
