### ISSUE TITLE
Design for stick/outside bag of our RDT

### ISSUE THREAD

**Issue by pld** [onaio/rdt-standard#90]
Design a layout for the outside of the bag our RDT will be packaged in.

It should be similar but not the same as the CareStart bag design, it should have an Ona logo (like this has an AccessBio logo).

It should be called the "Open Guidelines RDT" probably

**Comment by pld** [comment]
![Image from iOS](https://user-images.githubusercontent.com/50706/61151273-7a69ea00-a4dd-11e9-9381-054ff9a4fbf9.jpg)

carestart bag design to base our label design on

**Comment by rowo** [comment]
@pld do you have a physical dimension for this bag and any requirements from the packaging manufacturer I should be considering? They might have a die template.

**Comment by pld** [comment]
I do not. @shivenbhatt1 can you please get this from mologic
