### ISSUE TITLE
Changing the format of WhatsApp number and Household phone number to be in phone-number format

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#903]
The WhatsApp number and household phone number in the new client record are in text format. Phone number information will be important, so if it is mistakenly typed with text, it will ruin the validity of the data.

**Comment by syedowaisali90** [comment]
@yussin-hidayat Please add those keys and value https://github.com/onaio/rdt-standard/blob/b6bd1ae5618c47f42edb2d8dddc3dedd21870332/rdt-open-reader/src/covidIndonesia/assets/json.form/patient-registration-form.json#L526-L540 in `patient-registration-form.properties` file

**Comment by mwkhan1983** [comment]
@yussin-hidayat app crashing on opening new client record form so this could not be tested
