### ISSUE TITLE
The RDT data displayed in history does not cover all information needed

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#906]
![Patient History Form](https://user-images.githubusercontent.com/73918009/110579397-502c6c00-8199-11eb-9dad-203ada3417ab.png)

This is critical to be solved since the information is important to be known by the user.

**Comment by vincent-karuri** [comment]
@mwkhan1983 isn't this marked as SID [here](https://drive.google.com/file/d/1SQOvfdUGgQ7G3ePux65G9K3DJYKmiiHN/view)?

**Comment by mwkhan1983** [comment]
Since Owais is looking at history issue and SID would be engaged with
Adding RDT type and health facilities issue from Friday, it would be  good
if Owais can look into this.

We can then transfer knowledge about this in one of the calls.

**Comment by vincent-karuri** [comment]
we still have 4 and 11 outstanding that was originally allocated ona/sid, right?

**Comment by vincent-karuri** [comment]
We'll swap this issue out for https://github.com/onaio/rdt-standard/issues/830 since it's blocked by https://github.com/onaio/rdt-standard/issues/830#issuecomment-795654818.
