### ISSUE TITLE
Android 10 - Symptoms and history - forms does not allow you to go back to previous form

### ISSUE THREAD

**Issue by mwkhan1983** [onaio/rdt-standard#915]
Tap on Symptoms and history, fill in pre-existing conditions form and press continue. Once on next form, try to press android back button. It will not move to previous form.

**Comment by syedowaisali90** [comment]
@mwkhan1983 I have also Android 10 and the form working fine on the steps that you have described. Therefore, could you share a video of what you are doing.

cc: @vincent-karuri

**Comment by mwkhan1983** [comment]
@syedowaisali90 you have to check this on separate branch of code. Native forms PR is merged in that code I believe. That code is not merged with master. @vincent-karuri can better guide on that.

**Comment by syedowaisali90** [comment]
@mwkhan1983 I have tested the issue by using the master branch. So, if the issue was fixed in some other branch and that has been merged in master then why we checking this issue in another branch.

**Comment by vincent-karuri** [comment]
All issues marked as Android 10 should be tested on https://github.com/onaio/rdt-standard/pull/591. Update this with latest master before proceeding with testing.
