### ISSUE TITLE
Android 10 - White screen when pressing back after Scan barcode function

### ISSUE THREAD

**Issue by mwkhan1983** [onaio/rdt-standard#916]
Steps to reproduce:

1. Tap on RDT
2.  Tap on Locate Me
3. Tap on Continue
4. Select facility and tap on continue
5. tap on Scan barcode
6. Tap back button

It is showing white screen.

**Comment by syedowaisali90** [comment]
@mwkhan1983 it's working fine for me, could you show me a short video

**Comment by mwkhan1983** [comment]
not reproducing on latest version
