### ISSUE TITLE
Android 10 - Issue with Shipping preparation scan barcode

### ISSUE THREAD

**Issue by mwkhan1983** [onaio/rdt-standard#918]
Please see the attached video

https://drive.google.com/file/d/1sX-kYYw1du99x3u99_FYLgxY8UcckdW8/view?usp=sharing

**Comment by vincent-karuri** [comment]
@mwkhan1983 Could you point the camera at one barcode at a time?

**Comment by mwkhan1983** [comment]
> @mwkhan1983 Could you point the camera at one barcode at a time?

https://drive.google.com/file/d/1sjb-otPwJwZ-eccdvU89soGRLUPIyI8Q/view?usp=sharing

**Comment by vincent-karuri** [comment]
thanks, what exactly is the issue here? That the preview screen briefly appears?
