### ISSUE TITLE
Cannot log in although the username and creds are correct

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#922]
It won't log in although the username and creds are correct.

This is the condition after logging out (not freshly installed):
https://drive.google.com/file/d/12IVR3NoksxPf6mp_urqt0AnDmxkNzxbJ/view?usp=sharing

And the second condition is after crashes happened, it won't log in. After clearing the data, it then wants to log in. I think this should be fixed.
https://drive.google.com/file/d/1270jdZb6soo3au4XywhwU0CRKw1X_3SJ/view?usp=sharing

@vincent-karuri @mwkhan1983 @syedowaisali90

**Comment by ellyasafaa** [comment]
It happened on Samsung J5 Android 9, Redmi 5 Plus Android 7.1.2, and Oppo A5S Android 8.1.0

**Comment by ellyasafaa** [comment]
I'm pretty sure Mas Yussin experienced the issue as well

**Comment by vincent-karuri** [comment]
@ellyasafaa where is `rarang_lotim` in the [list of users](https://docs.google.com/spreadsheets/d/1tGc3IDLwxZ3QMg7_kjWHov_n8VOsl080MXFF3ZY9UDQ/edit#gid=1625211032)? Isn't it `rarang_lotim1`?

Also, you shouldn't be mixing logins on the same device, use one login on one device.

Also, I hope the drive links are not public. The videos expose the login credentials for the app.

**Comment by ellyasafaa** [comment]
@vincent-karuri My bad. The first video was not checked correctly.

```Also, you shouldn't be mixing logins on the same device, use one login on one device.```
Yes, I am aware of that. Just experimenting in case it can work.

```Also, I hope the drive links are not public. The videos expose the login credentials for the app.```
Yes, of course. This is a restricted folder. Only Wasim and you can check that without requesting access. If Owais, for example, want to check that, he still needs permission from me.

**Comment by vincent-karuri** [comment]
For the second video, please provide clear steps to reproduce it. I'd advise looping in your IT team as needed as they may be looking into this issue.

**Comment by vincent-karuri** [comment]
Closing this as stale.
