### ISSUE TITLE
When connectivity is there, allow for a remote login

### ISSUE THREAD

**Issue by mwkhan1983** [onaio/rdt-standard#955]
Allowing remote login in case of connectivity will help improve user experience in case session is expired. Currently when user logs out and then logs in again after some time (but assume session has expired), it logs user out again informing your session has expired. For an offline app, this is a genuine case but from user experience perspective, this looks odd.
Remote login will help improve user experience by renewing the session.

**Comment by vincent-karuri** [comment]
Cool, there's still the problem that if the session max is reached, the user will still be logged out.

**Comment by vincent-karuri** [comment]
Cool, have you tested what happens when the session max is reached and one tries to log in?

**Comment by mwkhan1983** [comment]
I haven't tested that scenario since before session max timeout, session idle timeout happens first the way it was configured. Until both are configured close to each other, 8 hours and 10 hours respectively for example,  that scenario is unlikely to happen.

**Comment by mwkhan1983** [comment]
I believe whether session idle timeout happens or session max time out happens, the behavior should be the same and will be the same.

**Comment by vincent-karuri** [comment]
Cool, when the session max is reached and one tries to log in, does the app login then logout or does it stay on the login screen with an error message. Because this could be another consideration separate from idle timeout.

**Comment by mwkhan1983** [comment]
So there are two scenarios possible:

1. User logs out
2. User does not log out, just move the app to the background

Log out scenario I have described above.

In 2nd scenario, when user resumes, message appears that session has expired and user is taken to login screen. When user logins again, it starts with the new session. So this case is handled the way it should be

**Comment by vincent-karuri** [comment]
Ok, so if remote login works for both session idle and session max, then this is fine.

**Comment by syedowaisali90** [comment]
Remote login should be false when no network available.

**Comment by syedowaisali90** [comment]
closing this with the ref  https://github.com/onaio/rdt-standard/pull/962#discussion_r622929803
