### ISSUE TITLE
Alarm goes off when not in form 

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#98]
Alarm goes off even when one exits the register form, from the 20-min timer screen

**Comment by allan-allay** [comment]
When exiting the countdown timer screen before the countdown is finished, the countdown continues in the background and the alarm rings on finish. 
The fix is to `cancel()` the countdown timer on the exit of the screen

**Comment by allan-allay** [comment]
Fixed in Native forms https://github.com/OpenSRP/opensrp-client-native-form/commit/2af4a56e06019bb19fe2ae537c3198abfa1b6ba2

**Comment by vincent-karuri** [comment]
Fixed
