### ISSUE TITLE
Fix truncated text in RDT pictorial screen

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#99]
![Screenshot_20190722-125916](https://user-images.githubusercontent.com/33488286/61624652-b2adbd00-ac81-11e9-8ed0-703a8db802dd.png)

**Comment by allan-allay** [comment]
Could not reproduce this. 
I tested wrapping of long text in the native forms library ImageView widget as well as how this is rendered in the RDT app in an emulator and an actual device, but could not reproduce what's shown above. 
Attached are screenshots of my outcomes
![Screenshot_Samsung_rdt-app](https://user-images.githubusercontent.com/16164649/61718108-f3353580-ad6a-11e9-804a-d
![Screenshot_emulator](https://user-images.githubusercontent.com/16164649/61718232-3db6b200-ad6b-11e9-9d90-521117f0ec9c.png)
849f5912af6.jpg)

**Comment by allan-allay** [comment]
Fixed in Native forms https://github.com/OpenSRP/opensrp-client-native-form/issues/247

**Comment by vincent-karuri** [comment]
Done
